{
  "hash": "98461a22ec3cc6913f83ff4fd8fed958",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Association Between Two Numeric Variables\"\noutput:\n  pdf_document:\n    number_sections: yes\n  html_document: default\neditor_options:\n  chunk_output_type: console\n---\n\n\n\n\n\n# Learning Objectives {.unnumbered}\n\nBy the end of this chapter, you should be able to:\n\n1.  Explain what it means for two numeric (continuous) variables to be \"associated,\" and describe that association using a scatter diagram.\n2.  State the definition, assumptions, properties, and correct interpretation of the **Pearson product-moment correlation coefficient** ($r$).\n3.  Calculate $r$ **by hand** from raw data, test $H_0: \\rho = 0$, and construct a confidence interval for $\\rho$.\n4.  State the definition, assumptions, properties, and correct interpretation of the **Spearman rank correlation coefficient** ($r_s$ or $\\rho_s$).\n5.  Calculate $r_s$ **by hand**, including the correction needed when tied ranks are present.\n6.  Reproduce both coefficients in **R**, using the Western Collaborative Group Study (**WCGS**) data set as a worked example, and correctly choose between Pearson and Spearman for a given pair of variables.\n7.  Recognise common pitfalls in interpreting correlation coefficients.\n\n------------------------------------------------------------------------\n\n# Association Between Two Numeric Variables\n\nIn epidemiology and clinical research we frequently ask whether two **quantitative (numeric)** characteristics measured on the same individuals tend to move together — for example, does systolic blood pressure rise with age? Does body weight track with height? Does serum cholesterol relate to blood pressure?\n\n**Association** (or *correlation*, used loosely) between two numeric variables describes the tendency of one variable to change systematically as the other changes. It has three components that should always be examined together:\n\n-   **Direction** — do the variables move in the same direction (*positive* association) or opposite directions (*negative* association)?\n-   **Strength** — how closely do the points cluster around a discernible trend?\n-   **Form** — is the trend linear, curvilinear (monotonic but not straight), or is there no discernible pattern?\n\n## The scatter diagram\n\nThe scatter diagram (scatterplot) is the essential first step in *any* correlation analysis — a numeric summary should never be trusted without first looking at the data.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(wcgs, aes(x = height, y = weight)) +\n  geom_point(alpha = 0.25, colour = \"steelblue\") +\n  geom_smooth(method = \"lm\", se = FALSE, colour = \"firebrick\") +\n  labs(x = \"Height (inches)\", y = \"Weight (lb)\",\n       title = \"Height vs. weight, WCGS cohort (n = 3,154)\") +\n  theme_minimal(base_size = 12)\n```\n\n::: {.cell-output-display}\n![Height and weight in the WCGS cohort (each point is one man).](12_1_Correlation_files/figure-html/fig-scatter-intro-1.png){#fig-scatter-intro fig-align='center' width=85%}\n:::\n:::\n\n\nTwo correlation coefficients dominate practice, and this chapter covers both:\n\n|   | **Pearson** $r$ | **Spearman** $r_s$ |\n|----|----|----|\n| Measures | Strength of **linear** association | Strength of **monotonic** association |\n| Uses | Raw values | **Ranks** of the values |\n| Best suited to | Approximately normal, linearly related continuous data | Ordinal data, non-normal data, data with outliers, or monotonic-but-curved relationships |\n\n------------------------------------------------------------------------\n\n## Pearson Product-Moment Correlation Coefficient\n\n### Definition {#sec-ppmc}\n\nFor a population, the Pearson correlation coefficient is\n\n$$\n\\rho = \\frac{\\operatorname{Cov}(X,Y)}{\\sigma_X\\,\\sigma_Y}\n$$\n\nFor a sample of $n$ paired observations $(x_i, y_i)$, it is estimated by\n\n$$\nr = \\frac{\\displaystyle\\sum_{i=1}^{n}(x_i-\\bar x)(y_i-\\bar y)}\n        {\\sqrt{\\displaystyle\\sum_{i=1}^{n}(x_i-\\bar x)^2 \\; \\sum_{i=1}^{n}(y_i-\\bar y)^2}}\n$$ {#eq-pearson-deviation}\n\nan equivalent **computational (raw-score) formula**, more convenient for hand calculation, is\n\n$$\nr = \\frac{n\\sum x_iy_i - \\left(\\sum x_i\\right)\\left(\\sum y_i\\right)}\n        {\\sqrt{\\left[n\\sum x_i^2-\\left(\\sum x_i\\right)^2\\right]\\left[n\\sum y_i^2-\\left(\\sum y_i\\right)^2\\right]}}\n$$ {#eq-pearson-raw}\n\n## Assumptions\n\n1.  Both $X$ and $Y$ are **continuous (interval/ratio) numeric** variables.\n2.  The relationship between $X$ and $Y$ is (approximately) **linear**.\n3.  For inference (hypothesis tests / CIs), the pairs $(X,Y)$ come from a **bivariate normal distribution** — in practice this is usually checked by inspecting the marginal distributions of $X$ and $Y$ for gross non-normality and skew.\n4.  Observations are **independent** of one another.\n5.  No excessively influential **outliers**.\n6.  Variance of $Y$ is reasonably constant across the range of $X$ (homoscedasticity).\n\n## Properties\n\n-   $-1 \\le r \\le 1$; $r=1$ is perfect positive linear association, $r=-1$ perfect negative linear association, $r=0$ no *linear* association.\n-   $r$ is **unit-free** (dimensionless) and **symmetric**: $r_{xy} = r_{yx}$.\n-   $r$ measures only **linear** association — a strong curved relationship can produce a small $r$.\n-   $r$ is sensitive to **outliers** and to **restriction of range**.\n-   $r^2$ (the **coefficient of determination**) is the proportion of variance in $Y$ \"explained\" by the linear relationship with $X$.\n-   Correlation does **not** imply causation.\n\n## A rule-of-thumb interpretation scale\n\n| $|r|$       | Strength of linear association |\n|-------------|--------------------------------|\n| 0.00 – 0.09 | Negligible                     |\n| 0.10 – 0.39 | Weak                           |\n| 0.40 – 0.69 | Moderate                       |\n| 0.70 – 0.89 | Strong                         |\n| 0.90 – 1.00 | Very strong                    |\n\nThese cut-points (adapted from conventions such as Cohen, 1988) are a rough guide only; the meaningfulness of a given $r$ always depends on the substantive context.\n\n## Hypothesis test for $\\rho$\n\nTo test $H_0: \\rho = 0$ versus $H_1: \\rho \\ne 0$:\n\n$$\nt = r\\sqrt{\\frac{n-2}{1-r^2}} \\qquad \\sim \\; t_{(n-2)} \\text{ under } H_0\n$$ {#eq-pearson-t}\n\n## Confidence interval for $\\rho$ (Fisher's $z$-transformation)\n\nBecause the sampling distribution of $r$ is skewed (except when $\\rho=0$), Fisher's $z$-transformation is used:\n\n$$\nz' = \\tfrac12 \\ln\\!\\left(\\frac{1+r}{1-r}\\right), \\qquad SE(z') = \\frac{1}{\\sqrt{n-3}}\n$$\n\nA $95\\%$ CI for $z'$ is $z' \\pm 1.96 \\times SE(z')$; each limit is back-transformed with\n\n$$\nr = \\frac{e^{2z'}-1}{e^{2z'}+1}\n$$\n\n------------------------------------------------------------------------\n\n# Manual (Hand) Calculation of Pearson $r$\n\nWe illustrate the arithmetic with a small, reproducible random sample of $n=10$ men drawn from the WCGS data, using **height** (inches) and **weight** (lb).\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(123)\nidx <- sample(seq_len(nrow(wcgs)), 10)\nsub <- as.data.frame(wcgs[idx, c(\"id\", \"height\", \"weight\")])\nnames(sub) <- c(\"id\", \"x_height\", \"y_weight\")\nkable(sub, caption = \"Random subsample (n = 10) used for the manual Pearson calculation\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Random subsample (n = 10) used for the manual Pearson calculation\n\n|    id| x_height| y_weight|\n|-----:|--------:|--------:|\n| 11348|       74|      290|\n| 22029|       69|      160|\n| 13114|       67|      165|\n| 11238|       72|      187|\n|  3777|       72|      160|\n| 10157|       67|      145|\n| 21192|       67|      155|\n| 21159|       68|      156|\n|  3944|       66|      145|\n|  3118|       72|      187|\n\n\n:::\n:::\n\n\n## Step 1: Compute the deviation table\n\nFor each subject we need $x-\\bar x$, $y-\\bar y$, their product, and their squares.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nx <- sub$x_height; y <- sub$y_weight\nn <- length(x)\nxbar <- mean(x); ybar <- mean(y)\n\ntab <- data.frame(\n  id     = sub$id,\n  x      = x,\n  y      = y,\n  dx     = round(x - xbar, 2),\n  dy     = round(y - ybar, 2),\n  dx_dy  = round((x - xbar) * (y - ybar), 2),\n  dx2    = round((x - xbar)^2, 2),\n  dy2    = round((y - ybar)^2, 2)\n)\nkable(tab, col.names = c(\"ID\",\"x (height)\",\"y (weight)\",\"$x-\\\\bar x$\",\"$y-\\\\bar y$\",\n                          \"$(x-\\\\bar x)(y-\\\\bar y)$\",\"$(x-\\\\bar x)^2$\",\"$(y-\\\\bar y)^2$\"))\n```\n\n::: {.cell-output-display}\n\n\n|    ID| x (height)| y (weight)| $x-\\bar x$| $y-\\bar y$| $(x-\\bar x)(y-\\bar y)$| $(x-\\bar x)^2$| $(y-\\bar y)^2$|\n|-----:|----------:|----------:|----------:|----------:|----------------------:|--------------:|--------------:|\n| 11348|         74|        290|        4.6|        115|                  529.0|          21.16|          13225|\n| 22029|         69|        160|       -0.4|        -15|                    6.0|           0.16|            225|\n| 13114|         67|        165|       -2.4|        -10|                   24.0|           5.76|            100|\n| 11238|         72|        187|        2.6|         12|                   31.2|           6.76|            144|\n|  3777|         72|        160|        2.6|        -15|                  -39.0|           6.76|            225|\n| 10157|         67|        145|       -2.4|        -30|                   72.0|           5.76|            900|\n| 21192|         67|        155|       -2.4|        -20|                   48.0|           5.76|            400|\n| 21159|         68|        156|       -1.4|        -19|                   26.6|           1.96|            361|\n|  3944|         66|        145|       -3.4|        -30|                  102.0|          11.56|            900|\n|  3118|         72|        187|        2.6|         12|                   31.2|           6.76|            144|\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Column sums:\\n\",\n    \" sum(x) =\", sum(x), \"  sum(y) =\", sum(y), \"\\n\",\n    \" sum[(x-xbar)(y-ybar)] =\", sum(tab$dx_dy), \"\\n\",\n    \" sum[(x-xbar)^2]       =\", sum(tab$dx2), \"\\n\",\n    \" sum[(y-ybar)^2]       =\", sum(tab$dy2), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> Column sums:\n#>   sum(x) = 694   sum(y) = 1750 \n#>   sum[(x-xbar)(y-ybar)] = 831 \n#>   sum[(x-xbar)^2]       = 72.4 \n#>   sum[(y-ybar)^2]       = 16624\n```\n\n\n:::\n:::\n\n\n## Step 2: Apply the deviation formula\n\n$$\n\\bar x = \\frac{694}{10}=69.4 \\qquad \\bar y=\\frac{1750}{10}=175.0\n$$\n\n$$\nr=\\frac{\\sum(x-\\bar x)(y-\\bar y)}{\\sqrt{\\sum(x-\\bar x)^2 \\sum(y-\\bar y)^2}}\n =\\frac{831.0}{\\sqrt{72.4 \\times 16624}}\n =\\frac{831.0}{\\sqrt{1{,}203{,}977.6}}\n =\\frac{831.0}{1097.26}\n$$\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nr_manual <- sum(tab$dx_dy) / sqrt(sum(tab$dx2) * sum(tab$dy2))\nr_manual\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> [1] 0.7574675\n```\n\n\n:::\n:::\n\n\n**By hand,** $r = 0.757$ — a strong, positive linear association between height and weight in this subsample.\n\n### Cross-check with the computational (raw-score) formula\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nSx <- sum(x); Sy <- sum(y); Sxy <- sum(x*y); Sx2 <- sum(x^2); Sy2 <- sum(y^2)\nr_raw <- (n*Sxy - Sx*Sy) / sqrt((n*Sx2 - Sx^2) * (n*Sy2 - Sy^2))\ndata.frame(Sx, Sy, Sxy, Sx2, Sy2, r_raw)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>    Sx   Sy    Sxy   Sx2    Sy2     r_raw\n#> 1 694 1750 122281 48236 322874 0.7574675\n```\n\n\n:::\n:::\n\n\nBoth formulas agree exactly, as they must algebraically.\n\n## Step 3: Test $H_0: \\rho = 0$\n\n$$\nt = r\\sqrt{\\frac{n-2}{1-r^2}} = 0.757\\sqrt{\\frac{8}{1-0.757^2}}\n$$\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nt_manual  <- r_manual * sqrt((n - 2) / (1 - r_manual^2))\ndf_manual <- n - 2\np_manual  <- 2 * pt(-abs(t_manual), df = df_manual)\ndata.frame(t = t_manual, df = df_manual, p_value = p_manual)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>         t df    p_value\n#> 1 3.28156  8 0.01116178\n```\n\n\n:::\n:::\n\n\nWith $t = 3.28$ on $8$ df, $p = 0.011$: we reject $H_0$ at the $5\\%$ level and conclude there is a statistically significant positive linear association between height and weight in this small sample.\n\n## Step 4: Verify against R's built-in function\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncor.test(x, y, method = \"pearson\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> \n#> \tPearson's product-moment correlation\n#> \n#> data:  x and y\n#> t = 3.2816, df = 8, p-value = 0.01116\n#> alternative hypothesis: true correlation is not equal to 0\n#> 95 percent confidence interval:\n#>  0.2444014 0.9391791\n#> sample estimates:\n#>       cor \n#> 0.7574675\n```\n\n\n:::\n:::\n\n\nThe hand-calculated $r$, $t$, $df$, and $p$-value match R's `cor.test()` output exactly — confirming the manual arithmetic.\n\n------------------------------------------------------------------------\n\n# Spearman Rank Correlation Coefficient\n\n## When to use Spearman instead of Pearson {#sec-spearman}\n\nSpearman's coefficient should be preferred over Pearson's when:\n\n-   The variables are **ordinal** rather than truly numeric (e.g., pain scores, tumour grade).\n-   The data are numeric but **markedly non-normal or skewed** (Pearson's inferential validity is weakened).\n-   There are **influential outliers** that would distort $r$.\n-   The relationship is **monotonic but not linear** (consistently increasing or decreasing, but curved) — Spearman still detects this fully, whereas Pearson under-estimates it.\n\n## Definition\n\nSpearman's rank correlation is simply the Pearson correlation coefficient computed on the **ranks** of $X$ and $Y$ rather than on their raw values. If there are no tied ranks, this simplifies to the well-known shortcut formula:\n\n$$\nr_s = 1-\\frac{6\\sum_{i=1}^n d_i^2}{n(n^2-1)}, \\qquad d_i = \\operatorname{rank}(x_i)-\\operatorname{rank}(y_i)\n$$ {#eq-spearman}\n\n**Tied values** are given the **average of the ranks** they would otherwise occupy. When ties are present, @eq-spearman is only an *approximation*; the exact value is obtained by computing the ordinary Pearson formula (@eq-pearson-deviation) on the rank-transformed data. Software (including R) uses this ties-corrected version by default.\n\n## Assumptions and properties\n\n-   Requires only that the data be at least **ordinal**, and that the relationship be **monotonic**.\n-   $-1 \\le r_s \\le 1$, same interpretation of sign and magnitude as Pearson's $r$, but describing a **monotonic** rather than strictly linear trend.\n-   Far more **robust to outliers** than Pearson's $r$, because extreme values are pulled in by ranking.\n-   Hypothesis test of $H_0: \\rho_s = 0$ can use the same $t$-approximation as Pearson's (@eq-pearson-t), substituting $r_s$ for $r$, for moderate/large $n$; exact permutation-based $p$-values are used for small $n$ without ties.\n\n------------------------------------------------------------------------\n\n# Manual (Hand) Calculation of Spearman $r_s$\n\nWe again draw a reproducible random subsample of $n=10$ men (this time keeping only those with a recorded cholesterol value) and examine **total cholesterol** (`chol`, mg/dL) against **systolic blood pressure** (`sbp`, mmHg) — two variables that are typically right-skewed, making Spearman a more defensible choice than Pearson.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(321)\nidx2 <- sample(which(!is.na(wcgs$chol)), 10)\nsub2 <- as.data.frame(wcgs[idx2, c(\"id\", \"chol\", \"sbp\")])\nkable(sub2, caption = \"Random subsample (n = 10, complete cholesterol) used for the manual Spearman calculation\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Random subsample (n = 10, complete cholesterol) used for the manual Spearman calculation\n\n|    id| chol| sbp|\n|-----:|----:|---:|\n|  3574|  279| 130|\n| 12432|  288| 122|\n|  3562|  205| 128|\n|  2242|  212| 152|\n| 12334|  164| 120|\n| 16026|  230| 138|\n|  3711|  175| 120|\n|  3069|  241| 120|\n|  3739|  228| 110|\n|  3281|  205| 116|\n\n\n:::\n:::\n\n\n## Step 1: Rank each variable separately\n\nRanks are assigned from lowest (rank 1) to highest; **tied values receive the average of the ranks they span**. Notice that `sbp` = 120 occurs three times (ranks 3, 4, 5 → averaged to 4).\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncx <- sub2$chol; cy <- sub2$sbp\nrx <- rank(cx); ry <- rank(cy)\nd  <- rx - ry\nd2 <- d^2\n\ntab2 <- data.frame(id = sub2$id, chol = cx, sbp = cy,\n                    rank_chol = rx, rank_sbp = ry, d = d, d2 = d2)\nkable(tab2, col.names = c(\"ID\",\"Cholesterol\",\"SBP\",\"Rank (chol)\",\"Rank (sbp)\",\"$d$\",\"$d^2$\"))\n```\n\n::: {.cell-output-display}\n\n\n|    ID| Cholesterol| SBP| Rank (chol)| Rank (sbp)|  $d$| $d^2$|\n|-----:|-----------:|---:|-----------:|----------:|----:|-----:|\n|  3574|         279| 130|         9.0|          8|  1.0|  1.00|\n| 12432|         288| 122|        10.0|          6|  4.0| 16.00|\n|  3562|         205| 128|         3.5|          7| -3.5| 12.25|\n|  2242|         212| 152|         5.0|         10| -5.0| 25.00|\n| 12334|         164| 120|         1.0|          4| -3.0|  9.00|\n| 16026|         230| 138|         7.0|          9| -2.0|  4.00|\n|  3711|         175| 120|         2.0|          4| -2.0|  4.00|\n|  3069|         241| 120|         8.0|          4|  4.0| 16.00|\n|  3739|         228| 110|         6.0|          1|  5.0| 25.00|\n|  3281|         205| 116|         3.5|          2|  1.5|  2.25|\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Sum of d^2 =\", sum(d2), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> Sum of d^2 = 114.5\n```\n\n\n:::\n:::\n\n\n## Step 2: Apply the shortcut formula (ignoring ties)\n\n$$\nr_s \\approx 1-\\frac{6\\sum d_i^2}{n(n^2-1)} = 1-\\frac{6(114.5)}{10(100-1)} = 1-\\frac{687}{990}\n$$\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nn2 <- length(cx)\nrho_shortcut <- 1 - (6 * sum(d2)) / (n2 * (n2^2 - 1))\nrho_shortcut\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> [1] 0.3060606\n```\n\n\n:::\n:::\n\n\nThis gives $r_s \\approx 0.306$. **However**, because `sbp` contains tied values, this shortcut formula is only approximate.\n\n## Step 3: Exact value: Pearson's formula applied to the ranks\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nrho_exact <- cor(rx, ry, method = \"pearson\")\nrho_exact\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> [1] 0.2953972\n```\n\n\n:::\n:::\n\n\nThe tie-corrected (exact) value is $r_s = 0.295$ — close to, but not identical to, the uncorrected shortcut (0.306). **Rule of thumb: with any tied values, always use the Pearson-on-ranks method (or software) rather than the raw** $d^2$ shortcut.\n\n## Step 4: Verify against R's built-in function\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncor.test(cx, cy, method = \"spearman\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> \n#> \tSpearman's rank correlation rho\n#> \n#> data:  cx and cy\n#> S = 116.26, p-value = 0.4073\n#> alternative hypothesis: true rho is not equal to 0\n#> sample estimates:\n#>       rho \n#> 0.2953972\n```\n\n\n:::\n:::\n\n\nR's `cor.test()` reports $r_s = 0.295$, matching our tie-corrected hand calculation exactly (R issues a warning that an *exact* $p$-value cannot be computed because of ties, and instead reports an asymptotic $t$-approximation $p$-value). With $n=10$ and $r_s=0.295$, $p = 0.41$ — no statistically significant monotonic association is detected in this small subsample.\n\n------------------------------------------------------------------------\n\n# Demonstration in R Using the Full WCGS Data Set\n\n## About the data\n\nThe **Western Collaborative Group Study (WCGS)** was a prospective cohort study of coronary heart disease (CHD) among middle-aged American men. The extract used here (`wcgs.xls`) contains **3154** subjects and the following key numeric variables:\n\n\n::: {#tbl-dictionary .cell layout-align=\"center\" tbl-cap='Selected WCGS variables used in this chapter'}\n\n```{.r .cell-code}\ndict <- data.frame(\n  Variable = c(\"age\",\"height\",\"weight\",\"bmi\",\"sbp\",\"dbp\",\"chol\",\"ncigs\",\"chd69\",\"behpat\"),\n  Description = c(\n    \"Age (years)\",\n    \"Height (inches)\",\n    \"Weight (pounds)\",\n    \"Body mass index (kg/m$^2$)\",\n    \"Systolic blood pressure (mmHg)\",\n    \"Diastolic blood pressure (mmHg)\",\n    \"Total serum cholesterol (mg/dL)\",\n    \"Cigarettes smoked per day\",\n    \"Coronary heart disease event by end of follow-up (Yes/No)\",\n    \"Behaviour pattern (A1, A2, B3, B4)\"\n  )\n)\nkable(dict)\n```\n\n::: {.cell-output-display}\n\n\n|Variable |Description                                               |\n|:--------|:---------------------------------------------------------|\n|age      |Age (years)                                               |\n|height   |Height (inches)                                           |\n|weight   |Weight (pounds)                                           |\n|bmi      |Body mass index (kg/m$^2$)                                |\n|sbp      |Systolic blood pressure (mmHg)                            |\n|dbp      |Diastolic blood pressure (mmHg)                           |\n|chol     |Total serum cholesterol (mg/dL)                           |\n|ncigs    |Cigarettes smoked per day                                 |\n|chd69    |Coronary heart disease event by end of follow-up (Yes/No) |\n|behpat   |Behaviour pattern (A1, A2, B3, B4)                        |\n\n\n:::\n:::\n\n\n## Step 1: Import the data\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(readxl)\nwcgs <- read_excel(\"wcgs.xls\")\nstr(wcgs)\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsummary(wcgs[, c(\"age\",\"height\",\"weight\",\"bmi\",\"sbp\",\"dbp\",\"chol\",\"ncigs\")])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>       age            height          weight         bmi             sbp       \n#>  Min.   :39.00   Min.   :60.00   Min.   : 78   Min.   :11.19   Min.   : 98.0  \n#>  1st Qu.:42.00   1st Qu.:68.00   1st Qu.:155   1st Qu.:22.96   1st Qu.:120.0  \n#>  Median :45.00   Median :70.00   Median :170   Median :24.39   Median :126.0  \n#>  Mean   :46.28   Mean   :69.78   Mean   :170   Mean   :24.52   Mean   :128.6  \n#>  3rd Qu.:50.00   3rd Qu.:72.00   3rd Qu.:182   3rd Qu.:25.84   3rd Qu.:136.0  \n#>  Max.   :59.00   Max.   :78.00   Max.   :320   Max.   :38.95   Max.   :230.0  \n#>                                                                               \n#>       dbp              chol           ncigs     \n#>  Min.   : 58.00   Min.   :103.0   Min.   : 0.0  \n#>  1st Qu.: 76.00   1st Qu.:197.2   1st Qu.: 0.0  \n#>  Median : 80.00   Median :223.0   Median : 0.0  \n#>  Mean   : 82.02   Mean   :226.4   Mean   :11.6  \n#>  3rd Qu.: 86.00   3rd Qu.:253.0   3rd Qu.:20.0  \n#>  Max.   :150.00   Max.   :645.0   Max.   :99.0  \n#>                   NA's   :12\n```\n\n\n:::\n:::\n\n\n## Step 2: Visualise the relationships first\n\n\n::: {#fig-scatter-two .cell layout-ncol=\"2\" layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(wcgs, aes(height, weight)) +\n  geom_point(alpha = 0.25, colour = \"steelblue\") +\n  geom_smooth(method = \"lm\", se = FALSE, colour = \"firebrick\") +\n  labs(x = \"Height (in)\", y = \"Weight (lb)\") +\n  theme_minimal()\n\nggplot(wcgs, aes(chol, sbp)) +\n  geom_point(alpha = 0.25, colour = \"darkorange3\") +\n  geom_smooth(method = \"lm\", se = FALSE, colour = \"firebrick\") +\n  labs(x = \"Cholesterol (mg/dL)\", y = \"SBP (mmHg)\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![Height vs. weight](12_1_Correlation_files/figure-html/fig-scatter-two-1.png){#fig-scatter-two-1 fig-align='center' width=85%}\n:::\n\n::: {.cell-output-display}\n![Cholesterol vs. SBP](12_1_Correlation_files/figure-html/fig-scatter-two-2.png){#fig-scatter-two-2 fig-align='center' width=85%}\n:::\n\nTwo candidate relationships: (left) height vs. weight — roughly linear; (right) cholesterol vs. systolic BP — noisier, right-skewed variables.\n:::\n\n\n## Step 3: Check the normality assumption (needed for Pearson inference)\n\n\n::: {#fig-qq .cell layout-ncol=\"2\" layout-align=\"center\"}\n\n```{.r .cell-code}\nqqnorm(wcgs$height, main = \"Height\"); qqline(wcgs$height, col = \"red\")\nqqnorm(wcgs$weight, main = \"Weight\"); qqline(wcgs$weight, col = \"red\")\nqqnorm(wcgs$chol,   main = \"Cholesterol\"); qqline(wcgs$chol, col = \"red\")\nqqnorm(wcgs$sbp,    main = \"SBP\"); qqline(wcgs$sbp, col = \"red\")\n```\n\n::: {.cell-output-display}\n![Height](12_1_Correlation_files/figure-html/fig-qq-1.png){#fig-qq-1 fig-align='center' width=85%}\n:::\n\n::: {.cell-output-display}\n![Weight](12_1_Correlation_files/figure-html/fig-qq-2.png){#fig-qq-2 fig-align='center' width=85%}\n:::\n\n::: {.cell-output-display}\n![Cholesterol](12_1_Correlation_files/figure-html/fig-qq-3.png){#fig-qq-3 fig-align='center' width=85%}\n:::\n\n::: {.cell-output-display}\n![SBP](12_1_Correlation_files/figure-html/fig-qq-4.png){#fig-qq-4 fig-align='center' width=85%}\n:::\n\nNormal Q-Q plots: height and weight are close to normal; cholesterol and SBP are right-skewed.\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nshapiro.test(wcgs$height)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> \n#> \tShapiro-Wilk normality test\n#> \n#> data:  wcgs$height\n#> W = 0.98357, p-value < 2.2e-16\n```\n\n\n:::\n\n```{.r .cell-code}\nshapiro.test(wcgs$chol)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> \n#> \tShapiro-Wilk normality test\n#> \n#> data:  wcgs$chol\n#> W = 0.97856, p-value < 2.2e-16\n```\n\n\n:::\n:::\n\n\nWith $n = 3{,}154$, the Shapiro-Wilk test is extremely sensitive to trivial departures from normality (essentially all large samples reject $H_0$); the Q-Q plots are the more useful diagnostic here. Height is close to normal; cholesterol and SBP show the right skew typical of biological \"positive-only\" measurements, which is a caution for Pearson inference — and part of why we illustrate Spearman with this pair.\n\n## Step 4: Pearson correlation\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncor.test(wcgs$height, wcgs$weight, method = \"pearson\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> \n#> \tPearson's product-moment correlation\n#> \n#> data:  wcgs$height and wcgs$weight\n#> t = 35.36, df = 3152, p-value < 2.2e-16\n#> alternative hypothesis: true correlation is not equal to 0\n#> 95 percent confidence interval:\n#>  0.5074729 0.5574681\n#> sample estimates:\n#>       cor \n#> 0.5329355\n```\n\n\n:::\n:::\n\n\n**Interpretation:** $r = 0.533$ ($95\\%$ CI: $0.507$ to $0.557$), $t(3152) = 35.4$, $p < 0.001$. There is a **moderate, highly statistically significant, positive linear association** between height and weight: taller men tend to weigh more. $r^2 = 0.284$, i.e., height linearly \"explains\" about $28\\%$ of the variability in weight.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncor.test(wcgs$chol, wcgs$sbp, method = \"pearson\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> \n#> \tPearson's product-moment correlation\n#> \n#> data:  wcgs$chol and wcgs$sbp\n#> t = 6.9486, df = 3140, p-value = 4.466e-12\n#> alternative hypothesis: true correlation is not equal to 0\n#> 95 percent confidence interval:\n#>  0.08847366 0.15735253\n#> sample estimates:\n#>       cor \n#> 0.1230613\n```\n\n\n:::\n:::\n\n\nPearson's $r = 0.123$ for cholesterol vs. SBP — a weak association — but recall both variables are right-skewed, so this Pearson estimate may be distorted by a handful of high values.\n\n## Step 5: Spearman correlation\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncor.test(wcgs$chol, wcgs$sbp, method = \"spearman\", exact = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> \n#> \tSpearman's rank correlation rho\n#> \n#> data:  wcgs$chol and wcgs$sbp\n#> S = 4457547658, p-value = 8.779e-15\n#> alternative hypothesis: true rho is not equal to 0\n#> sample estimates:\n#>       rho \n#> 0.1377588\n```\n\n\n:::\n:::\n\n\n**Interpretation:** $r_s = 0.138$, $p < 0.001$. Because $n$ is large, even this weak monotonic association is statistically significant — a reminder that with large samples, statistical significance and practical/clinical importance are not the same thing. Note `exact = FALSE` is required here because `chol` contains tied values and is large, so R falls back on the asymptotic $t$-approximation for the $p$-value.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncor.test(wcgs$height, wcgs$weight, method = \"spearman\", exact = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> \n#> \tSpearman's rank correlation rho\n#> \n#> data:  wcgs$height and wcgs$weight\n#> S = 2409320566, p-value < 2.2e-16\n#> alternative hypothesis: true rho is not equal to 0\n#> sample estimates:\n#>       rho \n#> 0.5392548\n```\n\n\n:::\n:::\n\n\nFor height and weight, Pearson ($r=0.533$) and Spearman ($r_s=0.529$) agree closely — expected, since this relationship is close to linear and both variables are reasonably symmetric.\n\n## Step 6: A correlation matrix and correlation plot\n\nIt is often useful to examine several numeric variables at once.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nvars <- c(\"age\",\"height\",\"weight\",\"bmi\",\"sbp\",\"dbp\",\"chol\",\"ncigs\")\nM <- cor(wcgs[, vars], use = \"pairwise.complete.obs\", method = \"pearson\")\nround(M, 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>          age height weight   bmi  sbp   dbp  chol ncigs\n#> age     1.00  -0.10  -0.03  0.03 0.17  0.14  0.09 -0.01\n#> height -0.10   1.00   0.53 -0.07 0.02  0.01 -0.09  0.01\n#> weight -0.03   0.53   1.00  0.81 0.25  0.30  0.01 -0.08\n#> bmi     0.03  -0.07   0.81  1.00 0.29  0.34  0.07 -0.11\n#> sbp     0.17   0.02   0.25  0.29 1.00  0.77  0.12  0.03\n#> dbp     0.14   0.01   0.30  0.34 0.77  1.00  0.13 -0.06\n#> chol    0.09  -0.09   0.01  0.07 0.12  0.13  1.00  0.10\n#> ncigs  -0.01   0.01  -0.08 -0.11 0.03 -0.06  0.10  1.00\n```\n\n\n:::\n\n```{.r .cell-code}\ncorrplot(M, method = \"circle\", type = \"upper\", addCoef.col = \"black\",\n         number.cex = 0.7, tl.col = \"black\", tl.srt = 45,\n         title = \"Pearson correlations, WCGS numeric variables\",\n         mar = c(0,0,2,0))\n```\n\n::: {.cell-output-display}\n![Pearson correlation matrix of key WCGS numeric variables.](12_1_Correlation_files/figure-html/fig-corrmat-1.png){#fig-corrmat fig-align='center' width=85%}\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npsych::pairs.panels(wcgs[, c(\"age\",\"height\",\"weight\",\"sbp\",\"chol\")],\n                     method = \"pearson\", hist.col = \"lightblue\",\n                     density = TRUE, ellipses = FALSE)\n```\n\n::: {.cell-output-display}\n![Pairwise scatterplots, distributions, and Pearson correlations for a subset of WCGS variables.](12_1_Correlation_files/figure-html/fig-pairspanel-1.png){#fig-pairspanel fig-align='center' width=85%}\n:::\n:::\n\n\n## Step 7: Summary table, Pearson and Spearman side by side\n\n\n::: {#tbl-summary-both .cell layout-align=\"center\"}\n\n```{.r .cell-code}\npairs_list <- list(c(\"height\",\"weight\"), c(\"age\",\"sbp\"), c(\"chol\",\"sbp\"), c(\"bmi\",\"sbp\"))\n\nresults <- do.call(rbind, lapply(pairs_list, function(p) {\n  x <- wcgs[[p[1]]]; y <- wcgs[[p[2]]]\n  ok <- complete.cases(x, y)\n  pear <- cor.test(x[ok], y[ok], method = \"pearson\")\n  spea <- cor.test(x[ok], y[ok], method = \"spearman\", exact = FALSE)\n  data.frame(Variable_1 = p[1], Variable_2 = p[2], n = sum(ok),\n             Pearson_r = round(unname(pear$estimate), 3),\n             Pearson_p = signif(pear$p.value, 3),\n             Spearman_rs = round(unname(spea$estimate), 3),\n             Spearman_p = signif(spea$p.value, 3))\n}))\nkable(results)\n```\n\n::: {.cell-output-display}\n\n\n|Variable_1 |Variable_2 |    n| Pearson_r| Pearson_p| Spearman_rs| Spearman_p|\n|:----------|:----------|----:|---------:|---------:|-----------:|----------:|\n|height     |weight     | 3154|     0.533|         0|       0.539|          0|\n|age        |sbp        | 3154|     0.166|         0|       0.159|          0|\n|chol       |sbp        | 3142|     0.123|         0|       0.138|          0|\n|bmi        |sbp        | 3154|     0.288|         0|       0.293|          0|\n\n\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n# Pearson vs. Spearman: A Side-by-Side Comparison\n\n| Feature | Pearson $r$ | Spearman $r_s$ |\n|----|----|----|\n| Data type required | Numeric (interval/ratio) | Ordinal or numeric |\n| Detects | Linear association | Any monotonic association |\n| Uses | Actual values | Ranks of the values |\n| Sensitive to outliers? | Yes, strongly | No, largely robust |\n| Requires (approx.) normality for inference? | Yes | No |\n| Computation | Covariance / product of SDs | Pearson formula applied to ranks |\n| Typical use case | Height vs. weight, dose vs. response (linear) | Skewed labs (e.g., triglycerides), ordinal scores, monotone-but-curved relationships |\n\n------------------------------------------------------------------------\n\n# Common Pitfalls in Interpreting Correlation\n\n-   **Correlation is not causation.** A significant $r$ or $r_s$ establishes association, not that one variable causes changes in the other; confounding, reverse causation, and chance are all still possible explanations.\n-   **Non-linearity.** Pearson's $r$ can be close to zero even when $X$ and $Y$ are strongly related, if the relationship is curved (e.g., U-shaped) — always plot the data first.\n-   **Outliers and leverage points.** A single extreme observation can inflate or deflate Pearson's $r$ substantially; Spearman is more robust in this situation.\n-   **Restriction of range.** Correlation estimated within a narrow range of $X$ (e.g., only healthy adults) will understate the true association in the full population.\n-   **Ecological correlation.** Correlating group-level averages (e.g., country-level means) can produce misleadingly strong correlations that do not hold at the individual level (ecological fallacy).\n-   **Statistical vs. clinical significance.** With very large $n$ (as in WCGS, $n>3{,}000$), even trivially small correlations become \"statistically significant.\" Always report and interpret the magnitude of $r$/$r_s$, not just the $p$-value.\n-   **Multiple testing.** Scanning many pairwise correlations (e.g., a full correlation matrix) inflates the chance of false positives; interpret exploratory matrices cautiously and confirm key findings with pre-specified hypotheses.\n\n------------------------------------------------------------------------\n\n# Summary\n\n-   The **scatter diagram** is the starting point for any correlation analysis.\n-   **Pearson's** $r$ quantifies the strength and direction of a **linear** relationship between two numeric variables; it assumes approximate bivariate normality and is sensitive to outliers.\n-   **Spearman's** $r_s$ quantifies the strength and direction of a **monotonic** relationship using ranks; it requires only ordinal data, handles skew and outliers gracefully, and reduces to a simple $d^2$ shortcut formula when there are no tied ranks (with a small correction needed when ties are present).\n-   Both coefficients range from $-1$ to $+1$, are tested against $H_0: \\rho = 0$ using a $t$-based statistic, and should always be reported together with sample size, a confidence interval where possible, and — most importantly — a plot of the raw data.\n-   In the WCGS data, height and weight show a moderate, near-linear positive association ($r \\approx r_s \\approx 0.53$), while cholesterol and systolic blood pressure show only a weak monotonic association ($r=0.12$, $r_s=0.14$) despite reaching statistical significance because of the large sample size.\n\n------------------------------------------------------------------------\n\n# References {.unnumbered}\n\n-   Rosner B. *Fundamentals of Biostatistics*. 8th ed. Cengage Learning.\n-   Daniel WW, Cross CL. *Biostatistics: A Foundation for Analysis in the Health Sciences*. 11th ed. Wiley.\n-   Bland M. *An Introduction to Medical Statistics*. 4th ed. Oxford University Press.\n-   Woodward M. *Epidemiology: Study Design and Data Analysis*. 3rd ed. Chapman & Hall/CRC.\n-   Cohen J. *Statistical Power Analysis for the Behavioral Sciences*. 2nd ed. Lawrence Erlbaum Associates, 1988.\n-   Rosenman RH, et al. \"A predictive study of coronary heart disease: the Western Collaborative Group Study.\" *JAMA*. 1964;189:15–22. (Original WCGS study.)\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}