{
  "hash": "7b10768de4c0090de8375773aee7aa2a",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Comparing Two Independent Group Means\"\noutput:\n  pdf_document:\n    number_sections: yes\n  html_document: default\neditor_options:\n  chunk_output_type: console\n---\n\n\n\n\n\n# Learning Objectives {.unnumbered}\n\nBy the end of this chapter, you should be able to:\n\n1.  State the situation in which the means of **two independent groups** are compared, and translate a research question into $H_0$/$H_1$.\n2.  State the assumptions, formula, and correct interpretation of **Student's (pooled-variance) two-sample** $t$-test.\n3.  State when **Welch's** $t$-test should be used instead, and explain how it differs from Student's test.\n4.  Calculate both test statistics **by hand** from raw data, including the pooled variance and Welch-Satterthwaite degrees of freedom.\n5.  State the assumptions, formula, and correct interpretation of the **Mann-Whitney U test** (Wilcoxon rank-sum test), the nonparametric alternative.\n6.  Calculate the Mann-Whitney $U$ statistic **by hand**, including handling of tied ranks.\n7.  Reproduce all three procedures in **R**, using the WCGS data, and correctly choose among them based on formal checks of normality and variance homogeneity.\n\n------------------------------------------------------------------------\n\n# Comparing Two Independent Groups\n\nA very common design in health research compares a numeric outcome between **two separate, non-overlapping groups** of subjects — for example, smokers vs. non-smokers, treatment vs. control, or (as in this chapter) Type A vs. Type B behaviour pattern. The word \"independent\" here means the two samples consist of **different individuals** with no natural pairing between them (contrast this with the *paired* designs covered in a later chapter).\n\nWe will use two grouping variables already present in the WCGS data:\n\n-   **`dibpat`** — behaviour pattern, dichotomised as **Type A** ($n=1{,}589$) vs. **Type B** ($n=1{,}565$) — nearly equal group sizes, a good case to illustrate Student's test.\n-   **`chd69`** — whether the subject had a coronary heart disease event by the end of follow-up, **No** ($n=2{,}897$) vs. **Yes** ($n=257$) — very unequal group sizes together with unequal variances and skew, a good case to illustrate Welch's test and the Mann-Whitney U test.\n\n\n::: {#fig-box-intro .cell layout-ncol=\"2\" layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(wcgs, aes(x = dibpat, y = weight, fill = dibpat)) +\n  geom_boxplot(alpha = 0.7, show.legend = FALSE) +\n  labs(x = \"Behaviour pattern\", y = \"Weight (lb)\") +\n  theme_minimal(base_size = 12)\n\nggplot(wcgs, aes(x = chd69, y = chol, fill = chd69)) +\n  geom_boxplot(alpha = 0.7, show.legend = FALSE) +\n  labs(x = \"CHD event by 1969\", y = \"Cholesterol (mg/dL)\") +\n  theme_minimal(base_size = 12)\n```\n\n::: {.cell-output-display}\n![Weight by behaviour pattern (dibpat)](12_3_bivariate_files/figure-html/fig-box-intro-1.png){#fig-box-intro-1 fig-align='center' width=85%}\n:::\n\n::: {.cell-output-display}\n![Cholesterol by CHD event status (chd69)](12_3_bivariate_files/figure-html/fig-box-intro-2.png){#fig-box-intro-2 fig-align='center' width=85%}\n:::\n\nTwo independent-groups comparisons used throughout this chapter.\n:::\n\n\nThree procedures are commonly used:\n\n| Test | Assumes equal variances? | Assumes (approx.) normality? | Uses |\n|------------------|------------------|------------------|------------------|\n| **Student's (pooled)** $t$-test | Yes | Yes, in each group | Raw values |\n| **Welch's** $t$-test | No | Yes, in each group | Raw values |\n| **Mann-Whitney U** (Wilcoxon rank-sum) | No | No | Ranks of the pooled values |\n\n------------------------------------------------------------------------\n\n# Student's Two-Sample $t$-Test (Equal Variances) {#sec-ind_t_test}\n\n## Hypotheses\n\n$$\nH_0: \\mu_1=\\mu_2 \\qquad H_1: \\mu_1\\ne\\mu_2\n$$\n\n## Assumptions\n\n1.  The outcome is **continuous numeric**.\n2.  The two samples are **independent** of each other, and observations **within** each sample are independent (a random sample from each population).\n3.  Each population is (approximately) **normally distributed**, or each $n$ is large enough for the Central Limit Theorem to apply.\n4.  The two populations have **equal variances** ($\\sigma_1^2=\\sigma_2^2$) — often checked with an $F$-test (`var.test()`) or, preferably with non-normal data, **Levene's test**.\n\n## Test statistic\n\nThe two sample variances are combined into a single **pooled variance** estimate:\n\n$$\ns_p^2=\\frac{(n_1-1)s_1^2+(n_2-1)s_2^2}{n_1+n_2-2}\n$$ {#eq-pooledvar}\n\n$$\nt=\\frac{\\bar x_1-\\bar x_2}{\\sqrt{s_p^2\\left(\\dfrac1{n_1}+\\dfrac1{n_2}\\right)}}\n\\qquad \\sim\\; t_{(n_1+n_2-2)} \\text{ under } H_0\n$$ {#eq-studentt}\n\n## Confidence interval for $\\mu_1-\\mu_2$\n\n$$\n(\\bar x_1-\\bar x_2)\\pm t_{(1-\\alpha/2,\\;n_1+n_2-2)}\\sqrt{s_p^2\\left(\\frac1{n_1}+\\frac1{n_2}\\right)}\n$$\n\n------------------------------------------------------------------------\n\n# Manual (Hand) Calculation of Student's $t$-Test\n\nWe draw reproducible random subsamples of $n=8$ men from each behaviour-pattern group and compare **weight** (lb).\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n\nTable: Type A subsample (n = 8)\n\n|    id| weight|\n|-----:|------:|\n| 11038|    160|\n| 11355|    165|\n|  3068|    167|\n| 12711|    165|\n| 12264|    170|\n| 12591|    160|\n| 11058|    177|\n|  3465|    170|\n\n\n:::\n\n::: {.cell-output-display}\n\n\nTable: Type B subsample (n = 8)\n\n|    id| weight|\n|-----:|------:|\n| 10166|    185|\n|  3572|    203|\n| 21339|    160|\n| 13051|    230|\n| 21039|    185|\n| 13482|    175|\n|  3202|    179|\n| 13382|    150|\n\n\n:::\n:::\n\n\n## Step 1: Compute each group's mean and variance\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stdout}\n\n```\n#>    Group n    Mean  Variance        SD\n#> 1 Type A 8 166.750  31.92857  5.650537\n#> 2 Type B 8 183.375 616.26786 24.824743\n```\n\n\n:::\n:::\n\n\n## Step 2: Pool the variances\n\n$$\ns_p^2=\\frac{(8-1)(31.93)+(8-1)(616.27)}{8+8-2}=\\frac{7(31.93)+7(616.27)}{14}\n$$\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsp2 <- ((n1 - 1) * v1 + (n2 - 1) * v2) / (n1 + n2 - 2)\nsp2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> [1] 324.1\n```\n\n\n:::\n:::\n\n\n## Step 3: Compute the test statistic\n\n$$\nt=\\frac{\\bar x_1-\\bar x_2}{\\sqrt{s_p^2(1/n_1+1/n_2)}}=\\frac{166.75-183.375}{\\sqrt{324.10\\times(1/8+1/8)}}\n$$\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stdout}\n\n```\n#>         SE         t df    p_value\n#> 1 9.001364 -1.846942 14 0.08599752\n```\n\n\n:::\n:::\n\n\n## Step 4: Verify against R\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nt.test(x1, x2, var.equal = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> \n#> \tTwo Sample t-test\n#> \n#> data:  x1 and x2\n#> t = -1.8, df = 14, p-value = 0.09\n#> alternative hypothesis: true difference in means is not equal to 0\n#> 95 percent confidence interval:\n#>  -35.931   2.681\n#> sample estimates:\n#> mean of x mean of y \n#>     166.8     183.4\n```\n\n\n:::\n:::\n\n\nThe hand-calculated $t=-1.847$, $df=14$, $p=0.086$ match R's `t.test(..., var.equal = TRUE)` exactly. At the $5\\%$ level we do **not** reject $H_0$ in this small subsample.\n\n::: callout-note\nLook closely at the two group variances above: $31.9$ vs. $616.3$ — a nearly $20$-fold difference, purely a feature of this small, randomly drawn $n=8$ subsample (the *full-population* variance ratio, shown later, is actually close to $1$). This is exactly why we should never eyeball a handful of numbers and assume equal variances — a formal test, on adequate sample sizes, is needed.\n:::\n\n------------------------------------------------------------------------\n\n# Welch's $t$-Test (Unequal Variances)\n\n## When to use it\n\nUse Welch's test instead of Student's when the assumption of equal population variances is doubtful — either because a formal test (an $F$-test or, more robustly, Levene's test) rejects equal variances, or as a **safe default**: many statisticians now recommend using Welch's test routinely, since it performs almost identically to Student's test when variances *are* equal, but avoids the inflated Type I error that Student's test can produce when variances differ, especially with **unequal sample sizes**.\n\n## Test statistic\n\nWelch's test does not pool the variances; each group contributes its own variance to the standard error:\n\n$$\nt=\\frac{\\bar x_1-\\bar x_2}{\\sqrt{\\dfrac{s_1^2}{n_1}+\\dfrac{s_2^2}{n_2}}}\n$$ {#eq-welcht}\n\nThe degrees of freedom are **not** simply $n_1+n_2-2$; instead the **Welch-Satterthwaite approximation** is used, which can take non-integer values:\n\n$$\ndf_{Welch}=\\frac{\\left(\\dfrac{s_1^2}{n_1}+\\dfrac{s_2^2}{n_2}\\right)^2}\n{\\dfrac{(s_1^2/n_1)^2}{n_1-1}+\\dfrac{(s_2^2/n_2)^2}{n_2-1}}\n$$ {#eq-welchdf}\n\n------------------------------------------------------------------------\n\n# Manual (Hand) Calculation of Welch's $t$-Test {#sec-welch_t}\n\nUsing the **same** two subsamples as above.\n\n## Step 1: Compute the (unpooled) standard error\n\n$$\nSE=\\sqrt{\\frac{31.93}{8}+\\frac{616.27}{8}}\n$$\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stdout}\n\n```\n#> [1] 9.001364\n```\n\n\n:::\n:::\n\n\n**Notice** that because $n_1=n_2=8$ here, $SE_{Welch}=\\sqrt{(s_1^2+s_2^2)/n}$ is numerically **identical** to $SE_{pooled}=\\sqrt{s_p^2 \\times 2/n}$ from the Student's test above — this is a general fact whenever the two sample sizes are equal. What differs between the two tests, in this equal-$n$ case, is entirely the **degrees of freedom**.\n\n## Step 2: Welch-Satterthwaite degrees of freedom\n\n$$\ndf_{Welch}=\\frac{(31.93/8+616.27/8)^2}{\\dfrac{(31.93/8)^2}{7}+\\dfrac{(616.27/8)^2}{7}}\n$$\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stdout}\n\n```\n#> [1] 7.723392\n```\n\n\n:::\n:::\n\n\nBecause Group B's variance so dominates Group A's in this subsample, $df_{Welch}=7.72$ — pulled down close to $n_2-1=7$ (Welch's df is always between $\\min(n_1,n_2)-1$ and $n_1+n_2-2$; the more unequal the variances, the closer it moves to the smaller group's own df).\n\n## Step 3: Test statistic and $p$-value\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stdout}\n\n```\n#>           t       df   p_value\n#> 1 -1.846942 7.723392 0.1032826\n```\n\n\n:::\n:::\n\n\n## Step 4: Verify against R\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nt.test(x1, x2, var.equal = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> \n#> \tWelch Two Sample t-test\n#> \n#> data:  x1 and x2\n#> t = -1.8, df = 7.7, p-value = 0.1\n#> alternative hypothesis: true difference in means is not equal to 0\n#> 95 percent confidence interval:\n#>  -37.512   4.262\n#> sample estimates:\n#> mean of x mean of y \n#>     166.8     183.4\n```\n\n\n:::\n:::\n\n\nThe hand-calculated values match R's default `t.test()` (Welch's is R's default for two-sample tests) exactly: $t=-1.847$ (identical to Student's, as expected with equal $n$), but $df=7.72$ (much smaller than Student's $14$), giving a **wider, more conservative** $p$-value ($0.103$ vs. $0.086$) and a **wider** confidence interval. This illustrates precisely why Welch's test matters even when the two $t$-statistics coincide: unequal variances erode the effective degrees of freedom, and ignoring that (as Student's test does) can overstate precision.\n\n## Choosing between them: check variance homogeneity formally\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nvar.test(weight ~ dibpat, data = wcgs)          # F-test (sensitive to non-normality)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> \n#> \tF test to compare two variances\n#> \n#> data:  weight by dibpat\n#> F = 1.1, num df = 1588, denom df = 1564, p-value = 0.3\n#> alternative hypothesis: true ratio of variances is not equal to 1\n#> 95 percent confidence interval:\n#>  0.9527 1.1608\n#> sample estimates:\n#> ratio of variances \n#>              1.052\n```\n\n\n:::\n\n```{.r .cell-code}\nleveneTest(weight ~ dibpat, data = wcgs)         # Levene's test (robust to non-normality)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> Levene's Test for Homogeneity of Variance (center = median)\n#>         Df F value Pr(>F)\n#> group    1    0.36   0.55\n#>       3152\n```\n\n\n:::\n:::\n\n\nOn the **full** cohort, both the $F$-test ($p=0.32$) and Levene's test ($p=0.55$) agree the weight variances in Type A and Type B do **not** differ significantly — confirming that our small subsample's apparent $20$-fold variance difference above was simply sampling noise, and that Student's and Welch's tests should (and, as we will see, do) give essentially the same answer on the full data.\n\n------------------------------------------------------------------------\n\n# Mann-Whitney U Test (Wilcoxon Rank-Sum Test) {#sec-manwhitney_u}\n\n## When to use it\n\nUse the Mann-Whitney U test (equivalently, the Wilcoxon rank-sum test — the same procedure under two names) instead of a $t$-test when:\n\n-   The outcome is **ordinal**, or numeric but **clearly non-normal / skewed** in one or both groups.\n-   There are **influential outliers**.\n-   Sample sizes are **small and unequal**, compounding concerns about non-normality.\n\nIt tests whether observations from one group tend to be **systematically larger** than observations from the other (a shift in location/distribution), without assuming a particular distributional shape.\n\n$$\nH_0: \\text{the two populations have the same distribution (no location shift)}\n$$\n\n## Procedure\n\n1.  Combine the two samples and **rank all** $n_1+n_2$ values together from smallest (rank 1) to largest, giving tied values the average of the ranks they span.\n2.  Sum the ranks in each group: $R_1$ (group 1) and $R_2$ (group 2); note $R_1+R_2=\\dfrac{(n_1+n_2)(n_1+n_2+1)}{2}$.\n3.  Convert each rank sum to a $U$ statistic: $$\n    U_1=R_1-\\frac{n_1(n_1+1)}{2}, \\qquad U_2=R_2-\\frac{n_2(n_2+1)}{2}\n    $$ {#eq-mwu} and note $U_1+U_2=n_1n_2$ always.\n4.  The test statistic is conventionally $U=\\min(U_1,U_2)$ (R's `wilcox.test()` reports $W$, which equals $U$ for the first-listed group).\n5.  For small samples, compare $U$ to exact tables; for larger samples, use the normal approximation: $$\n    z=\\frac{U-\\mu_U}{\\sigma_U}, \\qquad \\mu_U=\\frac{n_1n_2}{2}, \\qquad \\sigma_U=\\sqrt{\\frac{n_1n_2(n_1+n_2+1)}{12}}\n    $$ {#eq-mwuz} (software also applies a tie correction to $\\sigma_U$ and often a continuity correction).\n\n------------------------------------------------------------------------\n\n# Manual (Hand) Calculation of the Mann-Whitney U Test\n\nWe draw reproducible random subsamples of $n=8$ men from each CHD-event group (restricted to those with complete cholesterol) and compare **total cholesterol** — a variable we already know is right-skewed, with the CHD-event group additionally containing a genuine extreme outlier ($645$ mg/dL, the maximum value in the entire cohort), making this a strong case for a rank-based test.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n\nTable: CHD = Yes subsample (n = 8)\n\n|    id| chol|\n|-----:|----:|\n| 10276|  240|\n| 13129|  226|\n|  2020|  220|\n| 13409|  220|\n| 12237|  645|\n|  3499|  300|\n| 10307|  228|\n|  2084|  208|\n\n\n:::\n\n::: {.cell-output-display}\n\n\nTable: CHD = No subsample (n = 8)\n\n|    id| chol|\n|-----:|----:|\n| 11320|  225|\n| 12908|  198|\n|  6090|  265|\n| 10077|  224|\n|  3207|  189|\n| 11210|  188|\n|  6079|  223|\n| 19068|  258|\n\n\n:::\n:::\n\n\n## Step 1: Pool, rank, and tabulate\n\nNote the value $220$ occurs twice (both in the \"Yes\" group), so both receive the average rank $(5+6)/2=5.5$.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n\nTable: Combined, ranked cholesterol values\n\n| chol|group | rank|\n|----:|:-----|----:|\n|  188|No    |  1.0|\n|  189|No    |  2.0|\n|  198|No    |  3.0|\n|  208|Yes   |  4.0|\n|  220|Yes   |  5.5|\n|  220|Yes   |  5.5|\n|  223|No    |  7.0|\n|  224|No    |  8.0|\n|  225|No    |  9.0|\n|  226|Yes   | 10.0|\n|  228|Yes   | 11.0|\n|  240|Yes   | 12.0|\n|  258|No    | 13.0|\n|  265|No    | 14.0|\n|  300|Yes   | 15.0|\n|  645|Yes   | 16.0|\n\n\n:::\n:::\n\n\n## Step 2: Sum the ranks in each group\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stdout}\n\n```\n#>   Group Rank_sum Total Expected\n#> 1   Yes       79   136      136\n#> 2    No       57   136      136\n```\n\n\n:::\n:::\n\n\n## Step 3: Convert to $U$\n\n$$\nU_1=R_1-\\frac{n_1(n_1+1)}{2}=79-36=43, \\qquad U_2=R_2-\\frac{n_2(n_2+1)}{2}=57-36=21\n$$\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stdout}\n\n```\n#>   U1 U2 U1+U2 n1*n2 U_test_statistic\n#> 1 43 21    64    64               21\n```\n\n\n:::\n:::\n\n\n## Step 4: Normal approximation\n\n$$\n\\mu_U=\\frac{8\\times8}{2}=32, \\qquad \\sigma_U=\\sqrt{\\frac{8\\times8\\times17}{12}}=9.522\n$$\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stdout}\n\n```\n#>   mu_U  sigma_U         z   p_value\n#> 1   32 9.521905 -1.155231 0.2479958\n```\n\n\n:::\n:::\n\n\n## Step 5: Verify against R\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nwilcox.test(g1, g2)                       # default: continuity-corrected\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> \n#> \tWilcoxon rank sum test with continuity correction\n#> \n#> data:  g1 and g2\n#> W = 43, p-value = 0.3\n#> alternative hypothesis: true location shift is not equal to 0\n```\n\n\n:::\n\n```{.r .cell-code}\nwilcox.test(g1, g2, correct = FALSE)      # matches the hand normal-approximation\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> \n#> \tWilcoxon rank sum test\n#> \n#> data:  g1 and g2\n#> W = 43, p-value = 0.2\n#> alternative hypothesis: true location shift is not equal to 0\n```\n\n\n:::\n:::\n\n\nR's $W=43$ is exactly our $U_1$ (the \"Yes\" group is the first argument). Without the continuity correction, $p=0.248$ matches our hand calculation; with it (R's default), $p=0.270$. Neither reaches significance in this small subsample — but note the extreme value ($645$) did **not** distort the result, because the Mann-Whitney test uses only its rank (the largest), unlike a $t$-test where it would inflate the group variance and mean substantially.\n\n------------------------------------------------------------------------\n\n# Demonstration in R Using the Full WCGS Data Set\n\n## Comparison 1: Weight by behaviour pattern (`dibpat`) — the \"equal-variance\" case\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(wcgs, aes(x = weight, fill = dibpat)) +\n  geom_histogram(binwidth = 5, alpha = 0.6, position = \"identity\", colour = \"white\") +\n  labs(x = \"Weight (lb)\", y = \"Count\", fill = \"Behaviour pattern\") +\n  theme_minimal(base_size = 12)\n```\n\n::: {.cell-output-display}\n![Weight distributions by behaviour pattern — both reasonably symmetric.](12_3_bivariate_files/figure-html/fig-weight-normcheck-1.png){#fig-weight-normcheck fig-align='center' width=85%}\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nt.test(weight ~ dibpat, data = wcgs, var.equal = TRUE)   # Student's\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> \n#> \tTwo Sample t-test\n#> \n#> data:  weight by dibpat\n#> t = 2.4, df = 3152, p-value = 0.02\n#> alternative hypothesis: true difference in means between group Type A and group Type B is not equal to 0\n#> 95 percent confidence interval:\n#>  0.3247 3.2686\n#> sample estimates:\n#> mean in group Type A mean in group Type B \n#>                170.8                169.0\n```\n\n\n:::\n\n```{.r .cell-code}\nt.test(weight ~ dibpat, data = wcgs, var.equal = FALSE)  # Welch's\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> \n#> \tWelch Two Sample t-test\n#> \n#> data:  weight by dibpat\n#> t = 2.4, df = 3152, p-value = 0.02\n#> alternative hypothesis: true difference in means between group Type A and group Type B is not equal to 0\n#> 95 percent confidence interval:\n#>  0.3249 3.2683\n#> sample estimates:\n#> mean in group Type A mean in group Type B \n#>                170.8                169.0\n```\n\n\n:::\n:::\n\n\n**Interpretation:** Student's and Welch's tests give virtually identical results ($t=2.39$, $df=3152$ vs. $df=3151.7$, both $p\\approx0.017$), exactly as expected given the near-equal variances confirmed earlier. Type A men weigh, on average, $1.80$ lb more than Type B men ($95\\%$ CI $0.32$ to $3.27$ lb) — statistically significant given the large sample, though a modest effect in absolute terms.\n\n## Comparison 2: Cholesterol by CHD event status (`chd69`) — the \"unequal-variance, skewed\" case\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(wcgs, aes(x = chd69, y = chol, fill = chd69)) +\n  geom_boxplot(alpha = 0.7, show.legend = FALSE) +\n  labs(x = \"CHD event by 1969\", y = \"Cholesterol (mg/dL)\") +\n  theme_minimal(base_size = 12)\n```\n\n::: {.cell-output-display}\n![Cholesterol by CHD event status, showing greater spread, right skew, and outliers in the CHD = Yes group.](12_3_bivariate_files/figure-html/fig-chol-box-1.png){#fig-chol-box fig-align='center' width=85%}\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nvar.test(chol ~ chd69, data = wcgs)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> \n#> \tF test to compare two variances\n#> \n#> data:  chol by chd69\n#> F = 0.73, num df = 2884, denom df = 256, p-value = 3e-04\n#> alternative hypothesis: true ratio of variances is not equal to 1\n#> 95 percent confidence interval:\n#>  0.6052 0.8694\n#> sample estimates:\n#> ratio of variances \n#>             0.7305\n```\n\n\n:::\n\n```{.r .cell-code}\nleveneTest(chol ~ chd69, data = wcgs)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> Levene's Test for Homogeneity of Variance (center = median)\n#>         Df F value Pr(>F)\n#> group    1    1.41   0.24\n#>       3140\n```\n\n\n:::\n\n```{.r .cell-code}\nshapiro.test(wcgs$chol[wcgs$chd69 == \"Yes\"])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> \n#> \tShapiro-Wilk normality test\n#> \n#> data:  wcgs$chol[wcgs$chd69 == \"Yes\"]\n#> W = 0.88, p-value = 1e-13\n```\n\n\n:::\n\n```{.r .cell-code}\nshapiro.test(wcgs$chol[wcgs$chd69 == \"No\"])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> \n#> \tShapiro-Wilk normality test\n#> \n#> data:  wcgs$chol[wcgs$chd69 == \"No\"]\n#> W = 0.99, p-value = 3e-13\n```\n\n\n:::\n:::\n\n\nHere the $F$-test suggests unequal variances ($p<0.001$), while Levene's test (more robust to the non-normality also confirmed by both Shapiro-Wilk tests) does not reach significance ($p=0.24$) — a useful reminder that the classical $F$-test for variances is itself sensitive to non-normality, and Levene's test is generally the more trustworthy diagnostic when normality is in doubt. Given the clear skew and an extreme outlier in the CHD = Yes group, this is a case for reporting **both** Welch's test and a nonparametric test.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nt.test(chol ~ chd69, data = wcgs, var.equal = TRUE)   # Student's\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> \n#> \tTwo Sample t-test\n#> \n#> data:  chol by chd69\n#> t = -9.3, df = 3140, p-value <2e-16\n#> alternative hypothesis: true difference in means between group No and group Yes is not equal to 0\n#> 95 percent confidence interval:\n#>  -31.28 -20.34\n#> sample estimates:\n#>  mean in group No mean in group Yes \n#>             224.3             250.1\n```\n\n\n:::\n\n```{.r .cell-code}\nt.test(chol ~ chd69, data = wcgs, var.equal = FALSE)  # Welch's\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> \n#> \tWelch Two Sample t-test\n#> \n#> data:  chol by chd69\n#> t = -8.1, df = 290, p-value = 1e-14\n#> alternative hypothesis: true difference in means between group No and group Yes is not equal to 0\n#> 95 percent confidence interval:\n#>  -32.07 -19.55\n#> sample estimates:\n#>  mean in group No mean in group Yes \n#>             224.3             250.1\n```\n\n\n:::\n\n```{.r .cell-code}\nwilcox.test(chol ~ chd69, data = wcgs, conf.int = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> \n#> \tWilcoxon rank sum test with continuity correction\n#> \n#> data:  chol by chd69\n#> W = 250259, p-value <2e-16\n#> alternative hypothesis: true location shift is not equal to 0\n#> 95 percent confidence interval:\n#>  -30 -19\n#> sample estimates:\n#> difference in location \n#>                    -24\n```\n\n\n:::\n:::\n\n\n**Interpretation:** All three tests agree in direction and significance, but notice how much more the degrees of freedom (and hence the standard error) shift here than in the weight example: Student's test uses $df=3140$, while Welch's drops to $df=290.3$ — because the much smaller, more variable CHD = Yes group ($n=257$) now genuinely dominates the uncertainty. Mean cholesterol is $25.8$ mg/dL higher in men who went on to have a CHD event ($95\\%$ CI, Welch: $19.6$ to $32.1$), and the Mann-Whitney/Hodges-Lehmann shift estimate is a very similar $24.0$ mg/dL — both parametric and nonparametric approaches point to the same clinically recognisable finding (higher cholesterol preceding CHD events), giving us confidence the conclusion is not an artefact of the skew.\n\n## Summary table across several variable pairs\n\n\n::: {#tbl-summary-twogroup .cell layout-align=\"center\"}\n\n```{.r .cell-code}\npairs_list <- list(\n  list(outcome = \"weight\", group = \"dibpat\"),\n  list(outcome = \"sbp\",    group = \"dibpat\"),\n  list(outcome = \"chol\",   group = \"chd69\"),\n  list(outcome = \"sbp\",    group = \"chd69\"),\n  list(outcome = \"weight\", group = \"smoke\")\n)\n\nresults <- do.call(rbind, lapply(pairs_list, function(p) {\n  f  <- as.formula(paste(p$outcome, \"~\", p$group))\n  d  <- wcgs[!is.na(wcgs[[p$outcome]]), ]\n  st <- t.test(f, data = d, var.equal = TRUE)\n  we <- t.test(f, data = d, var.equal = FALSE)\n  mw <- wilcox.test(f, data = d)\n  data.frame(Outcome = p$outcome, Group = p$group,\n             Student_t = round(unname(st$statistic), 2), Student_df = round(unname(st$parameter),1),\n             Student_p = signif(st$p.value, 3),\n             Welch_t = round(unname(we$statistic), 2), Welch_df = round(unname(we$parameter), 1),\n             Welch_p = signif(we$p.value, 3),\n             MannWhitney_W = unname(mw$statistic), MW_p = signif(mw$p.value, 3))\n}))\nkable(results)\n```\n\n::: {.cell-output-display}\n\n\n|Outcome |Group  | Student_t| Student_df| Student_p| Welch_t| Welch_df| Welch_p| MannWhitney_W|   MW_p|\n|:-------|:------|---------:|----------:|---------:|-------:|--------:|-------:|-------------:|------:|\n|weight  |dibpat |      2.39|       3152|    0.0168|    2.39|   3151.7|  0.0167|       1310445| 0.0087|\n|sbp     |dibpat |      4.31|       3152|    0.0000|    4.32|   3137.2|  0.0000|       1345807| 0.0001|\n|chol    |chd69  |     -9.25|       3140|    0.0000|   -8.12|    290.3|  0.0000|        250259| 0.0000|\n|sbp     |chd69  |     -7.54|       3152|    0.0000|   -6.54|    289.3|  0.0000|        274442| 0.0000|\n|weight  |smoke  |      6.83|       3152|    0.0000|    6.82|   3117.0|  0.0000|       1409984| 0.0000|\n\n\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n# A Practical Decision Process\n\n1.  **Plot the data** (boxplots, histograms) for each group.\n2.  **Check normality** within each group (Q-Q plots; Shapiro-Wilk for smaller $n$, interpreted cautiously for large $n$).\n3.  **Check variance homogeneity** (Levene's test is generally preferred over the $F$-test, since it is far less sensitive to non-normality).\n4.  Choose accordingly:\n\n| Normality? | Equal variances? | Recommended test |\n|----|----|----|\n| Yes | Yes | Student's (pooled-variance) $t$-test |\n| Yes | No | Welch's $t$-test |\n| No (or small, skewed, or outlier-prone) | — | Mann-Whitney U test |\n\nMany statisticians now recommend simply **defaulting to Welch's test** for two-group comparisons (it is R's default), since it costs almost nothing when variances are equal and protects against the inflated false-positive rate of Student's test when they are not.\n\n------------------------------------------------------------------------\n\n# Common Pitfalls\n\n-   **Assuming equal variances without checking.** Especially with unequal group sizes, ignoring unequal variances (using Student's test when Welch's is warranted) can distort the Type I error rate — the larger group's variance can dominate misleadingly.\n-   **Using the** $F$-test to check variance equality on non-normal data. As seen above, the $F$-test can itself mislead when the data are skewed; prefer Levene's test.\n-   **Over-relying on Shapiro-Wilk in large samples.** With $n$ in the thousands, trivial deviations from normality become \"significant\" — always inspect the plot as well.\n-   **Letting outliers dominate a** $t$-test. A single extreme value (like the $645$ mg/dL cholesterol reading here) can materially shift a group's mean and variance; the Mann-Whitney test is far more robust to this.\n-   **Interpreting the Mann-Whitney test as strictly a median comparison.** It formally tests for a general **distributional/location shift**; it approximates a median comparison well only when the two distributions have similar shape and spread.\n-   **Confusing statistical and clinical significance.** With WCGS's large $n$, even modest mean differences (e.g., $1.8$ lb in weight) become statistically significant — always report and interpret the effect size and CI, not just the $p$-value.\n\n------------------------------------------------------------------------\n\n# Summary\n\n-   To compare the means of **two independent groups**, first assess normality and variance homogeneity within each group.\n-   **Student's pooled-variance** $t$-test is appropriate when both groups are approximately normal with similar variances (as with weight by behaviour pattern in the WCGS data: $t=2.39$, $p=0.017$, essentially identical to Welch's result).\n-   **Welch's** $t$-test relaxes the equal-variance assumption and is a safe general default; it diverges most from Student's test when variances and sample sizes are both unequal (as with cholesterol by CHD status: Student's $df=3140$ vs. Welch's $df=290.3$, though both still reach the same substantive conclusion here).\n-   The **Mann-Whitney U test** (Wilcoxon rank-sum test) compares two groups using ranks rather than raw values, requiring no distributional assumption beyond independence — it is the method of choice for skewed data, small samples, or data with outliers, and agreed closely with the parametric tests in our cholesterol example (Hodges-Lehmann shift $24.0$ mg/dL vs. mean difference $25.8$ mg/dL).\n\n------------------------------------------------------------------------\n\n# References {.unnumbered}\n\n-   Rosner B. *Fundamentals of Biostatistics*. 8th ed. Cengage Learning.\n-   Daniel WW, Cross CL. *Biostatistics: A Foundation for Analysis in the Health Sciences*. 11th ed. Wiley.\n-   Bland M. *An Introduction to Medical Statistics*. 4th ed. Oxford University Press.\n-   Welch BL. \"The generalization of 'Student's' problem when several different population variances are involved.\" *Biometrika*. 1947;34(1-2):28-35.\n-   Mann HB, Whitney DR. \"On a Test of Whether one of Two Random Variables is Stochastically Larger than the Other.\" *Annals of Mathematical Statistics*. 1947;18(1):50-60.\n-   Rosenman RH, et al. \"A predictive study of coronary heart disease: the Western Collaborative Group Study.\" *JAMA*. 1964;189:15-22. (Original WCGS study.)\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}