<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.31">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Count Data analysis – Biostatistics with R</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../Section2/Survival analysis/16_Survival_analysis.html" rel="next">
<link href="../../Section2/Categorical data analysis/14_Categorical_data_analysis.html" rel="prev">
<link href="../../cover.png" rel="icon" type="image/png">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-4a990d8dcb58f517c7c86712b8f2ac7c.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark-46f4cc9626f044588a66931b604fc9c8.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-4a990d8dcb58f517c7c86712b8f2ac7c.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-b7a59ac9f7e3a770d9eeb162b88b5d40.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-dark-f524101b5d1cb1deb615440f12630413.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../../site_libs/bootstrap/bootstrap-b7a59ac9f7e3a770d9eeb162b88b5d40.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../Section2/01_introduction_to_Biostat.html">Biostatistics</a></li><li class="breadcrumb-item"><a href="../../Section2/Count data analysis/15_Poisson_regression.html"><span class="chapter-title">Count Data analysis</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="../../index.html" class="sidebar-logo-link">
      <img src="../../cover.png" alt="" class="sidebar-logo py-0 d-lg-inline d-none">
      </a>
    <div class="sidebar-title mb-0 py-0">
      <a href="../../">Biostatistics with R</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://github.com/Adrisyaone" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
    <a href="../../Biostatistics-with-R.pdf" title="Download PDF" class="quarto-navigation-tool px-1" aria-label="Download PDF"><i class="bi bi-file-pdf"></i></a>
    <div class="dropdown">
      <a href="" title="Share" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" role="link" aria-label="Share"><i class="bi bi-share"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-0">
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://twitter.com/intent/tweet?url=|url|">
              <i class="bi bi-twitter pe-1"></i>
            Twitter
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://www.linkedin.com/sharing/share-offsite/?url=|url|">
              <i class="bi bi-linkedin pe-1"></i>
            LinkedIn
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://www.facebook.com/sharer/sharer.php?u=|url|">
              <i class="bi bi-facebook pe-1"></i>
            Facebook
            </a>
          </li>
      </ul>
    </div>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Introduction to R</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../section1/Chapter1/01_introductions.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Introduction to R</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../section1/Chapter2/02_basics.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Basics in R: Part-1</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../section1/Chapter3/03_basics.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Basics in R: Part-2 (Data cleaning)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../section1/chapter4/04_data_types.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Data and variables</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Biostatistics</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Section2/01_introduction_to_Biostat.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Introduction to Biostatistics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Section2/02_Data_types.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Types of data and scales of measurement</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Section2/03_measures_central_tendency.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Measures of Central Tendency</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Section2/04_measures_of_dispersion.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Measures of Dispersion</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Section2/05_descriptives.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Descriptive Statistics with R (Practical Part)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Section2/06_probability.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Probability</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Section2/07_discrete_probability_distributions.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Discrete Probability Distributions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Section2/08_continuous_probability_distributions.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Continuous Probability Distributions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Section2/09_Sampling distribution.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Sampling distribution and Central Limit theorem</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Section2/10_estimation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Estimation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Section2/11_intro_hypothesis_testing.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Hypothesis Testing</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Section2/12_bivariate.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Basic statistical tests</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Section2/Numerical data analysis/13_linear_regression.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Linear regression Analysis</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Section2/Categorical data analysis/14_Categorical_data_analysis.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Categorical data analysis</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Section2/Count data analysis/15_Poisson_regression.html" class="sidebar-item-text sidebar-link active"><span class="chapter-title">Count Data analysis</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Section2/Survival analysis/16_Survival_analysis.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Survival Analysis</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Section2/17_sampling.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Sampling distribution and Central Limit theorem</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Section2/Sample size calculation/18_Sample_size_calculation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Sample Size estimation and power</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#count-data" id="toc-count-data" class="nav-link active" data-scroll-target="#count-data">Count data</a></li>
  <li><a href="#poisson-distribution" id="toc-poisson-distribution" class="nav-link" data-scroll-target="#poisson-distribution">Poisson Distribution</a></li>
  <li><a href="#poisson-regression" id="toc-poisson-regression" class="nav-link" data-scroll-target="#poisson-regression">Poisson Regression</a>
  <ul class="collapse">
  <li><a href="#assumptions-of-poisson-regression" id="toc-assumptions-of-poisson-regression" class="nav-link" data-scroll-target="#assumptions-of-poisson-regression">Assumptions of Poisson Regression</a></li>
  </ul></li>
  <li><a href="#worked-example-poisson-regression-in-r" id="toc-worked-example-poisson-regression-in-r" class="nav-link" data-scroll-target="#worked-example-poisson-regression-in-r">Worked Example: Poisson Regression in R</a>
  <ul class="collapse">
  <li><a href="#fit-the-model" id="toc-fit-the-model" class="nav-link" data-scroll-target="#fit-the-model">Fit the model</a></li>
  <li><a href="#interpreting-coefficients-as-incidence-rate-ratios-irrs" id="toc-interpreting-coefficients-as-incidence-rate-ratios-irrs" class="nav-link" data-scroll-target="#interpreting-coefficients-as-incidence-rate-ratios-irrs">Interpreting coefficients as Incidence Rate Ratios (IRRs)</a></li>
  <li><a href="#predicted-counts" id="toc-predicted-counts" class="nav-link" data-scroll-target="#predicted-counts">Predicted counts</a></li>
  <li><a href="#modeling-rates-with-an-offset" id="toc-modeling-rates-with-an-offset" class="nav-link" data-scroll-target="#modeling-rates-with-an-offset">Modeling rates with an offset</a></li>
  <li><a href="#goodness-of-fit" id="toc-goodness-of-fit" class="nav-link" data-scroll-target="#goodness-of-fit">Goodness of fit</a></li>
  </ul></li>
  <li><a href="#overdispersion-and-zero-inflated-count-models" id="toc-overdispersion-and-zero-inflated-count-models" class="nav-link" data-scroll-target="#overdispersion-and-zero-inflated-count-models">Overdispersion and Zero-Inflated Count Models</a>
  <ul class="collapse">
  <li><a href="#why-poisson-regression-is-often-not-enough" id="toc-why-poisson-regression-is-often-not-enough" class="nav-link" data-scroll-target="#why-poisson-regression-is-often-not-enough">Why Poisson Regression Is Often Not Enough</a></li>
  <li><a href="#worked-example-emergency-department-ed-visits" id="toc-worked-example-emergency-department-ed-visits" class="nav-link" data-scroll-target="#worked-example-emergency-department-ed-visits">Worked Example: Emergency Department (ED) Visits</a></li>
  <li><a href="#rcode" id="toc-rcode" class="nav-link" data-scroll-target="#rcode">Rcode</a></li>
  <li><a href="#fit-poisson-regression-and-check-the-assumptions" id="toc-fit-poisson-regression-and-check-the-assumptions" class="nav-link" data-scroll-target="#fit-poisson-regression-and-check-the-assumptions">Fit Poisson Regression and Check the Assumptions</a></li>
  <li><a href="#interpretation" id="toc-interpretation" class="nav-link" data-scroll-target="#interpretation">Interpretation</a></li>
  </ul></li>
  <li><a href="#negative-binomial-regression" id="toc-negative-binomial-regression" class="nav-link" data-scroll-target="#negative-binomial-regression">Negative Binomial Regression</a>
  <ul class="collapse">
  <li><a href="#the-model" id="toc-the-model" class="nav-link" data-scroll-target="#the-model">The model</a></li>
  <li><a href="#when-to-use-negative-binomial-instead-of-poisson" id="toc-when-to-use-negative-binomial-instead-of-poisson" class="nav-link" data-scroll-target="#when-to-use-negative-binomial-instead-of-poisson">When to use Negative Binomial instead of Poisson</a></li>
  <li><a href="#interpretation-1" id="toc-interpretation-1" class="nav-link" data-scroll-target="#interpretation-1">Interpretation</a></li>
  </ul></li>
  <li><a href="#zero-inflated-poisson-zip-regression" id="toc-zero-inflated-poisson-zip-regression" class="nav-link" data-scroll-target="#zero-inflated-poisson-zip-regression">Zero-Inflated Poisson (ZIP) Regression</a>
  <ul class="collapse">
  <li><a href="#the-model-1" id="toc-the-model-1" class="nav-link" data-scroll-target="#the-model-1">The model</a></li>
  <li><a href="#when-to-use-zip" id="toc-when-to-use-zip" class="nav-link" data-scroll-target="#when-to-use-zip">When to use ZIP</a></li>
  <li><a href="#r-code" id="toc-r-code" class="nav-link" data-scroll-target="#r-code">R code</a></li>
  <li><a href="#interpretation-2" id="toc-interpretation-2" class="nav-link" data-scroll-target="#interpretation-2">Interpretation</a></li>
  </ul></li>
  <li><a href="#zero-inflated-negative-binomial-zinb-regression" id="toc-zero-inflated-negative-binomial-zinb-regression" class="nav-link" data-scroll-target="#zero-inflated-negative-binomial-zinb-regression">Zero-Inflated Negative Binomial (ZINB) Regression</a>
  <ul class="collapse">
  <li><a href="#the-model-2" id="toc-the-model-2" class="nav-link" data-scroll-target="#the-model-2">The model</a></li>
  <li><a href="#when-to-use-zinb" id="toc-when-to-use-zinb" class="nav-link" data-scroll-target="#when-to-use-zinb">When to use ZINB</a></li>
  <li><a href="#r-code-1" id="toc-r-code-1" class="nav-link" data-scroll-target="#r-code-1">R code</a></li>
  <li><a href="#interpretation-3" id="toc-interpretation-3" class="nav-link" data-scroll-target="#interpretation-3">Interpretation</a></li>
  </ul></li>
  <li><a href="#comparing-all-four-models" id="toc-comparing-all-four-models" class="nav-link" data-scroll-target="#comparing-all-four-models">Comparing All Four Models</a>
  <ul class="collapse">
  <li><a href="#formal-comparison-tests" id="toc-formal-comparison-tests" class="nav-link" data-scroll-target="#formal-comparison-tests">Formal comparison tests</a></li>
  <li><a href="#a-related-alternative-hurdle-models" id="toc-a-related-alternative-hurdle-models" class="nav-link" data-scroll-target="#a-related-alternative-hurdle-models">A Related Alternative: Hurdle Models</a></li>
  </ul></li>
  <li><a href="#decision-guide-which-model-should-i-use" id="toc-decision-guide-which-model-should-i-use" class="nav-link" data-scroll-target="#decision-guide-which-model-should-i-use">Decision Guide: Which Model Should I Use?</a></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary">Summary</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/Adrisyaone/edit/main/Section2/Count data analysis/15_Poisson_regression.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/Adrisyaone/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../Section2/01_introduction_to_Biostat.html">Biostatistics</a></li><li class="breadcrumb-item"><a href="../../Section2/Count data analysis/15_Poisson_regression.html"><span class="chapter-title">Count Data analysis</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-title">Count Data analysis</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="count-data" class="level2">
<h2 class="anchored" data-anchor-id="count-data">Count data</h2>
<p>The data consisting of non-negative integers values which is the count of occurrence of events. Due to the discrete nature, the count data can’t be treated as continuous variables. The categorical analysis methods are also not appropriate. The examples of count data are:</p>
<p>a) Number of risk factors of NCDs present in a person</p>
<p>b) Number of people visiting doctor’s office per month</p>
</section>
<section id="poisson-distribution" class="level2">
<h2 class="anchored" data-anchor-id="poisson-distribution">Poisson Distribution</h2>
<p>It is the distribution if we want to calculate the probabilities of the number of ocurences of some phenomenon in some space or time interval, often measured as the rate (average given the measired space).</p>
<p><span class="math display">\[
f(x)= \frac{e^{-\lambda}*\lambda^x}{x!}, x=1,2,...
\]</span></p>
<p><span class="math display">\[
E(x)=Var(x) = lambda
\]</span></p>
<p><span class="math inline">\(\lambda\)</span> (rate) is the average number of some success in sometime span.</p>
</section>
<section id="poisson-regression" class="level2">
<h2 class="anchored" data-anchor-id="poisson-regression">Poisson Regression</h2>
<p>Poisson regression is particularly useful for:</p>
<ul>
<li>Modeling the count of events occurring within a fixed period or space.</li>
<li>Predicting counts based on predictor variables.</li>
</ul>
<p>The general form of the Poisson regression model is:</p>
<p><span class="math display">\[
\log(\lambda_i) = \beta_0 + \beta_1 X_1 + \beta_2 X_2 + \ldots + \beta_n X_n
\]</span></p>
<hr>
<section id="assumptions-of-poisson-regression" class="level3">
<h3 class="anchored" data-anchor-id="assumptions-of-poisson-regression">Assumptions of Poisson Regression</h3>
<ol type="1">
<li><p><strong>Poisson Distribution</strong>: The response variable ( Y_i ) follows a Poisson distribution. <span class="math display">\[
Y_i \sim \text{Poisson}(\lambda_i)
\]</span></p></li>
<li><p><strong>Log Link Function</strong>: The logarithm of the mean ( _i ) is linearly related to the predictors. <span class="math display">\[
\log(\lambda_i) = X\beta
\]</span></p></li>
<li><p><strong>Equality of Mean and Variance</strong>: The mean and variance of the response variable are equal. <span class="math display">\[
E(Y_i) = Var(Y_i) = \lambda_i
\]</span></p></li>
<li><p><strong>Independence</strong>: Observations are independent of each other.</p></li>
<li><p><strong>No Multi-collinearity</strong>: Predictor variables should not exhibit high collinearity.</p></li>
</ol>
<hr>
</section>
</section>
<section id="worked-example-poisson-regression-in-r" class="level2">
<h2 class="anchored" data-anchor-id="worked-example-poisson-regression-in-r">Worked Example: Poisson Regression in R</h2>
<p>We use the same simulated dataset as the rest of this chapter (<code>ed_visits.csv</code>, <span class="math inline">\(n=400\)</span>): a cohort of adult patients followed for one year, with outcome <code>ed_visits</code> (number of Emergency Department visits) and predictors <code>age</code>, <code>smoker</code>, <code>chronic</code> (number of chronic conditions), and <code>insured</code>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"D:/Epi Biostat with R/Biostat_with_R/Section2/Count data analysis/ed_visits.csv"</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>dat<span class="sc">$</span>age_c <span class="ot">&lt;-</span> (dat<span class="sc">$</span>age <span class="sc">-</span> <span class="dv">50</span>) <span class="sc">/</span> <span class="dv">10</span>   <span class="co"># age centered at 50, scaled per decade</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(dat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt;   age smoker chronic insured ed_visits age_c
#&gt; 1  30      0       2       1         0  -2.0
#&gt; 2  61      0       2       1         1   1.1
#&gt; 3  49      0       2       0         0  -0.1
#&gt; 4  43      0       1       1         0  -0.7
#&gt; 5  42      0       0       1         0  -0.8
#&gt; 6  71      0       1       1         0   2.1</code></pre>
</div>
</div>
<section id="fit-the-model" class="level3">
<h3 class="anchored" data-anchor-id="fit-the-model">Fit the model</h3>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>m_pois <span class="ot">&lt;-</span> <span class="fu">glm</span>(ed_visits <span class="sc">~</span> age_c <span class="sc">+</span> smoker <span class="sc">+</span> chronic <span class="sc">+</span> insured,</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>              <span class="at">family =</span> <span class="fu">poisson</span>(<span class="at">link =</span> <span class="st">"log"</span>), <span class="at">data =</span> dat)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m_pois)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; 
#&gt; Call:
#&gt; glm(formula = ed_visits ~ age_c + smoker + chronic + insured, 
#&gt;     family = poisson(link = "log"), data = dat)
#&gt; 
#&gt; Coefficients:
#&gt;             Estimate Std. Error z value Pr(&gt;|z|)    
#&gt; (Intercept) -0.99973    0.11273  -8.868  &lt; 2e-16 ***
#&gt; age_c        0.64145    0.02747  23.348  &lt; 2e-16 ***
#&gt; smoker       0.10107    0.07400   1.366 0.171991    
#&gt; chronic      0.43979    0.03138  14.014  &lt; 2e-16 ***
#&gt; insured      0.29965    0.08769   3.417 0.000633 ***
#&gt; ---
#&gt; Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
#&gt; 
#&gt; (Dispersion parameter for poisson family taken to be 1)
#&gt; 
#&gt;     Null deviance: 2086.9  on 399  degrees of freedom
#&gt; Residual deviance: 1197.0  on 395  degrees of freedom
#&gt; AIC: 1653.6
#&gt; 
#&gt; Number of Fisher Scoring iterations: 6</code></pre>
</div>
</div>
</section>
<section id="interpreting-coefficients-as-incidence-rate-ratios-irrs" class="level3">
<h3 class="anchored" data-anchor-id="interpreting-coefficients-as-incidence-rate-ratios-irrs">Interpreting coefficients as Incidence Rate Ratios (IRRs)</h3>
<p>Because the log link is used, exponentiating the coefficients converts them from the log scale to <strong>incidence rate ratios</strong> — the multiplicative change in the expected count per one-unit increase in the predictor.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">cbind</span>(<span class="at">IRR =</span> <span class="fu">coef</span>(m_pois), <span class="fu">confint</span>(m_pois)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt;                   IRR     2.5 %    97.5 %
#&gt; (Intercept) 0.3679788 0.2939149 0.4572799
#&gt; age_c       1.8992313 1.8010611 2.0059258
#&gt; smoker      1.1063528 0.9563549 1.2783456
#&gt; chronic     1.5523778 1.4596413 1.6507482
#&gt; insured     1.3493914 1.1392668 1.6069800</code></pre>
</div>
</div>
<p>For example, an IRR of 1.68 for <code>chronic</code> means each additional chronic condition is associated with a 68% increase in expected ED visits, holding other predictors constant.</p>
</section>
<section id="predicted-counts" class="level3">
<h3 class="anchored" data-anchor-id="predicted-counts">Predicted counts</h3>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>dat<span class="sc">$</span>pred_visits <span class="ot">&lt;-</span> <span class="fu">predict</span>(m_pois, <span class="at">type =</span> <span class="st">"response"</span>)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(dat[, <span class="fu">c</span>(<span class="st">"age"</span>, <span class="st">"smoker"</span>, <span class="st">"chronic"</span>, <span class="st">"insured"</span>, <span class="st">"ed_visits"</span>, <span class="st">"pred_visits"</span>)])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt;   age smoker chronic insured ed_visits pred_visits
#&gt; 1  30      0       2       1         0   0.3317416
#&gt; 2  61      0       2       1         1   2.4232111
#&gt; 3  49      0       2       0         0   0.8316870
#&gt; 4  43      0       1       1         0   0.4919871
#&gt; 5  42      0       0       1         0   0.2972340
#&gt; 6  71      0       1       1         0   2.9646381</code></pre>
</div>
</div>
</section>
<section id="modeling-rates-with-an-offset" class="level3">
<h3 class="anchored" data-anchor-id="modeling-rates-with-an-offset">Modeling rates with an offset</h3>
<p>When counts are observed over varying amounts of time or exposure (e.g., person-years of follow-up), an <strong>offset</strong> is used so the model estimates a <em>rate</em> rather than a raw count. If <code>dat$time</code> held each patient’s follow-up time, the model would be:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>m_rate <span class="ot">&lt;-</span> <span class="fu">glm</span>(ed_visits <span class="sc">~</span> age_c <span class="sc">+</span> smoker <span class="sc">+</span> chronic <span class="sc">+</span> insured,</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>              <span class="at">family =</span> <span class="fu">poisson</span>(<span class="at">link =</span> <span class="st">"log"</span>),</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>              <span class="at">offset =</span> <span class="fu">log</span>(time), <span class="at">data =</span> dat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The offset enters the model with a fixed coefficient of 1, so <code>log(lambda_i / time_i)</code> is modeled instead of <code>log(lambda_i)</code> — the fitted coefficients are then interpreted as rate ratios per unit time.</p>
</section>
<section id="goodness-of-fit" class="level3">
<h3 class="anchored" data-anchor-id="goodness-of-fit">Goodness of fit</h3>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span> <span class="sc">-</span> <span class="fu">pchisq</span>(<span class="fu">deviance</span>(m_pois), <span class="at">df =</span> m_pois<span class="sc">$</span>df.residual)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; [1] 0</code></pre>
</div>
</div>
<p>A small p-value here suggests the model does not fit well — this is the first diagnostic that motivates checking for overdispersion and excess zeros, covered next.</p>
</section>
</section>
<section id="overdispersion-and-zero-inflated-count-models" class="level2">
<h2 class="anchored" data-anchor-id="overdispersion-and-zero-inflated-count-models">Overdispersion and Zero-Inflated Count Models</h2>
<section id="why-poisson-regression-is-often-not-enough" class="level3">
<h3 class="anchored" data-anchor-id="why-poisson-regression-is-often-not-enough">Why Poisson Regression Is Often Not Enough</h3>
<p>Poisson regression, which rests on a strict assumption: <strong>the mean and the variance of the count are equal</strong>, <span class="math inline">\(E(Y_i)=Var(Y_i)=\lambda_i\)</span>. Real health-count data almost never behave this politely. Two problems show up constantly in clinical and public-health data:</p>
<ol type="1">
<li><strong>Overdispersion</strong> — the observed variance is <em>larger</em> than the mean (sometimes far larger), because of unmeasured heterogeneity between patients, clustering of events within a person, or contagion-type processes (one hospitalization increases the risk of another).</li>
<li><strong>Excess zeros</strong> — the data contain more zero counts than a Poisson (or even a Negative Binomial) distribution would predict, because some individuals are structurally incapable of generating a positive count (e.g., a never-smoker cannot have a smoking-related complication count above zero) while others simply happened to have a zero during the observation window.</li>
</ol>
<p>Ignoring either problem does not just produce a “slightly wrong” model — it produces <strong>standard errors that are too small</strong>, which inflates Type-I error and makes non-significant predictors look significant. This chapter builds, step by step, the toolbox used to diagnose and correct these problems:</p>
<ul>
<li><strong>Negative Binomial (NB) regression</strong> — corrects overdispersion.</li>
<li><strong>Zero-Inflated Poisson (ZIP) regression</strong> — corrects excess zeros when counts are otherwise equidispersed.</li>
<li><strong>Zero-Inflated Negative Binomial (ZINB) regression</strong> — corrects excess zeros <em>and</em> overdispersion simultaneously.</li>
<li>A short note on <strong>Hurdle models</strong>, a close relative of the zero-inflated family.</li>
</ul>
<p>Every model below is fit on the same worked health example so the numbers can be compared directly.</p>
<hr>
</section>
<section id="worked-example-emergency-department-ed-visits" class="level3">
<h3 class="anchored" data-anchor-id="worked-example-emergency-department-ed-visits">Worked Example: Emergency Department (ED) Visits</h3>
<p>Imagine a cohort of 400 adult patients followed for one year, and we count each patient’s number of <strong>Emergency Department visits</strong>. Predictors collected at baseline are:</p>
<p>a) <code>age</code> — age in years</p>
<p>b) <code>smoker</code> — current smoker (1) vs.&nbsp;non-smoker (0)</p>
<p>c) <code>chronic</code> — number of chronic conditions (0–4): diabetes, hypertension, COPD, heart disease</p>
<p>d) <code>insured</code> — has health insurance (1) vs.&nbsp;does not (0)</p>
<p>This is a realistic setting for <strong>two separate zero-generating mechanisms</strong>: some patients are simply not “at risk” of an ED visit in a given year (healthy, well-controlled, good access to primary care — a <em>structural</em> zero), while others are at risk but simply happened not to visit during the window (a <em>sampling</em> zero, drawn from a Poisson/NB process). This is exactly the situation zero-inflated models were built for.</p>
<p>The simulated dataset (<code>ed_visits.csv</code>, <span class="math inline">\(n=400\)</span>) used throughout this chapter is saved alongside this file so every result below is fully reproducible.</p>
</section>
<section id="rcode" class="level3">
<h3 class="anchored" data-anchor-id="rcode">Rcode</h3>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MASS)     <span class="co"># glm.nb()</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(pscl)      <span class="co"># zeroinfl(), odTest(), vuong()</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(AER)        <span class="co"># dispersiontest()</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"ed_visits.csv"</span>)</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>dat<span class="sc">$</span>age_c <span class="ot">&lt;-</span> (dat<span class="sc">$</span>age <span class="sc">-</span> <span class="dv">50</span>) <span class="sc">/</span> <span class="dv">10</span>   <span class="co"># age centered at 50, scaled per decade</span></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(dat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; 'data.frame':    400 obs. of  6 variables:
#&gt;  $ age      : int  30 61 49 43 42 71 79 30 62 38 ...
#&gt;  $ smoker   : int  0 0 0 0 0 0 0 1 0 1 ...
#&gt;  $ chronic  : int  2 2 2 1 0 1 2 2 3 4 ...
#&gt;  $ insured  : int  1 1 0 1 1 1 1 0 1 1 ...
#&gt;  $ ed_visits: int  0 1 0 0 0 0 6 2 2 0 ...
#&gt;  $ age_c    : num  -2 1.1 -0.1 -0.7 -0.8 2.1 2.9 -2 1.2 -1.2 ...</code></pre>
</div>
</div>
<p>A quick look at the outcome already hints at trouble:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(dat<span class="sc">$</span>ed_visits)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; [1] 1.8975</code></pre>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">var</span>(dat<span class="sc">$</span>ed_visits)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; [1] 14.18746</code></pre>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">prop.table</span>(<span class="fu">table</span>(dat<span class="sc">$</span>ed_visits <span class="sc">==</span> <span class="dv">0</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; 
#&gt; FALSE  TRUE 
#&gt;  0.34  0.66</code></pre>
</div>
</div>
<p>The mean number of visits is about <strong>1.90</strong>, but the variance is about <strong>14.2</strong> — roughly <strong>7.5 times larger</strong> than the mean. Under a true Poisson process these should be equal. In addition, <strong>66%</strong> of patients have zero ED visits. Both signs point away from a plain Poisson model, but we fit it first anyway, because the diagnostics it produces are exactly what justify moving to the more complex models.</p>
<hr>
</section>
<section id="fit-poisson-regression-and-check-the-assumptions" class="level3">
<h3 class="anchored" data-anchor-id="fit-poisson-regression-and-check-the-assumptions">Fit Poisson Regression and Check the Assumptions</h3>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>m_pois <span class="ot">&lt;-</span> <span class="fu">glm</span>(ed_visits <span class="sc">~</span> age_c <span class="sc">+</span> smoker <span class="sc">+</span> chronic <span class="sc">+</span> insured,</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>              <span class="at">family =</span> <span class="fu">poisson</span>(<span class="at">link =</span> <span class="st">"log"</span>), <span class="at">data =</span> dat)</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m_pois)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; 
#&gt; Call:
#&gt; glm(formula = ed_visits ~ age_c + smoker + chronic + insured, 
#&gt;     family = poisson(link = "log"), data = dat)
#&gt; 
#&gt; Coefficients:
#&gt;             Estimate Std. Error z value Pr(&gt;|z|)    
#&gt; (Intercept) -0.99973    0.11273  -8.868  &lt; 2e-16 ***
#&gt; age_c        0.64145    0.02747  23.348  &lt; 2e-16 ***
#&gt; smoker       0.10107    0.07400   1.366 0.171991    
#&gt; chronic      0.43979    0.03138  14.014  &lt; 2e-16 ***
#&gt; insured      0.29965    0.08769   3.417 0.000633 ***
#&gt; ---
#&gt; Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
#&gt; 
#&gt; (Dispersion parameter for poisson family taken to be 1)
#&gt; 
#&gt;     Null deviance: 2086.9  on 399  degrees of freedom
#&gt; Residual deviance: 1197.0  on 395  degrees of freedom
#&gt; AIC: 1653.6
#&gt; 
#&gt; Number of Fisher Scoring iterations: 6</code></pre>
</div>
</div>
<p><strong>Formal overdispersion test</strong> (Cameron &amp; Trivedi regression-based test):</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dispersiontest</span>(m_pois)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; 
#&gt;  Overdispersion test
#&gt; 
#&gt; data:  m_pois
#&gt; z = 4.7601, p-value = 9.674e-07
#&gt; alternative hypothesis: true dispersion is greater than 1
#&gt; sample estimates:
#&gt; dispersion 
#&gt;   4.063466</code></pre>
</div>
</div>
<p><strong>Comparing observed vs.&nbsp;Poisson-predicted zeros:</strong></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>mu_hat <span class="ot">&lt;-</span> <span class="fu">fitted</span>(m_pois)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>obs_zero  <span class="ot">&lt;-</span> <span class="fu">mean</span>(dat<span class="sc">$</span>ed_visits <span class="sc">==</span> <span class="dv">0</span>)</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>pred_zero <span class="ot">&lt;-</span> <span class="fu">mean</span>(<span class="fu">exp</span>(<span class="sc">-</span>mu_hat))</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">observed =</span> obs_zero, <span class="at">poisson_predicted =</span> pred_zero)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt;          observed poisson_predicted 
#&gt;         0.6600000         0.4074593</code></pre>
</div>
</div>
</section>
<section id="interpretation" class="level3">
<h3 class="anchored" data-anchor-id="interpretation">Interpretation</h3>
<p>The dispersion statistic is about <strong>4.1</strong> (should be <span class="math inline">\(\approx 1\)</span> under a true Poisson model), and <code>dispersiontest()</code> rejects equidispersion at <span class="math inline">\(p&lt;0.001\)</span>. The model also badly under-predicts zeros: Poisson expects only about <strong>41%</strong> zero visits, but <strong>66%</strong> are observed in the data. Both diagnostics say the same thing: <strong>Poisson regression is not adequate here</strong>, and any p-values from <code>m_pois</code> should not be trusted — they are too optimistic (SEs too small). This is the standard trigger for moving to Negative Binomial regression.</p>
</section>
</section>
<section id="negative-binomial-regression" class="level2">
<h2 class="anchored" data-anchor-id="negative-binomial-regression">Negative Binomial Regression</h2>
<section id="the-model" class="level3">
<h3 class="anchored" data-anchor-id="the-model">The model</h3>
<p>The Negative Binomial (NB2, the standard parameterization) extends Poisson by adding a dispersion parameter <span class="math inline">\(\alpha&gt;0\)</span>:</p>
<p><span class="math display">\[
Var(Y_i) = \mu_i + \alpha\,\mu_i^2
\]</span></p>
<p>When <span class="math inline">\(\alpha \to 0\)</span>, NB collapses back to Poisson (<span class="math inline">\(Var=\mu\)</span>), which is why Poisson is a special case of NB and the two can be compared with a likelihood-ratio test. The mean structure is unchanged, <span class="math inline">\(\log(\mu_i)=X_i\beta\)</span>, so the <strong>interpretation of coefficients is identical to Poisson</strong> (incidence rate ratios, IRRs) — only the variance (and therefore the standard errors and p-values) is corrected.</p>
</section>
<section id="when-to-use-negative-binomial-instead-of-poisson" class="level3">
<h3 class="anchored" data-anchor-id="when-to-use-negative-binomial-instead-of-poisson">When to use Negative Binomial instead of Poisson</h3>
<ul>
<li>The Pearson/deviance dispersion statistic is noticeably <span class="math inline">\(&gt;1\)</span> (commonly used rule of thumb: <span class="math inline">\(&gt;1.5\)</span>–<span class="math inline">\(2\)</span> deserves attention; here it is <span class="math inline">\(4.1\)</span>).</li>
<li><code>dispersiontest()</code> (or an equivalent LR/score test) rejects equidispersion.</li>
<li>Overdispersion is plausibly due to <strong>unobserved heterogeneity</strong> between subjects rather than a distinct “always-zero” subpopulation (if the zeros look structurally different from the rest, consider zero-inflated models first — see below).</li>
<li>There is <strong>no strong a-priori reason to model the zeros with a separate process</strong> — NB simply lets the whole distribution be more spread out, including allowing more zeros than Poisson.</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>m_nb <span class="ot">&lt;-</span> <span class="fu">glm.nb</span>(ed_visits <span class="sc">~</span> age_c <span class="sc">+</span> smoker <span class="sc">+</span> chronic <span class="sc">+</span> insured, <span class="at">data =</span> dat)</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m_nb)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; 
#&gt; Call:
#&gt; glm.nb(formula = ed_visits ~ age_c + smoker + chronic + insured, 
#&gt;     data = dat, init.theta = 0.3862060674, link = log)
#&gt; 
#&gt; Coefficients:
#&gt;             Estimate Std. Error z value Pr(&gt;|z|)    
#&gt; (Intercept) -1.05631    0.23936  -4.413 1.02e-05 ***
#&gt; age_c        0.65827    0.06023  10.929  &lt; 2e-16 ***
#&gt; smoker       0.08189    0.20615   0.397    0.691    
#&gt; chronic      0.51981    0.08733   5.952 2.64e-09 ***
#&gt; insured      0.19036    0.21971   0.866    0.386    
#&gt; ---
#&gt; Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
#&gt; 
#&gt; (Dispersion parameter for Negative Binomial(0.3862) family taken to be 1)
#&gt; 
#&gt;     Null deviance: 472.86  on 399  degrees of freedom
#&gt; Residual deviance: 304.78  on 395  degrees of freedom
#&gt; AIC: 1143.9
#&gt; 
#&gt; Number of Fisher Scoring iterations: 1
#&gt; 
#&gt; 
#&gt;               Theta:  0.3862 
#&gt;           Std. Err.:  0.0548 
#&gt; 
#&gt;  2 x log-likelihood:  -1131.8870</code></pre>
</div>
</div>
<p>Incidence rate ratios (IRRs) with 95% CIs:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">cbind</span>(<span class="at">IRR =</span> <span class="fu">coef</span>(m_nb), <span class="fu">confint</span>(m_nb)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt;                   IRR     2.5 %    97.5 %
#&gt; (Intercept) 0.3477372 0.2127285 0.5681924
#&gt; age_c       1.9314550 1.7199622 2.1814970
#&gt; smoker      1.0853375 0.7264347 1.6309138
#&gt; chronic     1.6817129 1.4115011 2.0185060
#&gt; insured     1.2096867 0.7747641 1.8643213</code></pre>
</div>
</div>
<p><strong>Formal test of whether NB is needed over Poisson</strong> (likelihood-ratio test on the boundary of <span class="math inline">\(\alpha=0\)</span>, implemented in <code>pscl::odTest</code>):</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">odTest</span>(m_nb)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; Likelihood ratio test of H0: Poisson, as restricted NB model:
#&gt; n.b., the distribution of the test-statistic under H0 is non-standard
#&gt; e.g., see help(odTest) for details/references
#&gt; 
#&gt; Critical value of test statistic at the alpha= 0.05 level: 2.7055 
#&gt; Chi-Square Test Statistic =  511.7369 p-value = &lt; 2.2e-16</code></pre>
</div>
</div>
<p><strong>Zero-count check for NB:</strong></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>mu_nb    <span class="ot">&lt;-</span> <span class="fu">fitted</span>(m_nb)</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>theta_nb <span class="ot">&lt;-</span> m_nb<span class="sc">$</span>theta</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>p_nb0 <span class="ot">&lt;-</span> <span class="fu">mean</span>((theta_nb <span class="sc">/</span> (theta_nb <span class="sc">+</span> mu_nb))<span class="sc">^</span>theta_nb)</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">observed =</span> obs_zero, <span class="at">nb_predicted =</span> p_nb0)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt;     observed nb_predicted 
#&gt;     0.660000     0.622975</code></pre>
</div>
</div>
</section>
<section id="interpretation-1" class="level3">
<h3 class="anchored" data-anchor-id="interpretation-1">Interpretation</h3>
<p><code>odTest()</code> gives a large LR statistic with <span class="math inline">\(p&lt;0.001\)</span>: overdispersion is real, and NB is a significantly better fit than Poisson (AIC drops from about <strong>1654</strong> to about <strong>1144</strong>). The estimated dispersion parameter <span class="math inline">\(\hat\theta \approx 0.39\)</span> (equivalently <span class="math inline">\(\hat\alpha = 1/\theta \approx 2.6\)</span>) is far from the Poisson limit of <span class="math inline">\(\theta\to\infty\)</span>, confirming strong overdispersion.</p>
<p>Reading the IRRs: each additional chronic condition multiplies the expected number of ED visits by about <span class="math inline">\(e^{0.52}\approx1.68\)</span> (68% more visits per chronic condition, holding other variables fixed), and each 10-year increase in age multiplies expected visits by about <span class="math inline">\(e^{0.66}\approx1.93\)</span>. Smoking status and insurance are no longer significant once overdispersion is properly accounted for (their Poisson p-values were artificially small).</p>
<p>The NB model also predicts the zero proportion much better than Poisson (<strong>62%</strong> vs.&nbsp;the <strong>66%</strong> observed) — but not perfectly. That residual gap is the signature of <strong>excess zeros that NB alone cannot fully explain</strong>, which motivates the zero-inflated models next.</p>
</section>
</section>
<section id="zero-inflated-poisson-zip-regression" class="level2">
<h2 class="anchored" data-anchor-id="zero-inflated-poisson-zip-regression">Zero-Inflated Poisson (ZIP) Regression</h2>
<section id="the-model-1" class="level3">
<h3 class="anchored" data-anchor-id="the-model-1">The model</h3>
<p>ZIP treats the data as coming from a <strong>two-component mixture</strong>:</p>
<ul>
<li>With probability <span class="math inline">\(\pi_i\)</span>, the observation is a <strong>“certain” (structural) zero</strong> — the patient is simply not in the at-risk population for this event.</li>
<li>With probability <span class="math inline">\(1-\pi_i\)</span>, the observation comes from a standard <strong>Poisson</strong> process with mean <span class="math inline">\(\mu_i\)</span> (which can itself produce a zero by chance).</li>
</ul>
<p><span class="math display">\[
P(Y_i = 0) = \pi_i + (1-\pi_i)e^{-\mu_i} \qquad\qquad P(Y_i = y) = (1-\pi_i)\,\frac{e^{-\mu_i}\mu_i^{y}}{y!},\ \ y=1,2,\dots
\]</span></p>
<p>Two linear predictors are estimated simultaneously:</p>
<p><span class="math display">\[
\log(\mu_i) = X_i\beta \quad \text{(count model — "how many events, if any risk exists")}
\]</span></p>
<p><span class="math display">\[
\text{logit}(\pi_i) = Z_i\gamma \quad \text{(zero-inflation model — "probability of being structurally not at risk")}
\]</span></p>
</section>
<section id="when-to-use-zip" class="level3">
<h3 class="anchored" data-anchor-id="when-to-use-zip">When to use ZIP</h3>
<ul>
<li>There is a <strong>substantively meaningful subgroup that cannot experience the event at all</strong> (e.g., patients with no disease exposure, no relevant risk factor, or excellent disease control), distinct from patients who are at risk but simply recorded a zero.</li>
<li>The proportion of zeros observed is clearly larger than a Poisson model predicts.</li>
<li>Among the “at-risk” patients, the counts themselves are close to equidispersed once the structural zeros are separated out (if they remain overdispersed even after removing structural zeros, ZINB is more appropriate — see the AIC comparison below).</li>
</ul>
</section>
<section id="r-code" class="level3">
<h3 class="anchored" data-anchor-id="r-code">R code</h3>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>m_zip <span class="ot">&lt;-</span> <span class="fu">zeroinfl</span>(ed_visits <span class="sc">~</span> age_c <span class="sc">+</span> smoker <span class="sc">+</span> chronic <span class="sc">+</span> insured <span class="sc">|</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>                     age_c <span class="sc">+</span> smoker <span class="sc">+</span> chronic,</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">data =</span> dat, <span class="at">dist =</span> <span class="st">"poisson"</span>, <span class="at">link =</span> <span class="st">"logit"</span>)</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m_zip)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; 
#&gt; Call:
#&gt; zeroinfl(formula = ed_visits ~ age_c + smoker + chronic + insured | age_c + 
#&gt;     smoker + chronic, data = dat, dist = "poisson", link = "logit")
#&gt; 
#&gt; Pearson residuals:
#&gt;      Min       1Q   Median       3Q      Max 
#&gt; -1.64135 -0.57889 -0.29944 -0.09502 17.19354 
#&gt; 
#&gt; Count model coefficients (poisson with log link):
#&gt;             Estimate Std. Error z value Pr(&gt;|z|)    
#&gt; (Intercept)  0.55057    0.13025   4.227 2.37e-05 ***
#&gt; age_c        0.27276    0.03022   9.026  &lt; 2e-16 ***
#&gt; smoker       0.14205    0.07655   1.856 0.063514 .  
#&gt; chronic      0.25446    0.03353   7.589 3.23e-14 ***
#&gt; insured      0.31258    0.09135   3.422 0.000622 ***
#&gt; 
#&gt; Zero-inflation model coefficients (binomial with logit link):
#&gt;             Estimate Std. Error z value Pr(&gt;|z|)    
#&gt; (Intercept)  1.58036    0.24861   6.357 2.06e-10 ***
#&gt; age_c       -0.68454    0.08416  -8.134 4.16e-16 ***
#&gt; smoker      -0.13872    0.25791  -0.538 0.590667    
#&gt; chronic     -0.42778    0.11289  -3.789 0.000151 ***
#&gt; ---
#&gt; Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1 
#&gt; 
#&gt; Number of iterations in BFGS optimization: 16 
#&gt; Log-likelihood: -573.7 on 9 Df</code></pre>
</div>
</div>
<p>The formula has two parts separated by <code>|</code>: the left side is the <strong>count model</strong>, the right side is the <strong>zero-inflation (logit) model</strong> — here we used age, smoking, and chronic-disease count to predict whether a patient belongs to the “never at risk” group.</p>
</section>
<section id="interpretation-2" class="level3">
<h3 class="anchored" data-anchor-id="interpretation-2">Interpretation</h3>
<p><strong>Count component (IRR interpretation, same as Poisson/NB):</strong></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">coef</span>(m_zip, <span class="st">"count"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; (Intercept)       age_c      smoker     chronic     insured 
#&gt;    1.734249    1.313581    1.152634    1.289766    1.366942</code></pre>
</div>
</div>
<p>Among patients who are “at risk,” each additional chronic condition is associated with about <span class="math inline">\(e^{0.25}\approx1.29\)</span> times as many ED visits, and each 10 years of age with about <span class="math inline">\(e^{0.27}\approx1.31\)</span> times as many visits.</p>
<p><strong>Zero-inflation component (odds-ratio interpretation):</strong></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">coef</span>(m_zip, <span class="st">"zero"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; (Intercept)       age_c      smoker     chronic 
#&gt;   4.8567241   0.5043240   0.8704710   0.6519543</code></pre>
</div>
</div>
<p>These coefficients describe the odds of being a <strong>structural (certain) zero</strong>. A negative coefficient means the predictor makes structural-zero membership <em>less</em> likely (i.e., pushes the patient toward the “at-risk” group). Here, older age and a higher chronic-disease count both significantly <strong>reduce</strong> the odds of being a “never visits the ED” patient (odds ratios around <span class="math inline">\(e^{-0.68}\approx0.51\)</span> and <span class="math inline">\(e^{-0.40}\approx0.67\)</span> per unit, respectively) — clinically sensible, since sicker and older patients are less likely to be entirely free of ED risk.</p>
</section>
</section>
<section id="zero-inflated-negative-binomial-zinb-regression" class="level2">
<h2 class="anchored" data-anchor-id="zero-inflated-negative-binomial-zinb-regression">Zero-Inflated Negative Binomial (ZINB) Regression</h2>
<section id="the-model-2" class="level3">
<h3 class="anchored" data-anchor-id="the-model-2">The model</h3>
<p>ZINB is the natural extension when <strong>both</strong> problems are present: excess zeros <em>and</em> overdispersion among the positive counts. It uses the same two-part mixture structure as ZIP, but replaces the Poisson count component with a Negative Binomial:</p>
<p><span class="math display">\[
P(Y_i=0)=\pi_i+(1-\pi_i)\left(\frac{\alpha^{-1}}{\alpha^{-1}+\mu_i}\right)^{\alpha^{-1}}
\]</span></p>
<p><span class="math display">\[
P(Y_i=y)=(1-\pi_i)\,\frac{\Gamma(y+\alpha^{-1})}{y!\,\Gamma(\alpha^{-1})}\left(\frac{\alpha^{-1}}{\alpha^{-1}+\mu_i}\right)^{\alpha^{-1}}\left(\frac{\mu_i}{\alpha^{-1}+\mu_i}\right)^{y},\ \ y=1,2,\dots
\]</span></p>
</section>
<section id="when-to-use-zinb" class="level3">
<h3 class="anchored" data-anchor-id="when-to-use-zinb">When to use ZINB</h3>
<ul>
<li>Excess zeros <strong>and</strong> overdispersion are both present in the non-zero counts (the most common situation in real clinical utilization/morbidity data).</li>
<li>A plain NB model still under-predicts the zero count noticeably.</li>
<li>A plain ZIP model still shows overdispersion in its Pearson residuals, or has a worse AIC/BIC than NB despite fixing the zero problem (exactly what happens in this example, below).</li>
</ul>
</section>
<section id="r-code-1" class="level3">
<h3 class="anchored" data-anchor-id="r-code-1">R code</h3>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>m_zinb <span class="ot">&lt;-</span> <span class="fu">zeroinfl</span>(ed_visits <span class="sc">~</span> age_c <span class="sc">+</span> smoker <span class="sc">+</span> chronic <span class="sc">+</span> insured <span class="sc">|</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>                      age_c <span class="sc">+</span> smoker <span class="sc">+</span> chronic,</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>                    <span class="at">data =</span> dat, <span class="at">dist =</span> <span class="st">"negbin"</span>, <span class="at">link =</span> <span class="st">"logit"</span>)</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m_zinb)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; 
#&gt; Call:
#&gt; zeroinfl(formula = ed_visits ~ age_c + smoker + chronic + insured | age_c + 
#&gt;     smoker + chronic, data = dat, dist = "negbin", link = "logit")
#&gt; 
#&gt; Pearson residuals:
#&gt;      Min       1Q   Median       3Q      Max 
#&gt; -1.12746 -0.51566 -0.28277 -0.05883 15.79316 
#&gt; 
#&gt; Count model coefficients (negbin with log link):
#&gt;             Estimate Std. Error z value Pr(&gt;|z|)    
#&gt; (Intercept)  0.46292    0.20687   2.238   0.0252 *  
#&gt; age_c        0.29137    0.04902   5.943 2.79e-09 ***
#&gt; smoker       0.06716    0.13711   0.490   0.6243    
#&gt; chronic      0.28448    0.06188   4.597 4.29e-06 ***
#&gt; insured      0.29158    0.15340   1.901   0.0573 .  
#&gt; Log(theta)   1.03901    0.25054   4.147 3.37e-05 ***
#&gt; 
#&gt; Zero-inflation model coefficients (binomial with logit link):
#&gt;             Estimate Std. Error z value Pr(&gt;|z|)    
#&gt; (Intercept)  1.40046    0.27074   5.173 2.31e-07 ***
#&gt; age_c       -0.67298    0.08917  -7.547 4.44e-14 ***
#&gt; smoker      -0.14550    0.27655  -0.526 0.598793    
#&gt; chronic     -0.40163    0.12005  -3.346 0.000821 ***
#&gt; ---
#&gt; Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1 
#&gt; 
#&gt; Theta = 2.8264 
#&gt; Number of iterations in BFGS optimization: 18 
#&gt; Log-likelihood: -531.1 on 10 Df</code></pre>
</div>
</div>
</section>
<section id="interpretation-3" class="level3">
<h3 class="anchored" data-anchor-id="interpretation-3">Interpretation</h3>
<p><strong>Count component (IRR):</strong></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">coef</span>(m_zinb, <span class="st">"count"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; (Intercept)       age_c      smoker     chronic     insured 
#&gt;    1.588711    1.338261    1.069467    1.329073    1.338538</code></pre>
</div>
</div>
<p><strong>Zero-inflation component (OR of being a structural zero):</strong></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">coef</span>(m_zinb, <span class="st">"zero"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; (Intercept)       age_c      smoker     chronic 
#&gt;   4.0570830   0.5101870   0.8645866   0.6692264</code></pre>
</div>
</div>
<p>The estimated dispersion parameter here (<code>Log(theta)</code> in the output, back-transformed) corresponds to <span class="math inline">\(\hat\theta\approx2.8\)</span> (<span class="math inline">\(\hat\alpha\approx0.35\)</span>) — much closer to the <em>true</em> amount of overdispersion in the at-risk population than the plain NB model’s inflated <span class="math inline">\(\hat\alpha\approx2.6\)</span>. This is an important lesson: <strong>when zero-inflation is ignored, a plain NB model tends to overestimate the dispersion parameter</strong>, because it is forced to use <span class="math inline">\(\alpha\)</span> to absorb both genuine overdispersion and the excess-zero problem at once. Separating the two mechanisms (as ZINB does) recovers a more accurate picture of both.</p>
<p>The count-model IRRs and zero-inflation odds ratios are similar in direction and magnitude to the ZIP model, but the standard errors and the fit are more appropriate once the leftover overdispersion is modeled properly.</p>
</section>
</section>
<section id="comparing-all-four-models" class="level2">
<h2 class="anchored" data-anchor-id="comparing-all-four-models">Comparing All Four Models</h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>aic_tab <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">Model =</span> <span class="fu">c</span>(<span class="st">"Poisson"</span>, <span class="st">"Negative Binomial"</span>, <span class="st">"Zero-Inflated Poisson"</span>, <span class="st">"Zero-Inflated Negative Binomial"</span>),</span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">AIC   =</span> <span class="fu">c</span>(<span class="fu">AIC</span>(m_pois), <span class="fu">AIC</span>(m_nb), <span class="fu">AIC</span>(m_zip), <span class="fu">AIC</span>(m_zinb))</span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a>aic_tab[<span class="fu">order</span>(aic_tab<span class="sc">$</span>AIC), ]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt;                             Model      AIC
#&gt; 4 Zero-Inflated Negative Binomial 1082.263
#&gt; 2               Negative Binomial 1143.887
#&gt; 3           Zero-Inflated Poisson 1165.410
#&gt; 1                         Poisson 1653.624</code></pre>
</div>
</div>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Model</th>
<th>AIC (approx.)</th>
<th>Handles overdispersion?</th>
<th>Handles excess zeros?</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Poisson</td>
<td>1654</td>
<td>No</td>
<td>No</td>
</tr>
<tr class="even">
<td>Zero-Inflated Poisson (ZIP)</td>
<td>1165</td>
<td>No</td>
<td>Yes</td>
</tr>
<tr class="odd">
<td>Negative Binomial (NB)</td>
<td>1144</td>
<td>Yes</td>
<td>Partially (via wider distribution)</td>
</tr>
<tr class="even">
<td>Zero-Inflated Negative Binomial (ZINB)</td>
<td>1082</td>
<td>Yes</td>
<td>Yes</td>
</tr>
</tbody>
</table>
<p>Notice the instructive (and common) pattern: <strong>fixing only one problem is not always enough.</strong> ZIP fixes the zero problem but still assumes an equidispersed Poisson for the count part, so it actually fits <em>worse</em> than plain NB in this example, because the remaining overdispersion among positive counts is left unmodeled. ZINB, which fixes both problems simultaneously, gives the lowest AIC by a wide margin and is the preferred model here.</p>
<section id="formal-comparison-tests" class="level3">
<h3 class="anchored" data-anchor-id="formal-comparison-tests">Formal comparison tests</h3>
<p><strong>Nested comparison (Poisson vs.&nbsp;NB)</strong> — already shown above with <code>odTest()</code>.</p>
<p><strong>Non-nested / boundary comparisons (Vuong test)</strong> — Poisson vs.&nbsp;ZIP, or NB vs.&nbsp;ZINB, are not compared cleanly with a standard likelihood-ratio test because the models are nested only at a parameter <em>boundary</em> (e.g., <span class="math inline">\(\pi_i \to 0\)</span> for all <span class="math inline">\(i\)</span>). The conventional tool is Vuong’s (1989) test, implemented in <code>pscl::vuong()</code>:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">vuong</span>(m_pois, m_zip)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; Vuong Non-Nested Hypothesis Test-Statistic: 
#&gt; (test-statistic is asymptotically distributed N(0,1) under the
#&gt;  null that the models are indistinguishible)
#&gt; -------------------------------------------------------------
#&gt;               Vuong z-statistic             H_A    p-value
#&gt; Raw                   -7.690100 model2 &gt; model1 7.3510e-15
#&gt; AIC-corrected         -7.566119 model2 &gt; model1 1.9227e-14
#&gt; BIC-corrected         -7.318688 model2 &gt; model1 1.2520e-13</code></pre>
</div>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">vuong</span>(m_nb, m_zinb)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; Vuong Non-Nested Hypothesis Test-Statistic: 
#&gt; (test-statistic is asymptotically distributed N(0,1) under the
#&gt;  null that the models are indistinguishible)
#&gt; -------------------------------------------------------------
#&gt;               Vuong z-statistic             H_A    p-value
#&gt; Raw                   -4.673061 model2 &gt; model1 1.4837e-06
#&gt; AIC-corrected         -4.136110 model2 &gt; model1 1.7662e-05
#&gt; BIC-corrected         -3.064501 model2 &gt; model1  0.0010902</code></pre>
</div>
</div>
<p>A significantly positive Vuong statistic favors the first model listed; a significantly negative statistic favors the second. In this example both tests favor the zero-inflated model over its non-inflated counterpart.</p>
<hr>
</section>
<section id="a-related-alternative-hurdle-models" class="level3">
<h3 class="anchored" data-anchor-id="a-related-alternative-hurdle-models">A Related Alternative: Hurdle Models</h3>
<p>A <strong>hurdle model</strong> is a close cousin of the zero-inflated family, and is worth knowing about even though it is not fit in detail here. The key conceptual difference:</p>
<ul>
<li><strong>Zero-inflated models (ZIP/ZINB):</strong> zeros can come from <em>two</em> sources — structural zeros and sampling zeros from the count process (which can also itself produce a zero).</li>
<li><strong>Hurdle models:</strong> <em>all</em> zeros come from a single binary “hurdle” process (did the event occur at all — yes/no); conditional on crossing the hurdle, the positive counts follow a <strong>zero-truncated</strong> Poisson or NB distribution. There is no separate “chance” zero from the count process — once the hurdle is crossed, the count is guaranteed to be <span class="math inline">\(\geq1\)</span>.</li>
</ul>
<p>Use a hurdle model instead of a zero-inflated model when the two processes (“does the event happen at all” vs.&nbsp;“how many times, given it happens”) are conceptually cleaner than “structural vs.&nbsp;sampling zero,” or when you want a single unambiguous interpretation of the zero mechanism. In R: <code>pscl::hurdle(y ~ x1 + x2 | x1 + x2, dist = "negbin")</code>. Model selection between hurdle and zero-inflated forms again relies on AIC/BIC and substantive reasoning rather than a formal nested test, since the two are non-nested.</p>
<hr>
</section>
</section>
<section id="decision-guide-which-model-should-i-use" class="level2">
<h2 class="anchored" data-anchor-id="decision-guide-which-model-should-i-use">Decision Guide: Which Model Should I Use?</h2>
<p><strong>Start:</strong> you have a count outcome (e.g., number of ED visits, hospitalizations, symptom episodes).</p>
<p><strong>Step 1 — Check dispersion.</strong> Is <span class="math inline">\(Var(Y)\)</span> much larger than <span class="math inline">\(Mean(Y)\)</span> (dispersion statistic <span class="math inline">\(\gg1\)</span>, <code>dispersiontest()</code>/<code>odTest()</code> significant)?</p>
<ul>
<li><strong>No (roughly equidispersed):</strong> go to Step 2a.</li>
<li><strong>Yes (overdispersed):</strong> go to Step 2b.</li>
</ul>
<p><strong>Step 2a — No overdispersion.</strong> Are there more zeros than the Poisson model predicts?</p>
<ul>
<li><strong>No:</strong> use <strong>Poisson regression</strong>.</li>
<li><strong>Yes:</strong> use <strong>Zero-Inflated Poisson (ZIP)</strong>.</li>
</ul>
<p><strong>Step 2b — Overdispersion present.</strong> Are there still more zeros than the Negative Binomial model predicts?</p>
<ul>
<li><strong>No:</strong> use <strong>Negative Binomial (NB)</strong>.</li>
<li><strong>Yes:</strong> use <strong>Zero-Inflated Negative Binomial (ZINB)</strong> (or a Hurdle NB model if the “all zeros share one mechanism” framing fits better substantively).</li>
</ul>
<p><img src="Poisson_pic 1.png" class="img-fluid"></p>
<hr>
</section>
<section id="summary" class="level2">
<h2 class="anchored" data-anchor-id="summary">Summary</h2>
<p>Count outcomes in health research (ED visits, hospitalizations, falls, seizure counts, number of comorbid risk factors) very often violate the Poisson assumption of equal mean and variance, and frequently show more zeros than any single, simple distribution predicts. The practical workflow is:</p>
<ol type="1">
<li>Fit Poisson first; always check the dispersion statistic and compare observed vs.&nbsp;predicted zeros.</li>
<li>If only overdispersion is present, move to <strong>Negative Binomial</strong>.</li>
<li>If only excess zeros are present (counts otherwise well-behaved), move to <strong>Zero-Inflated Poisson</strong>.</li>
<li>If both problems are present — the most common situation in practice — move to <strong>Zero-Inflated Negative Binomial</strong>.</li>
<li>Use AIC/BIC and the Vuong test to choose between non-nested alternatives, and <code>odTest()</code> for the nested Poisson-vs-NB comparison; always sanity-check the substantive story (is there really a distinct “not at risk” subgroup?) rather than choosing a model on fit statistics alone.</li>
<li>Report <strong>incidence rate ratios (IRRs)</strong> from the count component and, for zero-inflated/hurdle models, <strong>odds ratios</strong> from the zero/hurdle component — these answer two different clinical questions (“how many events, given some risk” vs.&nbsp;“who is at risk at all”) and should be interpreted and reported separately.</li>
</ol>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../../Section2/Categorical data analysis/14_Categorical_data_analysis.html" class="pagination-link" aria-label="Categorical data analysis">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-title">Categorical data analysis</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../../Section2/Survival analysis/16_Survival_analysis.html" class="pagination-link" aria-label="Survival Analysis">
        <span class="nav-page-text"><span class="chapter-title">Survival Analysis</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/Adrisyaone/edit/main/Section2/Count data analysis/15_Poisson_regression.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/Adrisyaone/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div></div></footer><script src="../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>