{
  "hash": "42357e67c97972468b1a32f303027b6a",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Survival Analysis\"\noutput:\n  pdf_document:\n    number_sections: yes\n  html_document: default\n---\n\n## Introduction\n\nSometime outcome variable may consist of time-to-event consisting of two components- **Time and event**. **Time** means years, months, weeks or days from the beginning of the follow-up of an individual until an events occurs. Time can be the age of individual when an event occurs. It is non negative values. **Event** means occurrence of death, disease, incidence, recovery or remission or any experience of interest that can happen to individual. They are binary. Analytic alternatives such as `T-test`, `ANOVA` , `linear models` comparing survival time doesn't incorporate event component. Logistic regression or other binomial analysis of event (yes/no) doesn't incorporate time component. In order to incorporate both component at the same time, there is different analytical approach which is **Survival Analysis**. The different examples of survival analysis problems are:\n\n-   Leukemia patients/time in remission (weeks)\n\n-   Heart transplants/time until death (months)\n\n-   Disease-free cohort/time until heart disease (years)\n\n## Censoring\n\nCensoring occurs when some information about individual survival time is known, but exact survival time is not known.It can happen: - when study ended before study participants experienced an event - loss to follow up - participants withdraw from the study\n\nWe should not discard the censored data and if we do, we are ignoring the partial information available on survival.\n\n![](Pictures/survival_pic1.png)\n\n### Types\n\nThere are three types of censoring\n\n-   **Right Censoring:** It occurs when a true survival time is greater than or equal to the observed survival time.\n\n-   **Left Censoring**: It occurs when a true survival time is less than or equal to the observed survival time.\n\n-   **Interval censoring**: It occurs when a true survival time lies within the know interval but exact time is not known.\n\n### **Assumptions of censoring:**\n\nThere are three assumptions of censoring that needed to be considered during survival data analysis.\n\n-   **Independent censoring:** Within any subgroup of interest, the subjects who are censored at time t should be representative of all the subjects in that subgroup who remained at risk at time t with respect to their survival experience. In other words, censoring is independent if it is random within any subgroup of interest.\n\n-   **Random censoring:** Subjects who are censored at time t should be representative of all the study subjects who remained at risk at time t with respect to their survival experience\n\n-   **Non-informative censoring:** It occurs if the distribution of survival times provides no information about the distribution of censorship times, and vice versa. Otherwise, the censoring is informative. If more than 40% patients in the treatment arm dropped from the study, then censoring is informative about the side effects of the treatment.\n\n## Data structure for survival data analysis\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# install.packages(\"survival\")\nlibrary(survival)\n\n# cancer data \ndata(\"cancer\")\n\nhead(lung)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>   inst time status age sex ph.ecog ph.karno pat.karno meal.cal wt.loss\n#> 1    3  306      2  74   1       1       90       100     1175      NA\n#> 2    3  455      2  68   1       0       90        90     1225      15\n#> 3    3 1010      1  56   1       0       90        90       NA      15\n#> 4    5  210      2  57   1       1       90        60     1150      11\n#> 5    1  883      2  60   1       0      100        90       NA       0\n#> 6   12 1022      1  74   1       1       50        80      513       0\n```\n\n\n:::\n:::\n\n\n## Mathematical functions for survival analysis\n\nThere are two mathematical functions for survival analysis:\n\n-   Survivorship Function, `S(t)`\n\n-   Hazard Function, `h(t)`\n\n![](Pictures/survival%20curve_pic2.png)\n\n### **Survivor function**\n\nThe survivor function `S(t)` gives the probability that a person survives longer than some specified time `t`. That is, `S(t)` gives the probability that the random variable `T` exceeds the specified time `t`. The characteristics of survivor function are:\n\n-   non-increasing\n\n-   At time `t = 0, S(t) = S(0) = 1`(probability of surviving past time 0 is 1)\n\n-   At time `t = infinity, S(t) = S(infinity) = 0`\n\n-   When using actual data graphs are typically step functions. Because the study period is never infinite, it is possible that not everyone studied experiences the event. The estimated survivor function may not go all the way to zero at the end of the study.\n\n### **Hazard function**\n\nHazard function `h(t)` measures the instantaneous potential per unit time for the event to occur, given that the individual has survived up to time t. While the survivor function focuses on not failing, the hazard function focuses on failing, that is, on the event occurring. In some sense, the hazard function can be considered as giving the opposite side of the information given by the survivor function. Some characteristics of hazard function are\n\n-   It is always non-negative\n\n-   It has no upper bound\n\n-   Exponential model, Weibull, and log-normal are some mathematical forms of hazard functions.\n\n### **Cummulative hazard**, `H(t)`:\n\nIt describes the accumulated risk up to time `t`.\n\n$$\nH(t) = \\int_{0}^{t} h(u) d(u)\n$$\n\nThe expression of survival function in terms of hazard functions:\n\n$$\nS(t) =\\exp \\left [-\\int_{0}^{t} h(u) du\\right]\n$$\n\nThe expression of hazard function in terms of survivor function:\n\n$$\nh(t) = - \\left[ \\frac{dS(t) /dt}{S(t)} \\right]\n$$\n\n## Kaplan-Meier Method\n\nThe survivor function, S(t) gives the probability that an individual survives longer than a specified time t. In practice, real data are subject to finite sample size and random variation, so the true survivor function must be estimated from observed data. One approach is to fit a parametric model, which imposes a predefined mathematical form on the data to produce a smooth curve. This offers precision but relies on strong distributional assumptions that may not hold in real practice. A non-parametric alternative is the Kaplan-Meier method, which requires fewer assumptions and allows for a more flexible curve shape. Rather than forcing the data into a fixed structure, the **Kaplan-Meier estimator** let the data \"speak for itself.\"\n\n### The Product-Limit Estimator\n\nThe Kaplan-Meier (KM) estimator is also called the **product-limit estimator**, because it is calculated by multiplying together a series of conditional survival probabilities. Suppose there are $k$ distinct observed event times in a sample, ordered as $t_{(1)} < t_{(2)} < \\dots < t_{(k)}$. At each event time $t_{(j)}$:\n\n-   $n_j$ = the number of individuals **at risk** just before $t_{(j)}$ (i.e., still under observation and event-free)\n-   $d_j$ = the number of individuals who **have the event** at $t_{(j)}$\n\nThe KM estimator of the survivor function is:\n\n$$\n\\hat{S}(t) = \\prod_{j:\\, t_{(j)} \\le t} \\left(1 - \\frac{d_j}{n_j}\\right)\n$$\n\nIn words: the estimated probability of surviving past time $t$ is the product, over every event time up to and including $t$, of the conditional probability of surviving that event time given survival up to it. Individuals who are censored are not counted as events, but they are removed from the risk set at the time they are censored. This is precisely how the KM method incorporates the partial information contributed by censored subjects instead of discarding it.\n\n**Worked example:** Let us consider a small 7-subject data set which is as below:\n\n+---------+------+-----------------------------+\n| Subject | Time | **Status**                  |\n|         |      |                             |\n|         |      | ***1: Death/ 0: Censored*** |\n+=========+======+=============================+\n| A       | 5    | 0                           |\n+---------+------+-----------------------------+\n| B       | 13   | 1                           |\n+---------+------+-----------------------------+\n| C       | 6    | 0                           |\n+---------+------+-----------------------------+\n| D       | 5    | 0                           |\n+---------+------+-----------------------------+\n| E       | 15   | 0                           |\n+---------+------+-----------------------------+\n| F       | 20   | 1                           |\n+---------+------+-----------------------------+\n| G       | 18   | 1                           |\n+---------+------+-----------------------------+\n\n**Step-1:** Order the data by time\n\n| Subject | Time (in month) | **Status,** *1: Death/ 0: Censored* |\n|---------|-----------------|-------------------------------------|\n| A       | 5               | 0                                   |\n| D       | 5               | 0                                   |\n| C       | 6               | 0                                   |\n| B       | 13              | 1                                   |\n| E       | 15              | 0                                   |\n| G       | 18              | 1                                   |\n| F       | 20              | 1                                   |\n\n**Step-2:** Determine the number of subject at risk in the given time, number of events at that time. Calculate the probability of event in the risk set by using $d_j/n_j$ in column 4. There after, calculate survival probability by substracting the probability of event from 1 like in column 5. At the end, estimate total survival probability by multiplying survival probabilities from column 5.\n\n+----------------+---------------+--------------+-----------+--------------------------------+-----------------------+\n| Time $t_{(j)}$ | At risk $n_j$ | Events $d_j$ | $d_j/n_j$ | survival proportion$1-d_j/n_j$ | cummulative survival, |\n|                |               |              |           |                                |                       |\n|                |               |              |           |                                | $\\hat{S}(t)$          |\n+:==============:+:=============:+:============:+:=========:+:==============================:+:=====================:+\n| 0              | 5             | 0            | 0         | 1.000                          | 1.000                 |\n+----------------+---------------+--------------+-----------+--------------------------------+-----------------------+\n| 13             | 4             | 1            | 0.25      | 0.75                           | 0.75                  |\n+----------------+---------------+--------------+-----------+--------------------------------+-----------------------+\n| 18             | 2             | 1            | 0.50      | 0.50                           | 0.375                 |\n+----------------+---------------+--------------+-----------+--------------------------------+-----------------------+\n| 20             | 1             | 1            | 1         | 0                              | 0                     |\n+----------------+---------------+--------------+-----------+--------------------------------+-----------------------+\n\nCensored observations (A and D at month 5, C at 6 months, and E at 15 months) reduce the risk set but do not themselves produce a drop in the survival curve. The curve only steps down at observed event times.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(survival)\n\ndf_km <- data.frame(\n  subject = c(\"A\", \"B\", \"C\", \"D\", \"E\", \"F\", \"G\"),\n  time    = c(5,5, 6, 13, 15, 18,20),\n  status  = c(0, 0, 0,1, 0, 1,1)   # 1 = event (death), 0 = censored\n)\n\nfit_km <- survfit(Surv(time, status) ~ 1, data = df_km)\nsummary(fit_km)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> Call: survfit(formula = Surv(time, status) ~ 1, data = df_km)\n#> \n#>  time n.risk n.event survival std.err lower 95% CI upper 95% CI\n#>    13      4       1    0.750   0.217       0.4259            1\n#>    18      2       1    0.375   0.286       0.0839            1\n#>    20      1       1    0.000     NaN           NA           NA\n```\n\n\n:::\n\n```{.r .cell-code}\nplot(fit_km, xlab = \"Follow-up time (months)\", ylab = \"Survival probability\",\n     main = \"Kaplan-Meier Curve\", conf.int = FALSE, mark.time = TRUE)\n```\n\n::: {.cell-output-display}\n![](16_Survival_analysis_files/figure-html/unnamed-chunk-2-1.png){fig-align='center' width=85%}\n:::\n:::\n\n\n### Standard Error and Confidence Interval for S(t)\n\nBecause $\\hat{S}(t)$ is estimated from a finite, censored sample, it has sampling variability that should be reported alongside the point estimate. The most widely used variance estimator is **Greenwood's formula** [@greenwood1926], derived using a Taylor series (delta method) approximation:\n\n$$\n\\widehat{Var}\\left[\\hat{S}(t)\\right] = \\left[\\hat{S}(t)\\right]^2 \\sum_{t_{(j)} \\le t} \\frac{d_j}{n_j(n_j - d_j)}\n$$\n\nA large-sample confidence interval for $S(t)$ follows directly:\n\n$$\n\\hat{S}(t) \\pm z_{1-\\alpha/2} \\sqrt{\\widehat{Var}\\left[\\hat{S}(t)\\right]}\n$$\n\nIn practice, software typically applies a log or complementary log-log transformation before constructing the interval and then back-transforms, which keeps the bounds within $[0,1]$. In R, `survfit()` computes Greenwood's standard errors and confidence limits automatically:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfit_km_ci <- survfit(Surv(time, status) ~ 1, data = df_km, conf.type = \"log-log\")\nsummary(fit_km_ci)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> Call: survfit(formula = Surv(time, status) ~ 1, data = df_km, conf.type = \"log-log\")\n#> \n#>  time n.risk n.event survival std.err lower 95% CI upper 95% CI\n#>    13      4       1    0.750   0.217        0.128        0.961\n#>    18      2       1    0.375   0.286        0.011        0.808\n#>    20      1       1    0.000     NaN           NA           NA\n```\n\n\n:::\n\n```{.r .cell-code}\nplot(fit_km_ci, xlab = \"Follow-up time (months)\", ylab = \"Survival probability\",\n     main = \"Kaplan-Meier Curve with 95% CI\", conf.int = TRUE, mark.time = TRUE, col = \"steelblue\")\n```\n\n::: {.cell-output-display}\n![](16_Survival_analysis_files/figure-html/unnamed-chunk-3-1.png){fig-align='center' width=85%}\n:::\n:::\n\n\n## Comparing Survival Between Two or More Groups: The Log-Rank Test\n\nA common goal in survival analysis is to compare the survival experience of two or more groups defined by an exposure, treatment, or other categorical factor. This is done by computing a separate KM curve for each group and then testing formally whether the underlying survivor functions differ.\n\n**Hypotheses:**\n\n-   $H_0$: The survivor functions are identical across groups\n-   $H_A$: The survivor functions differ across groups\n\nAt each distinct event time across the combined data, we can construct a table of observed events and, under $H_0$, the number of events **expected** in each group (proportional to that group's share of the risk set at that time). Summing observed minus expected events for a group across all event times, and appropriately weighting by the variance, yields the **log-rank test statistic**:\n\n$$\n\\chi^2 = \\frac{\\left(\\sum_j (O_{1j} - E_{1j})\\right)^2}{\\sum_j Var(O_{1j} - E_{1j})} \\sim \\chi^2_{(g-1)}\n$$\n\nwhere $g$ is the number of groups being compared. Under $H_0$, this statistic follows a chi-square distribution with $g - 1$ degrees of freedom (df).\n\n**Worked example.** In a classical clinical trial, leukemia patients were randomized to a 6-MP treatment arm versus placebo. In this study, researcher wanted to answer whether there is difference in survival between patients with maintenance of chemotherapy versus no maintenance of chemotherapy. The dataset is as follows:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndata(cancer, package = \"survival\")\ndata(aml)\nhead(aml)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>   time status          x\n#> 1    9      1 Maintained\n#> 2   13      1 Maintained\n#> 3   13      0 Maintained\n#> 4   18      1 Maintained\n#> 5   23      1 Maintained\n#> 6   28      0 Maintained\n```\n\n\n:::\n:::\n\n\nIn order to answer the question, we have to perform log rank test. The 5 step hypothesis test is as follows:\n\n**Step 1: Set up Hypothesis**\n\n*Ho: Two survival functions of chemotherapy Maintained and Not maintained are identical.*\n\n*Ha: Two survival functions of of Maintained and Not maintained differ*\n\n**Step 2: Level of significance**\n\n$$\\alpha=0.05$$\n\n**Step 3: Selection of test statistics**\n\nSince, two survival curve between chemotherapy Maintained and Not maintained are to be compared, log rank test is the appropriate test to perform. The formula for log rank test statistics is\n\n$$\n\\chi^2 = \\frac{\\left(\\sum_j (O_{1j} - E_{1j})\\right)^2}{\\sum_j Var(O_{1j} - E_{1j})} \\sim \\chi^2_{(df=1)}\n$$\n\n**Step 4: Calculation of test statistics**\n\nR was used to perform analysis. `survdiff()` in R performs the log-rank test directly and reports the chi-square statistic, degrees of freedom, and p-value. The output of the analysis is as follows:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfit_aml <- survfit(Surv(time, status) ~ x, data = aml)\nfit_aml\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> Call: survfit(formula = Surv(time, status) ~ x, data = aml)\n#> \n#>                  n events median 0.95LCL 0.95UCL\n#> x=Maintained    11      7     31      18      NA\n#> x=Nonmaintained 12     11     23       8      NA\n```\n\n\n:::\n\n```{.r .cell-code}\nsurvdiff(Surv(time, status) ~ x, data = aml)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> Call:\n#> survdiff(formula = Surv(time, status) ~ x, data = aml)\n#> \n#>                  N Observed Expected (O-E)^2/E (O-E)^2/V\n#> x=Maintained    11        7    10.69      1.27       3.4\n#> x=Nonmaintained 12       11     7.31      1.86       3.4\n#> \n#>  Chisq= 3.4  on 1 degrees of freedom, p= 0.07\n```\n\n\n:::\n\n```{.r .cell-code}\nplot(fit_aml, col = c(\"blue\", \"red\"), lty = 1:2,\n     xlab = \"Weeks\", ylab = \"Survival probability\",\n     main = \"Kaplan-Meier by Maintenance Therapy (aml data)\")\nlegend(\"topright\", legend = levels(aml$x), col = c(\"blue\", \"red\"), lty = 1:2)\n```\n\n::: {.cell-output-display}\n![](16_Survival_analysis_files/figure-html/unnamed-chunk-5-1.png){fig-align='center' width=85%}\n:::\n:::\n\n\n**Manual calculation**\n\n**Step 1:** Arrange the data in as in the table below. First get all the time points in assending order. Then, for each time point get the number of events (m), number of censored observation and number of subjects at risk (n).\n\n| Time |   | **Maintained** |   |   | **Not maintained** |   |\n|----|----|----|----|----|----|----|\n|  | **Censored (k1)** | **Events (m1)** | **At Risk (n1)** | **Censored (k2)** | **Events (m2)** | **At Risk (n2)** |\n| 5 |  |  | 11 |  | 2 | 12 |\n| 8 |  |  | 11 |  | 2 | 10 |\n| 9 |  | 1 | 11 |  |  | 8 |\n| 12 |  |  | 10 |  | 1 | 8 |\n| 13 | 1 | 1 | 10 |  |  | 7 |\n| 16 |  |  | 8 | 1 |  | 7 |\n| 18 |  | 1 | 8 |  |  | 6 |\n| 23 |  | 1 | 7 |  | 1 | 6 |\n| 27 |  |  | 6 |  | 1 | 5 |\n| 28 | 1 |  | 6 |  |  | 4 |\n| 30 |  |  | 5 |  | 1 | 4 |\n| 31 |  | 1 | 5 |  |  | 3 |\n| 33 |  |  | 4 |  | 1 | 3 |\n| 34 |  | 1 | 4 |  |  | 2 |\n| 43 |  |  | 3 |  | 1 | 2 |\n| 45 | 1 |  | 3 |  | 1 | 1 |\n| 48 |  | 1 | 2 |  |  | 0 |\n| 161 | 1 |  | 1 |  |  | 0 |\n\nStep-2: Estimate expected number of events for each group using the formula below$E_1=\\frac{n_1}{(n _1+n_2)}(m_1+m_2)$\n\n$E_2=\\frac{n_2}{(n_1+n_2)}(m_1+m_2)$ .\n\n$Variance=\\sum Var=\\sum\\frac{n_1*n_2 (m_1+m_2)(n_1+n_2-m_1-m_2)}{(n_1+n_2)^2 (n_1+n_2-1)}$\n\n|      Time |   E₁ |   E₂ | n₁n₂ | n1+n2 | m1+m2 |      Var |     O₁−E₁ |    O₂−E₂ |\n|----------:|-----:|-----:|-----:|------:|------:|---------:|----------:|---------:|\n|         5 | 0.96 | 1.04 |  132 |    23 |     2 |     0.48 |     -0.96 |     0.96 |\n|         8 | 1.05 | 0.95 |  110 |    21 |     2 |     0.47 |     -1.05 |     1.05 |\n|         9 | 0.58 | 0.42 |   88 |    19 |     1 |     0.24 |      0.42 |    -0.42 |\n|        12 | 0.56 | 0.44 |   80 |    18 |     1 |     0.25 |     -0.56 |     0.56 |\n|        13 | 0.59 | 0.41 |   70 |    17 |     1 |     0.24 |      0.41 |    -0.41 |\n|        16 | 0.00 | 0.00 |   56 |    15 |     0 |     0.00 |      0.00 |     0.00 |\n|        18 | 0.57 | 0.43 |   48 |    14 |     1 |     0.24 |      0.43 |    -0.43 |\n|        23 | 1.08 | 0.92 |   42 |    13 |     2 |     0.46 |     -0.08 |     0.08 |\n|        27 | 0.55 | 0.45 |   30 |    11 |     1 |     0.25 |     -0.55 |     0.55 |\n|        28 | 0.00 | 0.00 |   24 |    10 |     0 |     0.00 |      0.00 |     0.00 |\n|        30 | 0.56 | 0.44 |   20 |     9 |     1 |     0.25 |     -0.56 |     0.56 |\n|        31 | 0.63 | 0.38 |   15 |     8 |     1 |     0.23 |      0.38 |    -0.38 |\n|        33 | 0.57 | 0.43 |   12 |     7 |     1 |     0.24 |     -0.57 |     0.57 |\n|        34 | 0.67 | 0.33 |    8 |     6 |     1 |     0.22 |      0.33 |    -0.33 |\n|        43 | 0.60 | 0.40 |    6 |     5 |     1 |     0.24 |     -0.60 |     0.60 |\n|        45 | 0.75 | 0.25 |    3 |     4 |     1 |     0.19 |     -0.75 |     0.75 |\n|        48 | 1.00 | 0.00 |    0 |     2 |     1 |     0.00 |      0.00 |     0.00 |\n|       161 | 0.00 | 0.00 |    0 |     1 |     0 |          |      0.00 |     0.00 |\n| **Total** |      |      |      |       |       | **4.01** | **−3.69** | **3.69** |\n\nLog rank test value is calculated using the formula\n\n$$\nLog  rank= \\frac{(O-E)^2}{Var} = 3.69^2/4.01 =3.4\n$$\n\n**Step 5: Decision and conclusion**\n\nSince p-value is 0.07 which is greater than 0.05 and log rank statistics is 3.4 which is less than critical value of 3.84, we failed to reject the null hypothesis. Thus we conclude that there is no significant difference in two survival curve for chemotherapy Maintained and Not maintained groups.\n\n## Median Survival Time\n\nAccording to National Cancer Institute, **median survival time** is the length of time from diagnosis (or start of treatment) at which half of the patients in a group are still alive[@definiti2011]. It is directly read from the KM curve as the time at which $\\hat{S}(t) = 0.50$ is first crossed or first achieved. Because it does not require assuming the entire tail of the distribution is observed, median survival is often more useful and more robust to report than mean survival time in the presence of censoring.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Plot\nplot(fit_aml,\n     col = c(\"blue\", \"red\"),\n     lty = 1:2,\n     lwd = 2,\n     xlab = \"Weeks\",\n     ylab = \"Survival probability\",\n     main = \"Kaplan-Meier by Maintenance Therapy\")\n\nlegend(\"topright\",\n       legend = levels(aml$x),\n       col = c(\"blue\", \"red\"),\n       lty = 1:2,\n       lwd = 2,\n       bty = \"n\")\n\n# Horizontal line at 50% survival\nabline(h = 0.5, lty = 3, col = \"darkgray\")\n\n# Median survival times\nmed <- summary(fit_aml)$table[, \"median\"]\n\n# Add vertical lines\nabline(v = med[1], col = \"blue\", lty = 3)\nabline(v = med[2], col = \"red\", lty = 3)\n\n# Label median survival times\ntext(med[1]+0.5, 0.05,\n     labels = paste0(\"Median = \", med[1]),\n     col = \"blue\",\n     pos = 4,)\n\ntext(med[2]-30, 0.05,\n     labels = paste0(\"Median = \", med[2]),\n     col = \"red\",\n     pos = 4)\n```\n\n::: {.cell-output-display}\n![](16_Survival_analysis_files/figure-html/unnamed-chunk-6-1.png){fig-align='center' width=85%}\n:::\n:::\n\n\nIf $\\hat{S}(t)$ never falls to 0.50 during the observation period due to early end of follow up, or treatment is highly effective, median survival is **not estimable** and is typically reported as **\"not reached\"**. A 95% confidence interval for median survival can also be obtained from the KM curve.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfit_aml   # printing a survfit object reports median survival and its 95% CI directly\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> Call: survfit(formula = Surv(time, status) ~ x, data = aml)\n#> \n#>                  n events median 0.95LCL 0.95UCL\n#> x=Maintained    11      7     31      18      NA\n#> x=Nonmaintained 12     11     23       8      NA\n```\n\n\n:::\n:::\n\n\nThe quartiles of survival time divide the estimated survival experience into four equal parts based on the Kaplan–Meier survival function. They are defined as the times at which the estimated survival probability first reaches specific levels.\n\n-   **First quartile (Q1):** The time at which the estimated survival probability first falls to **0.75**. At this point, approximately 25% of participants have experienced the event.\n\n-   **Median survival time (Q2):** The time at which the estimated survival probability first falls to **0.50**. By this time, approximately 50% of participants have experienced the event.\n\n-   **Third quartile (Q3):** The time at which the estimated survival probability first falls to **0.25**. By this time, approximately 75% of participants have experienced the event.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nquantile(fit_aml)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> $quantile\n#>                 25 50 75\n#> x=Maintained    18 31 48\n#> x=Nonmaintained  8 23 33\n#> \n#> $lower\n#>                 25 50 75\n#> x=Maintained    13 18 34\n#> x=Nonmaintained  5  8 27\n#> \n#> $upper\n#>                 25 50 75\n#> x=Maintained    NA NA NA\n#> x=Nonmaintained 30 NA NA\n```\n\n\n:::\n:::\n\n\n**Interpretation**: The KM estimate indicates that 25% of patients experienced the event by 18 weeks(95%CI: 13, NA) in maintained group, and by 8 weeks (95% CI: 5 to 30) in not maintained group. Similarly, it indicates that 50% of patients experienced the event by 31 weeks(95%CI: 18, NA) in maintained group, and by 23 weeks (95% CI: 8 to NA) in not maintained group. Similarly, it indicates that 75% of patients experienced the event by 48 weeks(95%CI: 34, NA) in maintained group, and by 33 weeks (95% CI: 27 to NA) in not maintained group.\n\n## The Cox Proportional Hazards Model\n\n### Limitations of the Kaplan-Meier Approach\n\nThe KM method and log-rank test are extremely useful, but they have important limitations:\n\n-   They require **categorical** predictors (grouping variables)\n-   They do not **control for covariates** (confounding cannot be adjusted for)\n-   They cannot accommodate **time-dependent** variables\n\nOrdinary linear regression is not a solution either, because it requires a continuous, uncensored outcome ranging over $(-\\infty, \\infty)$, not appropriate for time-to-event data with censoring.\n\n### Sir David Cox and the Proportional Hazards Model\n\nIn 1972, the English statistician Sir David Cox introduced the proportional hazards assumption and, with it, a regression model for survival data that focuses on the **hazard function** rather than on survival time directly [@cox1972]. The Cox model is among the most heavily cited papers in all of statistics, and the **Cox Proportional Hazards (PH) model** remains the most widely used regression approach for time-to-event data in the health sciences.\n\nThe model is built by allowing the hazard for an individual to depend on a baseline hazard function multiplied by an exponentiated linear combination of covariates:\n\n$$\nh(t, \\mathbf{X}) = h_0(t) \\exp\\left(\\beta_1 X_1 + \\beta_2 X_2 + \\dots + \\beta_p X_p\\right)\n$$\n\nTwo features of this formula are essential:\n\n-   $h_0(t)$, the **baseline hazard function**, depends on $t$ but not on the $X$'s. It represents the hazard for an individual with all covariates equal to zero, and its functional form is left **completely unspecified**.\n-   The exponential term $\\exp(\\sum \\beta_i X_i)$ depends on the $X$'s but **not on** $t$ . These are called time-independent covariates, and their effect on the hazard is assumed constant over time.\n\nBecause $h_0(t)$ is not specified, the Cox model is called **semi-parametric**: some structure is assumed for how covariates act on the hazard, but no particular distributional form is imposed on survival time itself. This is in contrast to a fully **parametric** model, whose functional form is completely specified except for the values of unknown parameters (discussed later in this chapter). Despite leaving $h_0(t)$ unspecified, the Cox model is remarkably robust regression coefficients, hazard ratios, and adjusted survival curves obtained from it closely approximate results from the correctly specified parametric model in a wide range of situations.\n\n### Assumptions of the Proportional Hazards Model\n\n1.  **Independent observations** across subjects\n2.  **Independent censoring**\n3.  **Proportional hazards**: The hazard for one individual is proportional to the hazard for any other individual, and this proportionality constant does not change over time\n\n### Fitting the Model: Maximum Likelihood\n\nThe regression coefficients $\\beta_1, \\dots, \\beta_p$ are estimated using **maximum likelihood**, maximizing a *partial* likelihood function that depends only on the ordering of event times and the composition of the risk sets, not on the unspecified baseline hazard. This is analogous to how logistic regression coefficients are estimated. Because the baseline hazard cancels out of this partial likelihood, valid inference on the $\\beta$'s is possible without ever estimating $h_0(t)$.\n\n### The Hazard Ratio\n\nSuppose we want to compare the hazard for two individuals (or groups) with covariate vectors $\\mathbf{X}^*$ and $\\mathbf{X}$. Taking the ratio of their hazards, the baseline hazard $h_0(t)$ cancels out entirely:\n\n$$\n\\frac{h(t, \\mathbf{X}^*)}{h(t, \\mathbf{X})} = \\frac{h_0(t)\\exp(\\sum \\beta_i X_i^*)}{h_0(t)\\exp(\\sum \\beta_i X_i)} = \\exp\\left[\\sum_i \\beta_i (X_i^* - X_i)\\right]\n$$\n\nThis ratio, the **hazard ratio (HR)**, is the primary measure of association reported from a Cox model. For a single binary covariate coded 0/1, comparing $X_1^*=1$ to $X_1=0$ gives simply $HR = \\exp(\\beta_1)$. For a continuous covariate, $HR = \\exp(\\beta_1)$ represents the hazard ratio associated with a **one-unit increase** in that covariate, holding all other covariates constant.\n\n**Interpreting** $\\beta$:\n\n-   $\\beta_1$ is the increase in the *log* hazard per one-unit increase in $X_1$\n-   $\\exp(\\beta_1)$ is the hazard ratio per one-unit increase in $X_1$\n-   $\\beta_1 > 0$ (equivalently $HR>1$): increasing $X_1$ is associated with **increased** hazard (worse survival)\n-   $\\beta_1 < 0$ (equivalently $HR<1$): increasing $X_1$ is associated with **decreased** hazard (better survival)\n\n**Worked example (single binary predictor).** For lung cancer data(228 patients), fitting $h(t)/h_0(t) = \\exp(\\beta_1 X_1)$ with $X_1=1$ for Male produces $\\hat\\beta_1 = -0.531$, so $\\widehat{HR} = \\exp(-0.531) = 0.588$ (95% CI: 0.42, 0.82), $\\chi^2=10.63$, $p=0.001$. **Interpretation:** the hazard of death for female patients is 41% lower compared to male patients.\n\n**Worked example (multiple covariates).** In a lung cancer data, the hazard of death among female compared to male after adjusting for age and ph-ecog was determined. , fitting $h(t)/h_0(t) = \\exp(\\beta_1 \\text{Sex} + \\beta_2 \\text{Age}+\\beta_3 \\text{Ph.ecog})$ yields $\\widehat{HR}_{sex} = \\exp(-0.55) = 0.58$ (95% CI: 0.41, 0.80) and $\\widehat{HR}_{age} = \\exp(0.011) = 1.01$ (95% CI: 0.99 to 1.03) and $\\widehat{HR}_{Ph.ecog} = \\exp(0.46) = 1.59$ (95% CI: 1.27 to 1.99).\n\n**Interpretation:** After adjustment for age and ECOG performance status, females had a significantly lower hazard of death than males (HR = 0.58, 95% CI: 0.41 to 0.80). Each additional year of age was associated with an estimated 1% increase in the hazard of death (HR = 1.01, 95% CI: 0.99 to 1.03), although this association was not statistically significant. In contrast, each one-unit increase in ECOG performance status was associated with a 59% higher hazard of death (HR = 1.59, 95% CI: 1.27 to 1.99), indicating that worse performance status is an important predictor of mortality after controlling for age and sex.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndata(cancer)\nhead(lung)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>   inst time status age sex ph.ecog ph.karno pat.karno meal.cal wt.loss\n#> 1    3  306      2  74   1       1       90       100     1175      NA\n#> 2    3  455      2  68   1       0       90        90     1225      15\n#> 3    3 1010      1  56   1       0       90        90       NA      15\n#> 4    5  210      2  57   1       1       90        60     1150      11\n#> 5    1  883      2  60   1       0      100        90       NA       0\n#> 6   12 1022      1  74   1       1       50        80      513       0\n```\n\n\n:::\n\n```{.r .cell-code}\n# cleaning\nlung$sex <- factor(lung$sex, levels = c(1,2), labels = c(\"Male\", \"Female\"))\nlung$status <- ifelse(lung$status==1, 0, 1)\n\n# Cox model 1\ncox1 <- coxph(Surv(time, status) ~ sex, data = lung)\nsummary(cox1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> Call:\n#> coxph(formula = Surv(time, status) ~ sex, data = lung)\n#> \n#>   n= 228, number of events= 165 \n#> \n#>              coef exp(coef) se(coef)      z Pr(>|z|)   \n#> sexFemale -0.5310    0.5880   0.1672 -3.176  0.00149 **\n#> ---\n#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n#> \n#>           exp(coef) exp(-coef) lower .95 upper .95\n#> sexFemale     0.588      1.701    0.4237     0.816\n#> \n#> Concordance= 0.579  (se = 0.021 )\n#> Likelihood ratio test= 10.63  on 1 df,   p=0.001\n#> Wald test            = 10.09  on 1 df,   p=0.001\n#> Score (logrank) test = 10.33  on 1 df,   p=0.001\n```\n\n\n:::\n\n```{.r .cell-code}\n# cox model 2\ncox2 <- coxph(Surv(time, status) ~ age + sex + ph.ecog, data = lung)\nsummary(cox2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> Call:\n#> coxph(formula = Surv(time, status) ~ age + sex + ph.ecog, data = lung)\n#> \n#>   n= 227, number of events= 164 \n#>    (1 observation deleted due to missingness)\n#> \n#>                coef exp(coef)  se(coef)      z Pr(>|z|)    \n#> age        0.011067  1.011128  0.009267  1.194 0.232416    \n#> sexFemale -0.552612  0.575445  0.167739 -3.294 0.000986 ***\n#> ph.ecog    0.463728  1.589991  0.113577  4.083 4.45e-05 ***\n#> ---\n#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n#> \n#>           exp(coef) exp(-coef) lower .95 upper .95\n#> age          1.0111     0.9890    0.9929    1.0297\n#> sexFemale    0.5754     1.7378    0.4142    0.7994\n#> ph.ecog      1.5900     0.6289    1.2727    1.9864\n#> \n#> Concordance= 0.637  (se = 0.025 )\n#> Likelihood ratio test= 30.5  on 3 df,   p=1e-06\n#> Wald test            = 29.93  on 3 df,   p=1e-06\n#> Score (logrank) test = 30.5  on 3 df,   p=1e-06\n```\n\n\n:::\n:::\n\n\nThe `exp(coef)` column in the R output is precisely the estimated hazard ratio for each covariate, with the associated 95% confidence interval given in the `summary()` output, and the Wald test p-value indicating whether that covariate is significantly associated with survival after adjusting for the others in the model.\n\n## Assessing the Proportional Hazards Assumption\n\nBecause the Cox model is *named* after the proportional hazards assumption, this assumption deserves careful evaluation rather than being taken for granted. Three general approaches are used to check it.\n\n### Approach 1: Graphical Evaluation\n\n**Log-log survival curves.** A log-log survival curve is obtained by taking the natural log of the KM survival estimate, twice: $-\\ln[-\\ln \\hat{S}(t)]$ (we negate the first log because probabilities are always $\\le 1$, making $\\ln \\hat S(t)$ negative). If the PH assumption holds for a categorical predictor, the log-log curves for its categories should be roughly **parallel**. Non-parallel or crossing curves suggest violation of assumption.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplot(survfit(Surv(time, status) ~ sex, data = lung), fun = \"cloglog\",\n     xlab = \"Time in days (log scale)\", ylab = \"log(-log(S(t)))\",\n     col = c(\"blue\", \"red\"), main = \"Log-log Survival Curves by Sex (lung data)\")\nlegend(\"bottomright\", legend = c(\"Male\", \"Female\"), col = c(\"blue\", \"red\"), lty = 1)\n```\n\n::: {.cell-output-display}\n![](16_Survival_analysis_files/figure-html/unnamed-chunk-10-1.png){fig-align='center' width=85%}\n:::\n:::\n\n\n**Observed vs. expected plots** are a related graphical device: fit a Cox model containing the predictor of interest, obtain \"expected\" survival curves for each category from the fitted model, and overlay them on the \"observed\" (KM) curves for the same categories. Close agreement supports the PH assumption; substantial, systematic divergence suggests a violation.\n\nBoth graphical approaches share a common weakness: judging \"parallel enough\" or \"close enough\" is inherently subjective. Kleinbaum and Klein recommend assuming PH is reasonable unless the evidence against it is fairly convincing.\n\n### Approach 2: Goodness-of-Fit (Schoenfeld Residuals)\n\nSchoenfeld (1982) proposed a formal hypothesis test based on residuals which is now called **Schoenfeld residuals**. It is defined for each predictor, for each subject who experiences an event. If the PH assumption holds for a given covariate, its Schoenfeld residuals should show **no systematic relationship with time**. The test correlates the scaled Schoenfeld residuals with (a function of) survival time; under $H_0$ (hazards proportional) this correlation is zero.\n\n-   $H_0$: hazards are proportional\n-   $H_1$: hazards are not proportional\n-   Test statistic follows a $\\chi^2$ distribution with 1 df per covariate\n\nIn R, the entire procedure for every covariate in a fitted Cox model plus a global test is implemented directly by `cox.zph()` function.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nzph2 <- cox.zph(cox2)\nzph2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>         chisq df    p\n#> age     0.188  1 0.66\n#> sex     2.305  1 0.13\n#> ph.ecog 2.054  1 0.15\n#> GLOBAL  4.464  3 0.22\n```\n\n\n:::\n\n```{.r .cell-code}\nplot(zph2)\n```\n\n::: {.cell-output-display}\n![](16_Survival_analysis_files/figure-html/unnamed-chunk-11-1.png){fig-align='center' width=85%}\n:::\n\n::: {.cell-output-display}\n![](16_Survival_analysis_files/figure-html/unnamed-chunk-11-2.png){fig-align='center' width=85%}\n:::\n\n::: {.cell-output-display}\n![](16_Survival_analysis_files/figure-html/unnamed-chunk-11-3.png){fig-align='center' width=85%}\n:::\n:::\n\n\nA small p-value for any row flags a possible PH violation for that covariate (or globally). The accompanying plot shows the scaled Schoenfeld residuals against time with a smoothed trend line. A roughly flat, horizontal trend supports PH, while a clearly sloped or curved trend suggests the covariate's effect changes over time.\n\n### Approach 3: Time-Dependent Covariates\n\nA third approach re-fits the Cox model with an added interaction term between the covariate being assessed and a function of time (e.g., $X \\times t$, or a step/\"Heaviside\" function of time). If this interaction term is statistically significant, the PH assumption is violated for that covariate, its effect on the hazard changes over time. This approach doubles as the foundation for the **extended Cox model**, discussed later in this chapter.\n\n## Model Building: Interaction and Confounding\n\n### Assessing Interaction\n\nA statistical **interaction** (effect modification) is present when the effect of one exposure on the outcome differs across levels of a third variable. In the PH model, because we work with hazard ratios (a multiplicative scale), we are primarily concerned with **multiplicative interaction**. No interaction, on this scale, means:\n\n$$\nHR_{11} = HR_{10} \\times HR_{01}\n$$\n\nThat is, the combined effect of two factors acting together equals the product of their separate effects. This can be tested by adding a product term to the model:\n\n$$\nh(t,\\mathbf{X}) = h_0(t)\\exp(\\beta_1 A + \\beta_2 B + \\beta_3 A{\\times}B), \\qquad H_0: \\beta_3 = 0\n$$\n\nThe interaction coefficient can be tested with a Wald test (from the model output directly) or, preferably, with a **likelihood ratio (LR) test** comparing the full (with interaction) and reduced (without interaction) models:\n\n$$\nF_0 = LR_{reduced} - LR_{full} \\sim \\chi^2_{df}\n$$\n\nStatisticians generally consider the LR test to have better statistical properties than the Wald test for this purpose, though the two usually agree. When an interaction is statistically significant, hazard ratios should be reported *separately* for meaningful values or categories of the effect-modifying variable (or the modifier can be treated as a stratifying variable, see below), rather than reporting a single \"overall\" hazard ratio that obscures the effect modification.\n\n### Assessing Confounding\n\nA **confounder** distorts the observed association between an exposure and outcome because of its own associations with both. Three conditions must all hold for a variable to be a confounder: (1) it must be associated with the outcome, (2) it must be associated with the exposure, and (3) it must **not** be an intermediate step on the causal pathway between exposure and outcome.\n\nFrom the Cox model, we can compare a **crude** hazard ratio (exposure alone) to an **adjusted** hazard ratio (exposure plus the potential confounder):\n\n$$\n\\text{Magnitude of confounding} = \\frac{HR_{crude} - HR_{adjusted}}{HR_{adjusted}} \\times 100\\%\n$$\n\nA common rule of thumb (the **10% rule**) retains a variable in the model as a confounder if adjusting for it changes the exposure hazard ratio by more than 10%. When several potential confounders are being screened, they are typically evaluated one at a time against the fully adjusted model.\n\nIt is worth distinguishing the two phenomena clearly: **confounding** is a distortion of the true association caused by an imbalance in another risk factor, the stratum-specific estimates will be similar to each other but different from the crude estimate. **Effect modification**, by contrast, is a real biological/clinical phenomenon in which the stratum-specific estimates genuinely differ from one another; it should be described and reported, not \"adjusted away.\"\n\n### Model-Building Strategy (E-V-W Framework)\n\nWhen the primary study goal is a valid **exposure–disease (E-D)** association (as opposed to pure outcome prediction), Kleinbaum and Klein recommend a structured strategy rather than automated stepwise procedures:\n\n1.  **Variable specification** designate one exposure of interest ($E$), and classify remaining covariates as potential confounders ($V_1,\\dots,V_p$) and/or potential effect modifiers ($W_1,\\dots,W_p$), based on subject-matter knowledge, prior literature, and (optionally) causal diagrams\n2.  **Check the PH assumption** for each variable\n3.  **Assess interaction** ($E \\times W$ terms), retaining significant ones\n4.  **Assess confounding** among the $V$'s using the 10% rule, in a **hierarchically well-formulated (HWF)** framework. For example: if a higher-order term (like $E{\\times}V_1{\\times}V_2$) is retained, all its lower-order components ($E$, $V_1$, $V_2$, $E{\\times}V_1$, $E{\\times}V_2$, $V_1{\\times}V_2$) must also remain in the model, so that hypothesis tests do not depend arbitrarily on how variables happen to be coded\n\nWhen the goal is instead a good **prediction** model rather than a specific E-D estimate, standard iterative procedures (forward selection, backward elimination, stepwise regression) are more appropriate.\n\n### Evaluating Predictive Accuracy: The C-Statistic\n\nThe **concordance index (C-statistic)**, also known as Harrell's C, measures how well a fitted survival model discriminates between subjects who fail sooner versus later, based on their predicted risk scores $\\hat\\eta_i = \\sum \\hat\\beta_k X_{ik}$. For every comparable pair of subjects, the pair is **concordant** if the subject with the higher risk score has the shorter observed survival time. The C-statistic is the proportion of concordant pairs among all pairs that can be evaluated:\n\n-   $C = 0.5$: no better than chance\n-   $C = 1.0$: perfect discrimination\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Harrels' C index\nconcordance(cox2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> Call:\n#> concordance.coxph(object = cox2)\n#> \n#> n= 227 \n#> Concordance= 0.6371 se= 0.02507\n#> concordant discordant     tied.x     tied.y    tied.xy \n#>      12544       7117        126         28          0\n```\n\n\n:::\n:::\n\n\nBecause heavy censoring can bias the ordinary C-statistic, **Uno's C-statistic** uses inverse probability of censoring weighting (IPCW) and is generally preferred when censoring exceeds roughly 30%. The R-code to calculate Uno's C-statistic is as follows:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n#install.packages(\"survAUC\")\n\nlibrary(survAUC)\n\n# Cox model\ncox1 <- coxph(Surv(time, status) ~ age + sex,\n              data = lung)\n\nUnoC(\n  Surv(lung$time, lung$status),\n  Surv(lung$time, lung$status),\n  predict(cox1, type = \"lp\") # linear predictor\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> [1] 0.5848518\n```\n\n\n:::\n:::\n\n\n## The Stratified Cox Model\n\nWhen one or more categorical covariates clearly violate the PH assumption, but we still want to control for them, the **stratified Cox (SC) model** offers a solution. Suppose $X_1,\\dots,X_p$ satisfy the PH assumption and $Z_1,\\dots,Z_k$ do not. We form a single stratification variable $Z^*$ from combinations of categories of the $Z$'s, and fit:\n\n$$\nh_g(t,\\mathbf{X}) = h_{0g}(t)\\exp\\left(\\sum_i \\beta_i X_i\\right), \\qquad g = 1,\\dots,\\text{(number of strata)}\n$$\n\nEach stratum $g$ is allowed its **own, unspecified baseline hazard function** $h_{0g}(t)$, but the regression coefficients for $X_1,\\dots,X_p$ are assumed to be the **same across strata** .This is the \"no-interaction\" assumption underlying the SC model. Its major advantage is that it lets us **control for** a variable that violates PH; its major limitation is that we can **no longer estimate a hazard ratio for the stratification variable itself**.\n\nThe no-interaction assumption can (and should) be checked with a likelihood ratio test comparing a model that allows separate coefficients per stratum against the common-coefficient stratified model. If interaction is present, it is generally better to fit separate models within each stratum than to force a single stratified Cox model.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndata(veteran)\nhead(veteran)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>   trt celltype time status karno diagtime age prior\n#> 1   1 squamous   72      1    60        7  69     0\n#> 2   1 squamous  411      1    70        5  64    10\n#> 3   1 squamous  228      1    60        3  38     0\n#> 4   1 squamous  126      1    60        9  63    10\n#> 5   1 squamous  118      1    70       11  65    10\n#> 6   1 squamous   10      1    20        5  49     0\n```\n\n\n:::\n\n```{.r .cell-code}\n# check PH assumption first\ncox_v <- coxph(Surv(time, status) ~ trt + age + factor(celltype), data = veteran)\ncox.zph(cox_v)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>                   chisq df     p\n#> trt               0.892  1 0.345\n#> age               1.231  1 0.267\n#> factor(celltype)  9.213  3 0.027\n#> GLOBAL           12.598  5 0.027\n```\n\n\n:::\n\n```{.r .cell-code}\n# stratify on the variable(s) that violate PH (here, illustratively, celltype)\ncox_strat <- coxph(Surv(time, status) ~ trt + age + strata(celltype), data = veteran)\nsummary(cox_strat)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> Call:\n#> coxph(formula = Surv(time, status) ~ trt + age + strata(celltype), \n#>     data = veteran)\n#> \n#>   n= 137, number of events= 128 \n#> \n#>         coef exp(coef) se(coef)     z Pr(>|z|)\n#> trt 0.159202  1.172575 0.203399 0.783    0.434\n#> age 0.002104  1.002106 0.009820 0.214    0.830\n#> \n#>     exp(coef) exp(-coef) lower .95 upper .95\n#> trt     1.173     0.8528    0.7871     1.747\n#> age     1.002     0.9979    0.9830     1.022\n#> \n#> Concordance= 0.522  (se = 0.032 )\n#> Likelihood ratio test= 0.77  on 2 df,   p=0.7\n#> Wald test            = 0.77  on 2 df,   p=0.7\n#> Score (logrank) test = 0.77  on 2 df,   p=0.7\n```\n\n\n:::\n:::\n\n\nIn this formulation, `celltype` no longer produces its own hazard ratio, it defines four separate baseline hazards, one per cell type, while `trt` and `age` retain interpretable, celltype-adjusted hazard ratios.\n\n## The Extended Cox Model for Time-Dependent Covariates\n\n### Time-Dependent Variables\n\nA **time-dependent** variable is one whose value for a given subject can change over the course of follow-up, in contrast to a time-independent variable, which is fixed at baseline. Time-dependent variables arise in two ways:\n\n1.  **Inherently time-dependent** variables change by nature such as smoking status, employment status, air pollution exposure, or (the classic example) heart-transplant status for a patient awaiting a transplant. A patient's transplant indicator is 0 until the day of transplant and 1 thereafter, for the remainder of follow-up.\n2.  **Defined** time-dependent variables are constructed specifically to test or relax the PH assumption for a time-independent predictor whose *effect*, not its value, appears to change over time.\n\nTime can enter the extended Cox model in three ways: (1) directly, as $X \\times t$; (2) as a general function $X \\times g(t)$ (e.g., $g(t)=\\log t$); or (3) as a **Heaviside function**, a step function that lets a covariate's effect take one value before a pre-specified time $t_0$ and a different value after it:\n\n$$\nh(t,\\mathbf{X}) = h_0(t)\\exp\\left(\\beta_1 X + \\delta \\, X\\, g(t)\\right), \\qquad g(t) = \\begin{cases} 0 & t < t_0 \\\\ 1 & t \\ge t_0 \\end{cases}\n$$\n\nBefore $t_0$ the effect of $X$ is $\\beta_1$; at or after $t_0$ it becomes $\\beta_1 + \\delta$. Heaviside functions are attractive because they are simple to interpret and model an abrupt, known-timepoint change in effect (e.g., after a protocol amendment); a general (continuous) function of time is more appropriate when the change in effect is gradual.\n\nBecause the general hazard-ratio formula now involves the difference in time-dependent covariate values *at time* $t$, **the hazard ratio itself becomes a function of time**. This is precisely why a model with time-dependent covariates no longer satisfies (and doesn't need to satisfy) the ordinary PH assumption. Estimation still proceeds by maximum (partial) likelihood, and Wald/LR tests and confidence intervals are constructed the same way as for the standard Cox model, though the risk sets used to build the partial likelihood are more complex.\n\n### A Worked Example in R: The Stanford Heart Transplant Data\n\nThe `heart` data set built into the **survival** package is the classic time-dependent covariate example:- patients awaiting a heart transplant, where `transplant` status changes value partway through a patient's follow-up time. The data are already arranged in *counting-process* `(start, stop, event)` format, which is the standard way R represents time-dependent covariates:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndata(heart)\nhead(heart)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>   start stop event        age      year surgery transplant id\n#> 1     0   50     1 -17.155373 0.1232033       0          0  1\n#> 2     0    6     1   3.835729 0.2546201       0          0  2\n#> 3     0    1     0   6.297057 0.2655715       0          0  3\n#> 4     1   16     1   6.297057 0.2655715       0          1  3\n#> 5     0   36     0  -7.737166 0.4900753       0          0  4\n#> 6    36   39     1  -7.737166 0.4900753       0          1  4\n```\n\n\n:::\n\n```{.r .cell-code}\ncox_td <- coxph(Surv(start, stop, event) ~ age + surgery + transplant, data = heart)\nsummary(cox_td)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> Call:\n#> coxph(formula = Surv(start, stop, event) ~ age + surgery + transplant, \n#>     data = heart)\n#> \n#>   n= 172, number of events= 75 \n#> \n#>                 coef exp(coef) se(coef)      z Pr(>|z|)  \n#> age          0.03054   1.03101  0.01389  2.198   0.0279 *\n#> surgery     -0.77333   0.46147  0.35967 -2.150   0.0315 *\n#> transplant1  0.01610   1.01623  0.30859  0.052   0.9584  \n#> ---\n#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n#> \n#>             exp(coef) exp(-coef) lower .95 upper .95\n#> age            1.0310     0.9699     1.003    1.0595\n#> surgery        0.4615     2.1670     0.228    0.9339\n#> transplant1    1.0162     0.9840     0.555    1.8606\n#> \n#> Concordance= 0.6  (se = 0.036 )\n#> Likelihood ratio test= 10.72  on 3 df,   p=0.01\n#> Wald test            = 9.68  on 3 df,   p=0.02\n#> Score (logrank) test = 10  on 3 df,   p=0.02\n```\n\n\n:::\n:::\n\n\nEach subject contributes one row per time interval during which their covariate values are constant; a subject who receives a transplant partway through follow-up contributes (at least) two rows, one with `transplant = 0` up to the transplant date, and one with `transplant = 1` from the transplant date onward. This `(start, stop)` counting-process layout is the general mechanism R uses to fit both the extended Cox model and the Heaviside-function formulation described above (a Heaviside term is simply an additional column, computed as the covariate multiplied by an indicator for `stop >= t0`, included alongside the time-independent version of the same covariate).\n\n## Parametric Survival Models\n\n### Motivation\n\nThe Cox model is semi-parametric which leaves the baseline hazard $h_0(t)$ completely unspecified. A **parametric survival model**, by contrast, assumes survival time follows a specific probability distribution (exponential, Weibull, log-logistic, log-normal, or generalized gamma, among others), fully specified except for a small number of unknown parameters. Once a probability density function $f(t)$ is specified, the corresponding survival function $S(t) = \\int_t^\\infty f(u)\\,du$ and hazard function $h(t) = f(t)/S(t)$ follow directly specifying any one of the three ($f$, $S$, or $h$) determines the other two.\n\nParametric models produce smooth theoretical survival curves (rather than the step functions typical of KM and Cox-adjusted estimates), and, if the distributional assumption is reasonable, they yield more precise and more easily summarized estimates (e.g., closed-form expressions for median survival). The trade-off is the added distributional assumption itself, which should be checked.\n\n### The Exponential Model\n\nThe simplest parametric survival model assumes a **constant hazard** over time, $h(t) = \\lambda$, which implies $S(t) = \\exp(-\\lambda t)$. Re-parameterizing $\\lambda = \\exp(\\beta_0 + \\beta_1 X_1 + \\dots)$ allows covariates to be incorporated. Note that assuming a constant hazard is a *much stronger* assumption than proportional hazards if the hazards themselves are constant, their ratio is automatically constant, but a constant ratio does not require either hazard individually to be constant.\n\n### The Weibull Model\n\nThe **Weibull distribution** is the most widely used parametric survival model. It generalizes the exponential by adding a shape parameter $p$ that governs whether the hazard increases, decreases, or stays constant over time (the exponential is the special case $p=1$). A convenient property of the Weibull model is that **if the AFT assumption holds, the PH assumption also holds** for a Weibull-distributed outcome making it something of a bridge between the two frameworks. Another useful property: $\\log[-\\log S(t)]$ is linear in $\\log(t)$ under a Weibull model, which provides a simple graphical check. After plotting the log-log KM curves against $\\log(t)$ for each group should produce roughly straight, parallel lines if the Weibull (and PH) assumptions are reasonable.\n\n### Accelerated Failure Time (AFT) Models\n\nMany parametric survival models including the exponential, Weibull, and log-logistic can be formulated as **accelerated failure time (AFT)** models, an alternative to the proportional-hazards model. Where the PH model assumes covariates act multiplicatively on the **hazard**, the AFT model assumes covariates act multiplicatively on **survival time** itself:\n\n$$\n\\log T = \\alpha_0 + \\alpha_1 X_1 + \\alpha_2 X_2 + \\dots + \\alpha_p X_p + \\sigma\\varepsilon\n$$\n\nwhere $\\sigma$ is a scale parameter and $\\varepsilon$ is a random error term whose assumed distribution determines the AFT model family (e.g., a standard extreme-value distribution for $\\varepsilon$ gives the Weibull/exponential AFT model).\n\nA helpful intuition: it is often said dogs age about seven times faster than humans, so that a dog surviving to age 10 is, in some sense, \"equivalent\" to a human surviving to age 70. Formally, $S_{dog}(t) = S_{human}(7t)$ :- dogs are accelerated through life by a factor of 7 relative to humans. The AFT model quantifies exactly this kind of \"stretching\" or \"contraction\" of the survival time scale as a function of covariates. The key measure of association is the **acceleration factor**, $\\gamma = \\exp(\\alpha_1)$: it is the ratio of times at which two groups reach the *same* survival probability. An acceleration factor greater than 1 for an exposure means that exposure is **beneficial** (survival time is stretched out) . This is the opposite direction from a hazard ratio, where $HR>1$ indicates **harm**.\n\n**Interpreting AFT coefficients:** increasing $X_1$ by one unit, holding other covariates fixed, changes the expected log survival time by $\\alpha_1$, i.e., it multiplies expected survival time by $\\exp(\\alpha_1)$. If $\\alpha_1 > 0$ survival time increases (better survival). If $\\alpha_1 < 0$, survival time decreases (worse survival).\n\n**Worked example.** In the leukemia remission-time trial, fitting an exponential AFT model with treatment as the sole predictor gives an acceleration factor of $\\gamma = \\exp(1.5266) = 4.60$ , treatment stretches expected remission time by a factor of 4.6 relative to placebo. Fitting the richer Weibull AFT model to the same data gives a similar acceleration factor (3.55, 95% CI 1.93–6.53) with a slightly better model fit, since the Weibull relaxes the strong constant-hazard assumption of the exponential model.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\naft_exp  <- survreg(Surv(time, status) ~ age + sex, data = lung, dist = \"exponential\")\nsummary(aft_exp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> \n#> Call:\n#> survreg(formula = Surv(time, status) ~ age + sex, data = lung, \n#>     dist = \"exponential\")\n#>                Value Std. Error     z      p\n#> (Intercept)  6.84061    0.58748 11.64 <2e-16\n#> age         -0.01562    0.00911 -1.72  0.086\n#> sexFemale    0.48093    0.16709  2.88  0.004\n#> \n#> Scale fixed at 1 \n#> \n#> Exponential distribution\n#> Loglik(model)= -1156.1   Loglik(intercept only)= -1162.3\n#> \tChisq= 12.48 on 2 degrees of freedom, p= 0.002 \n#> Number of Newton-Raphson Iterations: 4 \n#> n= 228\n```\n\n\n:::\n\n```{.r .cell-code}\naft_weib <- survreg(Surv(time, status) ~ age + sex, data = lung, dist = \"weibull\")\nsummary(aft_weib)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> \n#> Call:\n#> survreg(formula = Surv(time, status) ~ age + sex, data = lung, \n#>     dist = \"weibull\")\n#>                Value Std. Error     z       p\n#> (Intercept)  6.65694    0.44752 14.88 < 2e-16\n#> age         -0.01226    0.00696 -1.76  0.0781\n#> sexFemale    0.38209    0.12748  3.00  0.0027\n#> Log(scale)  -0.28230    0.06188 -4.56 5.1e-06\n#> \n#> Scale= 0.754 \n#> \n#> Weibull distribution\n#> Loglik(model)= -1147.1   Loglik(intercept only)= -1153.9\n#> \tChisq= 13.59 on 2 degrees of freedom, p= 0.0011 \n#> Number of Newton-Raphson Iterations: 5 \n#> n= 228\n```\n\n\n:::\n:::\n\n\nNote that `survreg()` reports coefficients on the $\\log T$ scale directly (the AFT parameterization), which is the *opposite* sign convention from `coxph()`'s hazard-ratio scale, a positive `survreg` coefficient means **longer** survival, while a positive `coxph` coefficient means **higher hazard** (shorter survival). Model fit for a parametric model can be checked graphically using **Cox-Snell residuals**: if the model is correctly specified, the Cox-Snell residuals should themselves behave like a censored sample from a unit-exponential distribution, i.e., a plot of the cumulative hazard of the residuals against the residuals should fall approximately on a straight line through the origin with slope 1.\n\n### Comparing AFT and Cox Regression\n\n|   | AFT Model | Cox PH Model |\n|:---|:---|:---|\n| Assumption | Specific error distribution (exponential, Weibull, etc.) | Proportional hazards |\n| Coefficient interpretation | Change in (log) survival time | Change in log hazard (hazard ratio) |\n| Baseline hazard | Fully specified | Left unspecified |\n| Typical use | Comparing survival times directly; some high-dimensional / variable-selection settings | The default choice in most biomedical survival studies |\n\n## Design and Sample Size Considerations for Survival Studies\n\nDesigning a study with a time-to-event outcome requires answering several linked questions: how many subjects are needed, how long should the accrual (recruitment) period be, how long should follow-up continue after accrual ends, and how should the analysis handle subjects who switch treatment groups partway through?\n\n### Basic Statistical Principles\n\nAs with any hypothesis test, four quantities are linked in sample-size planning for survival studies:\n\n-   $\\alpha$ (Type I error) : the probability of rejecting $H_0$ when it is actually true; conventionally set to 0.05\n-   **Power (**$1-\\beta$): the probability of correctly rejecting $H_0$ when a true difference exists; power increases with sample size\n-   **Effect size (**$\\Delta$): the magnitude of the true difference between groups, expressed as a hazard ratio, a ratio of survival probabilities, or a ratio of median survival times; larger effect sizes require fewer subjects to detect\n-   **Sample size / number of events**: the quantity we are usually solving for\n\nA key distinction in survival study design is between the **study size** ($N$, total number of participants enrolled) and the **number of events** ($NEV$, the number of participants who actually experience the outcome during the study). Because the statistical power of a survival analysis is driven primarily by the number of *events* observed, not simply the number of subjects enrolled, sample size calculations typically proceed in two stages: first determine the required number of events, then back-calculate the total study size needed to observe that many events given the assumed event rate, accrual period, and follow-up duration.\n\n### Freedman's Formula for the Number of Events\n\nAssuming proportional hazards, a widely used formula (Freedman, 1982) for the number of events required to detect a hazard ratio (or equivalently a ratio of median survival times) $\\Delta$ with two-sided significance level $\\alpha$ and power $1-\\beta$ is:\n\n$$ NEV = \\frac{\\left(z_{1-\\alpha/2} + z_{1-\\beta}\\right)^2 (\\Delta+1)^2}{(\\Delta - 1)^2} $$\n\nConverting the required number of events into a required study size additionally requires the length of the accrual period, the length of additional follow-up after accrual closes, and an assumed event-time distribution (exponential is common, since it yields simple closed-form results and is usually adequate for planning purposes even if it will not be assumed for the final analysis). In practice, these calculations are performed by software. Dedicated tools such as `powerSurvEpi::ssizeCT.default()`, `Hmisc::cpower()`, or the `gsDesign` package implement these formulas (including accrual/follow-up adjustments) directly. Sample size calculation with R is demonstrated in Sample size calculation @sec-sse_survival.\n\n### Additional Design Considerations\n\n-   **Unequal allocation.** Sample size formulas can be adapted for allocation ratios other than 1:1 (e.g., 2:1 randomization).\n-   **Loss to follow-up.** If a known or anticipated proportion of subjects will be lost before experiencing the event, the required study size (with full follow-up) must be inflated accordingly.\n-   **Treatment cross-over.** Under the intention-to-treat (ITT) principle, subjects are analyzed according to their original randomized assignment regardless of whether they later switch treatments. This preserves the benefits of randomization. However, cross-over dilutes the observed effect size, so the study size must be inflated by a **cross-over adjustment / sample size inflation factor** to maintain the originally planned power.\n\n### Multiple Comparisons\n\nWhenever a study involves several hypothesis tests on the same data set (pairwise group comparisons, multiple outcomes, subgroup analyses), the probability of at least one **false positive** across the whole family of tests, **familywise (experimentwise) error rate** increases well above selected $\\alpha$. For example, with 10 independent tests each conducted at $\\alpha=0.05$, the probability of at least one Type I error is $1-(1-0.05)^{10} \\approx 0.40$.\n\nCommon corrections for the familywise error rate include:\n\n-   **Bonferroni**: use $\\alpha/m$ for $m$ comparisons (simple but conservative)\n-   **Šidák**: $\\alpha_{SID} = 1-(1-\\alpha)^{1/m}$ (slightly less conservative than Bonferroni)\n-   **Benjamini-Hochberg (FDR)**: controls the *expected proportion* of false discoveries rather than the probability of any false discovery, and is less conservative when many tests are performed\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nraw_p <- c(0.01, 0.02, 0.04, 0.20, 0.03)\np.adjust(raw_p, method = \"bonferroni\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> [1] 0.05 0.10 0.20 1.00 0.15\n```\n\n\n:::\n\n```{.r .cell-code}\np.adjust(raw_p, method = \"BH\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> [1] 0.05 0.05 0.05 0.20 0.05\n```\n\n\n:::\n:::\n\n\nNot all statisticians agree that adjustment is always appropriate. Rothman (1990) famously argued that routine multiplicity adjustment sacrifices power (inflating Type II error) in exchange for protecting the null hypothesis, which may not always be the right trade-off[@rothman1990]. Whether (and how) to adjust should be guided by the study's goals, its exploratory vs. confirmatory nature, and the relative costs of false positive versus false negative conclusions.\n\n## Competing Risks\n\n### The Problem\n\n**Competing risks** arise when each subject can experience only one of several distinct types of event, and the occurrence of one type precludes (or \"competes with\") observing the others. Classic examples include a patient who can die of cancer *or* of cardiovascular disease (but not both), or a soldier who can die in combat *or* in a traffic accident. When competing risks are present, the standard KM/Cox toolbox needs modification, because:\n\n-   Treating competing events simply as \"censored\" observations in a cause-specific analysis requires assuming the competing risks are **independent** of the event of interest\n-   The KM curve for a specific cause, computed this way, can have a questionable interpretation in an extreme example. If an entire cohort dies simultaneously in an unrelated accident, the KM \"survival\" curve for, say, cancer death remains at 1 (implying no one ever dies of cancer), which is clearly misleading\n\n### Cause-Specific Hazards (Method 1)\n\nThe most common approach fits a **separate Cox model for each event type**, treating all *other* event types (in addition to ordinary loss-to-follow-up and study-end censoring) as censored observations. This gives a cause-specific hazard ratio for each event type, e.g., $h_{ca}(t,\\mathbf{X}) = h_{0,ca}(t)\\exp(\\sum \\beta_i X_i)$ for cancer death specifically. This approach is intuitive and easy to implement but still assumes the competing risks are independent, and the resulting \"1 minus cause-specific KM\" curve overestimates the true cumulative probability of that specific event.\n\n### Cumulative Incidence Functions (Fine & Gray)\n\nThe **cumulative incidence function (CIF)** is a more appropriate summary curve in the presence of competing risks. It starts at 0 (rather than 1) and increases as events of the specific type of interest occur, appropriately accounting for the fact that subjects who experience a competing event are no longer at risk for the event of interest. Unlike the naive \"1 - KM\" curve, the CIF does not require assuming the competing risks are independent. **Gray's test** (1988) is a log-rank-like test for comparing CIFs between groups (again without the independence assumption, though it does not adjust for covariates), and the **Fine-Gray model** (1999) extends the proportional-hazards framework to model the CIF (technically, the \"subdistribution hazard\") directly as a function of covariates.\n\nR's `survival` package supports multi-state `Surv()` objects that directly produce cumulative incidence estimates via `survfit()`. Using the built-in `mgus2` data set (monoclonal gammopathy patients who may progress to a plasma cell malignancy or die of another cause before progressing, two competing risks):\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndata(mgus2)\nstr(mgus2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> 'data.frame':\t1384 obs. of  11 variables:\n#>  $ id    : num  1 2 3 4 5 6 7 8 9 10 ...\n#>  $ age   : num  88 78 94 68 90 90 89 87 86 79 ...\n#>   ..- attr(*, \"label\")= chr \"AGE AT mgus_sp\"\n#>  $ sex   : Factor w/ 2 levels \"F\",\"M\": 1 1 2 2 1 2 1 1 1 1 ...\n#>   ..- attr(*, \"label\")= chr \"Sex\"\n#>   ..- attr(*, \"format\")= chr \"$desex\"\n#>  $ dxyr  : num  1981 1968 1980 1977 1973 ...\n#>  $ hgb   : num  13.1 11.5 10.5 15.2 10.7 12.9 10.5 12.3 14.5 9.4 ...\n#>  $ creat : num  1.3 1.2 1.5 1.2 0.8 1 0.9 1.2 0.9 1.1 ...\n#>  $ mspike: num  0.5 2 2.6 1.2 1 0.5 1.3 1.6 2.4 2.3 ...\n#>   ..- attr(*, \"label\")= chr \"SEP SPIKE AT mgus_sp\"\n#>  $ ptime : num  30 25 46 92 8 4 151 2 57 136 ...\n#>  $ pstat : num  0 0 0 0 0 0 0 0 0 0 ...\n#>  $ futime: num  30 25 46 92 8 4 151 2 57 136 ...\n#>  $ death : num  1 1 1 1 1 1 1 1 0 1 ...\n```\n\n\n:::\n\n```{.r .cell-code}\nmgus2$etime <- with(mgus2, ifelse(pstat == 0, futime, ptime))\nmgus2$event <- with(mgus2, ifelse(pstat == 0, 2 * death, 1))\nmgus2$event <- factor(mgus2$event, 0:2, labels = c(\"censor\", \"pcm\", \"death\"))\n\nfit_cif <- survfit(Surv(etime, event) ~ sex, data = mgus2)\nfit_cif\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> Call: survfit(formula = Surv(etime, event) ~ sex, data = mgus2)\n#> \n#>                n nevent     rmean se(rmean)*\n#> sex=F, (s0)  631      0 139.01247   5.682211\n#> sex=M, (s0)  753      0 122.97693   5.742051\n#> sex=F, pcm   631     59  42.77078   4.495519\n#> sex=M, pcm   753     56  31.82962   4.185262\n#> sex=F, death 631    370 242.21675   6.745244\n#> sex=M, death 753    490 269.19344   6.630760\n#>    *restricted mean time in state (max time = 424 )\n```\n\n\n:::\n\n```{.r .cell-code}\nplot(fit_cif, col = c(1, 1, 2, 2), lty = c(1, 2, 1, 2),\n     xlab = \"Years from diagnosis\", ylab = \"Cumulative incidence\",\n     main = \"Cumulative Incidence of PCM and Death, by Sex\")\nlegend(\"topleft\", legend = c(\"F: PCM\", \"F: Death\", \"M: PCM\", \"M: Death\"),\n       col = c(1, 2, 1, 2), lty = c(1, 1, 2, 2), cex = 0.8)\n```\n\n::: {.cell-output-display}\n![](16_Survival_analysis_files/figure-html/unnamed-chunk-18-1.png){fig-align='center' width=85%}\n:::\n:::\n\n\nWhen a `Surv()` object has more than two states (with the first factor level treated as censoring), `survfit()` automatically returns the cumulative incidence for each competing event type rather than an ordinary KM survival curve. This is the modern R equivalent of the Fine-and-Gray cumulative incidence approach.\n\n### The Lunn-McNeil Alternative (Method 2)\n\nAn alternative strategy, the **Lunn-McNeil approach**, duplicates each subject's data row once per competing risk type and fits a single **stratified** Cox model (stratified on event type) to the augmented data set, rather than fitting separate models for each cause. With appropriate coding, this reproduces the same hazard ratios as the cause-specific approach, but additionally allows direct statistical tests of whether a covariate's effect differs across event types (i.e., whether a no-interaction model, with one common coefficient per covariate across event types, is adequate, versus needing separate coefficients per event type), a comparison that is awkward to make when the cause-specific models are fit completely separately.\n\n## Extensions: Machine Learning Approaches to Survival Analysis\n\nBeyond the classical toolbox covered in this chapter, a growing set of machine-learning methods extend survival analysis to high-dimensional and more flexible settings:\n\n-   **Regularized Cox models** (ridge, LASSO, elastic net via, e.g., the `glmnet` package) add a penalty to the partial likelihood, which stabilizes estimation and performs implicit variable selection when the number of predictors is large relative to the number of events (common in genomic or high-dimensional EHR data), addressing the multicollinearity and overfitting problems of an unpenalized Cox model in that setting.\n-   **Survival trees** recursively split the covariate space (like a classification/regression tree) using a dissimilarity measure, often the log-rank statistic, to find the split that maximizes the survival difference between resulting nodes.\n-   **Random survival forests** ensemble many survival trees (analogous to random forests for regression/classification) for improved prediction accuracy and reduced overfitting.\n-   **Deep learning approaches** (e.g., DeepSurv, a deep Cox proportional-hazards network) replace the linear predictor $\\sum \\beta_i X_i$ with a neural network, allowing flexible, non-linear modeling of covariate effects on the hazard, and have been extended to convolutional architectures (for imaging data), transfer learning, and active learning settings for censored data.\n\nThese methods trade some of the interpretability of the classical Cox model for greater flexibility and predictive performance, and are an active area of ongoing methodological research.\n\n## Summary of Key R Functions for Survival Analysis\n\n| Function | Package | Purpose |\n|:---|:---|:---|\n| `Surv()` | survival | Creates the survival outcome object (time, status, or start/stop/status) |\n| `survfit()` | survival | Estimates Kaplan-Meier curves; produces cumulative incidence for multi-state outcomes |\n| `survdiff()` | survival | Performs the log-rank test comparing survival across groups |\n| `coxph()` | survival | Fits the (semi-parametric) Cox proportional hazards model, including stratified and time-dependent (counting-process) extensions |\n| `cox.zph()` | survival | Tests and plots the proportional hazards assumption via scaled Schoenfeld residuals |\n| `survreg()` | survival | Fits fully parametric survival models (exponential, Weibull, log-normal, log-logistic AFT models) |\n| `concordance()` | survival | Computes Harrell's (and, with weighting, Uno's) C-statistic |\n| `p.adjust()` | stats | Adjusts p-values for multiple comparisons (Bonferroni, BH/FDR, etc.) |\n\n## A Complete Worked Example: The NCCTG Lung Cancer Data\n\nTo tie the chapter together, the `lung` data set (North Central Cancer Treatment Group, Loprinzi et al. 1994; $N=228$, 63 censored), already introduced at the start of this chapter, can be carried through the full analytic pipeline described above: descriptive KM curves, a log-rank comparison, a multivariable Cox model, a PH assumption check, and a parametric alternative.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# 1. Kaplan-Meier by sex, with log-rank test\nkm_sex <- survfit(Surv(time, status) ~ sex, data = lung)\nkm_sex\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> Call: survfit(formula = Surv(time, status) ~ sex, data = lung)\n#> \n#>              n events median 0.95LCL 0.95UCL\n#> sex=Male   138    112    270     212     310\n#> sex=Female  90     53    426     348     550\n```\n\n\n:::\n\n```{.r .cell-code}\nsurvdiff(Surv(time, status) ~ sex, data = lung)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> Call:\n#> survdiff(formula = Surv(time, status) ~ sex, data = lung)\n#> \n#>              N Observed Expected (O-E)^2/E (O-E)^2/V\n#> sex=Male   138      112     91.6      4.55      10.3\n#> sex=Female  90       53     73.4      5.68      10.3\n#> \n#>  Chisq= 10.3  on 1 degrees of freedom, p= 0.001\n```\n\n\n:::\n\n```{.r .cell-code}\nplot(km_sex, col = c(\"blue\", \"red\"), xlab = \"Days\", ylab = \"Survival probability\",\n     main = \"NCCTG Lung Cancer: Survival by Sex\")\nlegend(\"topright\", legend = c(\"Male\", \"Female\"), col = c(\"blue\", \"red\"), lty = 1)\n```\n\n::: {.cell-output-display}\n![](16_Survival_analysis_files/figure-html/unnamed-chunk-19-1.png){fig-align='center' width=85%}\n:::\n\n```{.r .cell-code}\n# 2. Multivariable Cox PH model\ncox_lung <- coxph(Surv(time, status) ~ age + sex + ph.ecog + wt.loss, data = lung)\nsummary(cox_lung)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> Call:\n#> coxph(formula = Surv(time, status) ~ age + sex + ph.ecog + wt.loss, \n#>     data = lung)\n#> \n#>   n= 213, number of events= 151 \n#>    (15 observations deleted due to missingness)\n#> \n#>                coef exp(coef)  se(coef)      z Pr(>|z|)    \n#> age        0.013369  1.013459  0.009628  1.389 0.164951    \n#> sexFemale -0.590775  0.553898  0.175339 -3.369 0.000754 ***\n#> ph.ecog    0.515111  1.673824  0.125988  4.089 4.34e-05 ***\n#> wt.loss   -0.009006  0.991034  0.006658 -1.353 0.176135    \n#> ---\n#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n#> \n#>           exp(coef) exp(-coef) lower .95 upper .95\n#> age          1.0135     0.9867    0.9945    1.0328\n#> sexFemale    0.5539     1.8054    0.3928    0.7811\n#> ph.ecog      1.6738     0.5974    1.3076    2.1427\n#> wt.loss      0.9910     1.0090    0.9782    1.0041\n#> \n#> Concordance= 0.647  (se = 0.026 )\n#> Likelihood ratio test= 31.02  on 4 df,   p=3e-06\n#> Wald test            = 29.94  on 4 df,   p=5e-06\n#> Score (logrank) test = 30.65  on 4 df,   p=4e-06\n```\n\n\n:::\n\n```{.r .cell-code}\n# 3. Check the PH assumption\ncox.zph(cox_lung)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>          chisq df    p\n#> age     0.4353  1 0.51\n#> sex     2.6731  1 0.10\n#> ph.ecog 1.6355  1 0.20\n#> wt.loss 0.0457  1 0.83\n#> GLOBAL  4.7516  4 0.31\n```\n\n\n:::\n\n```{.r .cell-code}\n# 4. Parametric (Weibull AFT) alternative\nweib_lung <- survreg(Surv(time, status) ~ age + sex + ph.ecog + wt.loss, data = lung,\n                      dist = \"weibull\")\nsummary(weib_lung)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> \n#> Call:\n#> survreg(formula = Surv(time, status) ~ age + sex + ph.ecog + \n#>     wt.loss, data = lung, dist = \"weibull\")\n#>                Value Std. Error     z       p\n#> (Intercept)  6.75737    0.43508 15.53 < 2e-16\n#> age         -0.00889    0.00688 -1.29   0.196\n#> sexFemale    0.41616    0.12698  3.28   0.001\n#> ph.ecog     -0.36643    0.09040 -4.05 5.0e-05\n#> wt.loss      0.00613    0.00473  1.30   0.194\n#> Log(scale)  -0.33381    0.06375 -5.24 1.6e-07\n#> \n#> Scale= 0.716 \n#> \n#> Weibull distribution\n#> Loglik(model)= -1047.5   Loglik(intercept only)= -1062.6\n#> \tChisq= 30.14 on 4 degrees of freedom, p= 4.6e-06 \n#> Number of Newton-Raphson Iterations: 5 \n#> n=213 (15 observations deleted due to missingness)\n```\n\n\n:::\n:::\n\n\nAcross the KM/log-rank, Cox, and parametric analyses, female sex and better ECOG performance status are consistently associated with longer survival in this cohort illustrating how the different tools in this chapter (non-parametric, semi-parametric, and fully parametric) are complementary lenses on the same underlying data, and typically tell a consistent story when their respective assumptions are reasonably satisfied.\n\n## Chapter Summary\n\nThis chapter developed survival analysis from first principles through to modern extensions:\n\n-   Time-to-event outcomes require **specialized methods** because they combine a (possibly censored) time component with a binary event indicator, information that neither pure time-based methods (t-test, ANOVA) nor pure binary methods (logistic regression) can fully exploit\n-   **Censoring** (right, left, and interval) must be handled explicitly, under assumptions of independent, random, non-informative censoring\n-   The **Kaplan-Meier estimator** provides a non-parametric estimate of the survivor function, and the **log-rank test** compares survival between groups\n-   The **Cox proportional hazards model** is the workhorse regression tool for survival data, estimating hazard ratios while leaving the baseline hazard unspecified; its core assumption ( proportional hazards) should always be checked graphically (log-log plots) and/or formally (Schoenfeld residuals via `cox.zph()`)\n-   When PH is violated, the **stratified Cox model** (for categorical variables that can be stratified) and the **extended Cox model** (for variables whose effect changes continuously, or abruptly via a Heaviside function, over time) offer principled solutions\n-   **Parametric survival models** (exponential, Weibull, and other AFT models) provide an alternative, fully specified framework, with the acceleration factor as an intuitive, time-scale measure of association\n-   Careful attention to **model building** (interaction, confounding, the E-V-W framework), **study design** (power, sample size, cross-over, multiplicity), and **competing risks** rounds out the practical toolkit needed to plan, analyze, and correctly interpret time-to-event data\n-   Modern **machine learning extensions** (regularized Cox regression, survival trees, random survival forests, and deep survival networks) extend this classical framework to higher-dimensional and more flexible settings\n\n## References\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}