{
  "hash": "07832de098325fb6ea42b20c8ce926f8",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Categorical data analysis\"\noutput:\n  pdf_document:\n    number_sections: yes\n  html_document: default\neditor_options: \n  chunk_output_type: console\n---\n\n\n\n\n\n\nThis chapter reviews the core tools for analyzing categorical data using proportions, chi-square and Fisher's exact tests, McNemar's test for paired data, risk ratios and odds ratios, screening test characteristics, and stratified (Mantel-Haenszel) analysis. These methods answer the same substantive question that logistic regression answers later in this chapter — whether an outcome is associated with an exposure, and how strong that association is — but do so without fitting a model, and several of them (the odds ratio, the chi-square test, stratified analysis) reappear directly inside logistic regression once covariates are added. Examples below use the Western Collaborative Group Study (`wcgs`) data already introduced in this chapter, with ten-year coronary heart disease status (`chd69`) as the outcome.\n\n## Types of Categorical Data\n\nCategorical variables come in three forms, and knowing which one you have determines which test applies:\n\n-   **Binary**: exactly two categories (e.g., `chd69`: Yes/No)\n-   **Nominal**: more than two categories with no inherent order (e.g., blood type, `behpat`)\n-   **Ordinal**: more than two categories with a meaningful order but unequal or unknown spacing between them (e.g., pain severity: none/mild/moderate/severe)\n\nTwo probability distributions underlie most of the methods in this section. The **binomial distribution** describes the number of \"successes\" in *n* independent trials with a constant probability of success, and applies whenever the outcome is binary. The **multinomial distribution** extends this to outcomes with more than two categories. Nearly every method below — proportions, chi-square tests, risk ratios, odds ratios — is a way of comparing observed binomial or multinomial counts to what would be expected under a null hypothesis.\n\n## Inference for a Single Proportion\n\nFor a binary outcome observed in a sample of size $n$ with $x$ successes, the sample proportion is $\\hat{p}=x/n$. When both $n\\hat p$ and $n(1-\\hat p)$ exceed 5, $\\hat p$ is approximately normal, which justifies the Wald test and confidence interval:\n\n$$ Z_{stat}=\\frac{\\hat{p}-\\pi_0}{\\sqrt{\\pi_0(1-\\pi_0)/n}} \\qquad \\hat{p} \\pm Z_{1-\\alpha/2}\\sqrt{\\frac{\\hat p(1-\\hat p)}{n}} $$\n\nWhen the sample is small, or $\\hat p$ is close to 0 or 1, the Wald interval is known to under-cover; the exact (Clopper-Pearson) interval or the **Agresti-Coull** interval (Agresti & Coull, 1998, *The American Statistician*, 52, 119-126) are preferred in that setting.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Overall proportion of CHD in the wcgs cohort\ntable(data$chd69)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> \n#>   No  Yes \n#> 2897  257\n```\n\n\n:::\n\n```{.r .cell-code}\nx <- sum(data$chd69 == \"Yes\")\nn <- nrow(data)\n\n# One-sample test: is the CHD rate different from 10%?\nprop.test(x, n, p = 0.10, correct = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> \n#> \t1-sample proportions test without continuity correction\n#> \n#> data:  x out of n, null probability 0.1\n#> X-squared = 12.015, df = 1, p-value = 0.0005278\n#> alternative hypothesis: true p is not equal to 0.1\n#> 95 percent confidence interval:\n#>  0.07243754 0.09154836\n#> sample estimates:\n#>          p \n#> 0.08148383\n```\n\n\n:::\n\n```{.r .cell-code}\n# Exact binomial test and confidence interval\nbinom.test(x, n, p = 0.10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> \n#> \tExact binomial test\n#> \n#> data:  x and n\n#> number of successes = 257, number of trials = 3154, p-value = 0.0004093\n#> alternative hypothesis: true probability of success is not equal to 0.1\n#> 95 percent confidence interval:\n#>  0.07216913 0.09158305\n#> sample estimates:\n#> probability of success \n#>             0.08148383\n```\n\n\n:::\n:::\n\n\n### Interpretation\n\nOf the 3,154 participants, 257 developed CHD, giving $\\hat p = 0.081$ (95% Wald CI: 7.2%, 9.1%). Testing against $\\pi_0 = 0.10$ gives Z = -3.47, p = 0.0005, so the CHD rate in this cohort is significantly lower than 10%.\n\nFor small subgroups the choice of interval matters more. Restricting to the youngest age category (`agec == \"35-40\"`, n = 543, 31 events, $\\hat p = 0.057$), the Wald interval (3.8%, 7.7%) sits slightly lower than the exact interval (3.9%, 8.0%) — a reminder that the Wald method is not the recommended choice once $n$ or $\\hat p$ is small.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nyoung <- data |> dplyr::filter(agec == \"35-40\")\nx2 <- sum(young$chd69 == \"Yes\"); n2 <- nrow(young)\nphat <- x2 / n2\n\n# Wald interval\nphat + c(-1, 1) * 1.96 * sqrt(phat * (1 - phat) / n2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> [1] 0.03757508 0.07660540\n```\n\n\n:::\n\n```{.r .cell-code}\n# Exact (Clopper-Pearson) interval\nbinom.test(x2, n2)$conf.int\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> [1] 0.03911595 0.08005924\n#> attr(,\"conf.level\")\n#> [1] 0.95\n```\n\n\n:::\n:::\n\n\n## Comparing Two Independent Proportions\n\nTo compare proportions between two independent groups, the Wald test statistic and confidence interval are:\n\n$$ Z_{stat}=\\frac{(\\hat p_1-\\hat p_2)-\\delta_0}{\\sqrt{\\dfrac{\\hat p_1(1-\\hat p_1)}{n_1}+\\dfrac{\\hat p_2(1-\\hat p_2)}{n_2}}} \\qquad (\\hat p_1-\\hat p_2)\\pm Z_{1-\\alpha/2}\\sqrt{\\frac{\\hat p_1(1-\\hat p_1)}{n_1}+\\frac{\\hat p_2(1-\\hat p_2)}{n_2}} $$\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntab_sc <- table(data$smoke, data$chd69)[c(\"Yes\",\"No\"), c(\"Yes\",\"No\")]\ntab_sc  # rows = smoker, columns = chd69\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>      \n#>        Yes   No\n#>   Yes  159 1343\n#>   No    98 1554\n```\n\n\n:::\n\n```{.r .cell-code}\nprop.test(tab_sc, correct = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> \n#> \t2-sample test for equality of proportions without continuity correction\n#> \n#> data:  tab_sc\n#> X-squared = 22.764, df = 1, p-value = 1.831e-06\n#> alternative hypothesis: two.sided\n#> 95 percent confidence interval:\n#>  0.02725364 0.06582000\n#> sample estimates:\n#>     prop 1     prop 2 \n#> 0.10585885 0.05932203\n```\n\n\n:::\n:::\n\n\n### Interpretation\n\nThe CHD rate is 10.6% among smokers versus 5.9% among non-smokers, a difference of 4.7 percentage points (95% CI: 2.7, 6.6). The test statistic (Z ≈ 4.8, equivalent to the χ² statistic below) gives p < 0.0001, so smokers have a significantly higher CHD rate than non-smokers in this cohort.\n\n\n## McNemar's Test for Matched Pairs\n\nThe tests above assume independent samples. When the same subjects are measured twice (before/after, matched pairs, two raters), the two proportions are correlated and the ordinary two-proportion test no longer applies. McNemar's test instead uses only the *discordant* pairs — the cases where the two measurements disagree:\n\n$$ \\chi^2_{stat}=\\frac{(b-c)^2}{b+c}, \\quad df=1 $$\n\nwhere $b$ and $c$ are the two off-diagonal (discordant) cell counts of the $2\\times2$ paired table.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Illustrative matched-pairs example: outcome (improved/not) under two paired treatments\npairs_tab <- matrix(c(2, 2, 6, 6), nrow = 2, byrow = TRUE,\n                     dimnames = list(\"Treatment B\" = c(\"Improved\", \"Not improved\"),\n                                      \"Treatment A\" = c(\"Improved\", \"Not improved\")))\npairs_tab\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>               Treatment A\n#> Treatment B    Improved Not improved\n#>   Improved            2            2\n#>   Not improved        6            6\n```\n\n\n:::\n\n```{.r .cell-code}\nmcnemar.test(pairs_tab, correct = FALSE)   # matches the hand formula above\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> \n#> \tMcNemar's Chi-squared test\n#> \n#> data:  pairs_tab\n#> McNemar's chi-squared = 2, df = 1, p-value = 0.1573\n```\n\n\n:::\n\n```{.r .cell-code}\nmcnemar.test(pairs_tab)                    # default applies Yates' continuity correction\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> \n#> \tMcNemar's Chi-squared test with continuity correction\n#> \n#> data:  pairs_tab\n#> McNemar's chi-squared = 1.125, df = 1, p-value = 0.2888\n```\n\n\n:::\n:::\n\n\n### Interpretation\n\nHere $\\chi^2=(2-6)^2/(2+6)=2$, df = 1, p = 0.157. There is not enough evidence that the two treatments differ in their probability of improvement.\n\n## Chi-Square Test of Independence\n\nFor two independent categorical variables laid out in an $r\\times c$ contingency table, the chi-square test compares observed to expected cell counts under independence:\n\n$$ \\chi^2_{stat}=\\sum_{\\text{all cells}}\\frac{(f_o-f_e)^2}{f_e}, \\qquad f_e=\\frac{(\\text{row total})(\\text{column total})}{n}, \\qquad df=(r-1)(c-1) $$\n\nThe approximation is reliable when at least 80% of expected cell counts are $\\ge5$ and none is below 1; otherwise use Fisher's exact test.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nchisq.test(tab_sc, correct = FALSE)              # standard chi-square test\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> \n#> \tPearson's Chi-squared test\n#> \n#> data:  tab_sc\n#> X-squared = 22.764, df = 1, p-value = 1.831e-06\n```\n\n\n:::\n\n```{.r .cell-code}\nchisq.test(tab_sc, correct = FALSE)$expected      # check the >=5 rule\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>      \n#>            Yes       No\n#>   Yes 122.3887 1379.611\n#>   No  134.6113 1517.389\n```\n\n\n:::\n\n```{.r .cell-code}\nchisq.test(tab_sc, correct = TRUE)               # Yates' continuity correction\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> \n#> \tPearson's Chi-squared test with Yates' continuity correction\n#> \n#> data:  tab_sc\n#> X-squared = 22.147, df = 1, p-value = 2.526e-06\n```\n\n\n:::\n\n```{.r .cell-code}\n# Extending to an r x c table: behavior pattern (4 levels) by CHD status\ntable(data$behpat, data$chd69)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>     \n#>        No  Yes\n#>   A1  234   30\n#>   A2 1177  148\n#>   B3 1155   61\n#>   B4  331   18\n```\n\n\n:::\n\n```{.r .cell-code}\nchisq.test(table(data$behpat, data$chd69))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> \n#> \tPearson's Chi-squared test\n#> \n#> data:  table(data$behpat, data$chd69)\n#> X-squared = 39.916, df = 3, p-value = 1.11e-08\n```\n\n\n:::\n:::\n\n\n### Interpretation\n\nFor smoking status by CHD, $\\chi^2=22.76$, df = 1, p < 0.0001 (Yates-corrected: $\\chi^2=22.15$, p < 0.0001) — smoking status and CHD are not independent. The `behpat`-by-`chd69` table extends the same logic to a $4\\times2$ table without changing the test statistic or its interpretation, only the degrees of freedom.\n\n\n## Fisher's Exact Test\n\nWhen one or more expected cell counts fall below 5, the chi-square approximation is unreliable. Fisher's exact test instead conditions on the observed row and column totals and computes the exact probability of the observed table (and all more extreme tables) from the hypergeometric distribution:\n\n$$ p(a)=\\frac{\\binom{a+b}{a}\\binom{c+d}{c}}{\\binom{n}{a+c}} $$\n\nUnlike the chi-square test, Fisher's exact test has no test statistic or critical value — only a p-value — and it remains valid even with very small samples, zero cells, or highly unbalanced tables.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfisher.test(tab_sc)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> \n#> \tFisher's Exact Test for Count Data\n#> \n#> data:  tab_sc\n#> p-value = 2.366e-06\n#> alternative hypothesis: true odds ratio is not equal to 1\n#> 95 percent confidence interval:\n#>  1.434194 2.466073\n#> sample estimates:\n#> odds ratio \n#>   1.876954\n```\n\n\n:::\n:::\n\n\n### Interpretation\n\nFisher's exact test gives p < 0.0001 for the smoking/CHD table, agreeing with the chi-square result above (expected counts here are all well above 5, so either test is valid; Fisher's test is shown for comparison, and it is the correct choice whenever that condition fails).\n\n## Risk Ratio and Odds Ratio\n\nFor a $2\\times2$ table of exposure by disease,\n\n|           | Disease + | Disease − |\n|-----------|-----------|-----------|\n| Exposed   | a         | b         |\n| Unexposed | c         | d         |\n\nthe **risk ratio** compares the probability of disease between exposed and unexposed groups, and the **odds ratio** compares the odds:\n\n$$ \\hat{RR}=\\frac{a/(a+b)}{c/(c+d)} \\qquad \\hat{OR}=\\frac{ad}{bc} $$\n\nBoth are tested and estimated on the log scale, since $\\ln(\\hat{RR})$ and $\\ln(\\hat{OR})$ are approximately normal:\n\n$$ SE[\\ln(\\hat{RR})]=\\sqrt{\\frac1a-\\frac1{a+b}+\\frac1c-\\frac1{c+d}} \\qquad SE[\\ln(\\hat{OR})]=\\sqrt{\\frac1a+\\frac1b+\\frac1c+\\frac1d} $$\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\na  <- tab_sc[\"Yes\",\"Yes\"]; b <- tab_sc[\"Yes\",\"No\"]\nc_ <- tab_sc[\"No\",\"Yes\"];  d <- tab_sc[\"No\",\"No\"]\n\n# Risk ratio and 95% CI\nRR <- (a/(a+b)) / (c_/(c_+d))\nse_lnRR <- sqrt(1/a - 1/(a+b) + 1/c_ - 1/(c_+d))\nc(RR = RR, exp(log(RR) + c(-1, 1) * 1.96 * se_lnRR))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>       RR                   \n#> 1.784478 1.401165 2.272653\n```\n\n\n:::\n\n```{.r .cell-code}\n# Odds ratio and 95% CI\nOR <- (a*d) / (b*c_)\nse_lnOR <- sqrt(1/a + 1/b + 1/c_ + 1/d)\nc(OR = OR, exp(log(OR) + c(-1, 1) * 1.96 * se_lnOR))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>       OR                   \n#> 1.877353 1.444508 2.439901\n```\n\n\n:::\n:::\n\n\n::: callout-tip\nThe odds ratio and risk ratio answer slightly different questions and are not interchangeable, although they converge when the outcome is rare (here CHD is uncommon enough — about 8% — that RR = 1.78 and OR = 1.88 are close). The odds ratio is the quantity produced directly by logistic regression coefficients after exponentiating, which is why it, rather than the risk ratio, carries over into the regression models later in this chapter.\n:::\n\n### Interpretation\n\nSmokers have 1.78 times the risk of developing CHD compared to non-smokers (95% CI: 1.40, 2.27), and 1.88 times the odds (95% CI: 1.44, 2.44). Both intervals exclude 1, confirming the association already identified by the chi-square and Fisher's exact tests.\n\n\n## Screening Test Characteristics\n\nDiagnostic and screening tests are evaluated against a $2\\times2$ table of test result by true disease status:\n\n|        | Disease + | Disease − |\n|--------|-----------|-----------|\n| Test + | True Positive (TP)  | False Positive (FP) |\n| Test − | False Negative (FN) | True Negative (TN)  |\n\n$$ Se=P(+|D)=\\frac{TP}{TP+FN} \\qquad Sp=P(-|\\bar D)=\\frac{TN}{TN+FP} $$\n$$ PPV=P(D|+)=\\frac{TP}{TP+FP} \\qquad NPV=P(\\bar D|-)=\\frac{TN}{TN+FN} $$\n\nSensitivity and specificity are properties of the test itself and do not depend on how common the disease is. PPV and NPV, by contrast, depend heavily on disease prevalence — the same test performs very differently (in PPV terms) in a high-prevalence versus a low-prevalence population — and PPV/NPV cannot be validly calculated from a case-control sample where disease prevalence was fixed by the study design rather than observed.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nscreen <- matrix(c(180, 16, 20, 184), nrow = 2, byrow = TRUE,\n                  dimnames = list(Test = c(\"Positive\", \"Negative\"),\n                                   Disease = c(\"Yes\", \"No\")))\nscreen\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>           Disease\n#> Test       Yes  No\n#>   Positive 180  16\n#>   Negative  20 184\n```\n\n\n:::\n\n```{.r .cell-code}\nsensitivity <- screen[\"Positive\",\"Yes\"] / sum(screen[,\"Yes\"])\nspecificity <- screen[\"Negative\",\"No\"]  / sum(screen[,\"No\"])\nppv <- screen[\"Positive\",\"Yes\"] / sum(screen[\"Positive\",])\nnpv <- screen[\"Negative\",\"No\"]  / sum(screen[\"Negative\",])\nround(c(Sensitivity = sensitivity, Specificity = specificity, PPV = ppv, NPV = npv), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> Sensitivity Specificity         PPV         NPV \n#>       0.900       0.920       0.918       0.902\n```\n\n\n:::\n:::\n\n\n### Interpretation\n\nThis hypothetical test has 90% sensitivity and 92% specificity, both comfortably above the commonly cited 80% threshold for a \"good\" screening test. In this sample (50% disease prevalence by design), PPV is 92% and NPV is 90%; in a lower-prevalence population, the same test's PPV would be lower even though sensitivity and specificity stay the same.\n\n\n## Stratified 2×2 Tables and the Mantel-Haenszel Method\n\nA crude (unstratified) odds ratio, like the one computed above for smoking and CHD, can be confounded by a third variable that is associated with both the exposure and the outcome. The Mantel-Haenszel approach addresses this by splitting the data into strata of a potential confounder, testing for association *within* each stratum, and then pooling the stratum-specific evidence into a single adjusted test and effect estimate.\n\nThe Cochran-Mantel-Haenszel (CMH) test statistic, summed across $q$ strata, is:\n\n$$ Q_{MH}=\\frac{\\left[\\sum_{h=1}^{q}(n_{h11}-m_{h11})\\right]^2}{\\sum_{h=1}^{q}v_{h11}}, \\qquad m_{h11}=\\frac{n_{h1.}n_{h.1}}{n_h}, \\qquad v_{h11}=\\frac{n_{h1.}n_{h2.}n_{h.1}n_{h.2}}{n_h^2(n_h-1)} $$\n\nand the Mantel-Haenszel estimate of a **common** odds ratio across strata is:\n\n$$ \\hat\\theta_{MH}=\\frac{\\sum_{h=1}^{q} n_{h11}n_{h22}/n_h}{\\sum_{h=1}^{q} n_{h12}n_{h21}/n_h} $$\n\nHere we stratify the smoking/CHD association by behavior pattern (`dibpat`: Type A vs. Type B), a variable known in this cohort to be associated with both smoking and CHD risk.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nstrat_tab <- xtabs(~ smoke + chd69 + dibpat, data = data)\nstrat_tab\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> , , dibpat = Type A\n#> \n#>      chd69\n#> smoke  No Yes\n#>   No  714  70\n#>   Yes 697 108\n#> \n#> , , dibpat = Type B\n#> \n#>      chd69\n#> smoke  No Yes\n#>   No  840  28\n#>   Yes 646  51\n```\n\n\n:::\n\n```{.r .cell-code}\n# Stratum-specific odds ratios\napply(strat_tab, 3, function(t) (t[1,1]*t[2,2]) / (t[1,2]*t[2,1]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>   Type A   Type B \n#> 1.580488 2.368421\n```\n\n\n:::\n\n```{.r .cell-code}\n# Cochran-Mantel-Haenszel test and common odds ratio\nmantelhaen.test(strat_tab, correct = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> \n#> \tMantel-Haenszel chi-squared test without continuity correction\n#> \n#> data:  strat_tab\n#> Mantel-Haenszel X-squared = 19.486, df = 1, p-value = 1.013e-05\n#> alternative hypothesis: true common odds ratio is not equal to 1\n#> 95 percent confidence interval:\n#>  1.380054 2.337230\n#> sample estimates:\n#> common odds ratio \n#>          1.795969\n```\n\n\n:::\n:::\n\n\n### Test of Homogeneity (Breslow-Day Test)\n\nBefore pooling stratum-specific odds ratios into a single MH estimate, it is important to check that the strata actually share a common odds ratio (i.e., that behavior pattern is a confounder rather than an effect modifier). The Breslow-Day test evaluates $H_0:\\theta_1=\\theta_2=\\dots=\\theta_q$ against a $\\chi^2_{q-1}$ distribution.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nDescTools::BreslowDayTest(strat_tab)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> \n#> \tBreslow-Day test on Homogeneity of Odds Ratios\n#> \n#> data:  strat_tab\n#> X-squared = 1.9456, df = 1, p-value = 0.1631\n```\n\n\n:::\n:::\n\n\n### Interpretation\n\nThe stratum-specific odds ratios (Type A: 1.58; Type B: 2.37) differ numerically, but the Breslow-Day test does not find this difference statistically significant ($\\chi^2\\approx1.9$, p = 0.16), so it is reasonable to pool them. The CMH test rejects independence after adjusting for behavior pattern ($Q_{MH}\\approx19.5$, p < 0.0001), and the Mantel-Haenszel common odds ratio is about 1.80 — close to the crude, unadjusted odds ratio of 1.88 computed earlier, indicating that behavior pattern is not a strong confounder of the smoking-CHD association in this cohort. Had the stratum-specific and crude odds ratios diverged sharply, that would signal confounding requiring an adjusted (or model-based) estimate rather than the crude one.\n\n### Simpson's Paradox\n\nStratified analysis exists because an association observed in aggregated data can behave very differently — even reverse direction — once a confounder is taken into account. A classic illustration comes from a comparison of two kidney stone treatments (Charig et al., 1986, *BMJ*):\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nkidney <- tibble::tribble(\n  ~Stratum,       ~Treatment, ~Success, ~Failure,\n  \"Small stones\", \"A\",         81,        6,\n  \"Small stones\", \"B\",        234,       36,\n  \"Large stones\", \"A\",        192,       71,\n  \"Large stones\", \"B\",         55,       25,\n  \"Overall\",       \"A\",       273,       77,\n  \"Overall\",       \"B\",       289,       61\n)\nkidney |> dplyr::mutate(Success_rate = round(Success / (Success + Failure), 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> # A tibble: 6 x 5\n#>   Stratum      Treatment Success Failure Success_rate\n#>   <chr>        <chr>       <dbl>   <dbl>        <dbl>\n#> 1 Small stones A              81       6        0.931\n#> 2 Small stones B             234      36        0.867\n#> 3 Large stones A             192      71        0.73 \n#> 4 Large stones B              55      25        0.688\n#> 5 Overall      A             273      77        0.78 \n#> 6 Overall      B             289      61        0.826\n```\n\n\n:::\n:::\n\n\nTreatment A has the higher success rate for both small stones (93% vs. 87%) and large stones (73% vs. 69%) individually, yet Treatment B has the higher success rate overall (83% vs. 78%). The reversal happens because stone size is a confounder: Treatment A was used disproportionately on harder-to-treat large stones, while Treatment B was used mostly on easier small stones, which drags the *unadjusted* success rate for B upward. This is exactly the scenario the CMH test and Mantel-Haenszel odds ratio are designed to guard against, and it is also the core motivation for adjusting for covariates in the multivariable logistic regression models that follow.\n\n\n# Logistic regression Analysis\n\nThis chapter began with the foundational tools for analyzing categorical data directly from contingency tables — proportions, chi-square and Fisher's exact tests, McNemar's test, risk ratios and odds ratios, screening test characteristics, and Mantel-Haenszel stratified analysis — and now turns to regression-based approaches for binary, nominal, and ordinal outcomes. We begin with logistic regression (univariate, multivariable, and interaction models), and then cover five extensions of logistic regression: exact logistic regression, Firth's penalized logistic regression, generalized estimating equations (GEE), multinomial logistic regression, and ordinal logistic regression.\n\nLogistic regression is a type of regression analysis used when the dependent variable is binary or categorical. It models the probability of an event occurring by fitting a logistic function to the observed data. The logistic regression equation is:\n\n$$ P(Y=1) = \\frac{1}{1 + e^{-(\\beta_0 + \\beta_1 X)}} $$\n\n-   $P(Y=1)$ : Probability of the event occurring\n-   $X$ : Independent variable\n-   $\\beta_0$ : Y-intercept\n-   $\\beta_1$ : Slope\n-   $e$ : Base of the natural logarithm\n\nLogistic regression is widely used in classification problems, such as predicting whether an email is spam or not, based on various features. It provides the probability of the event rather than predicting the exact outcome.\n\nBoth linear and logistic regression play crucial roles in statistical modeling, each serving specific purposes based on the nature of the dependent variable.\n\n\n## **Univariate Logistic regression**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmodel3<-glm(formula = chd69~agec,family = binomial(link=\"logit\"),data = data)\nsummary(model3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> \n#> Call:\n#> glm(formula = chd69 ~ agec, family = binomial(link = \"logit\"), \n#>     data = data)\n#> \n#> Coefficients:\n#>             Estimate Std. Error z value Pr(>|z|)    \n#> (Intercept)  -2.8043     0.1850 -15.162  < 2e-16 ***\n#> agec41-45    -0.1315     0.2310  -0.569 0.569298    \n#> agec46-50     0.5307     0.2235   2.374 0.017580 *  \n#> agec51-55     0.8410     0.2275   3.697 0.000218 ***\n#> agec56-60     1.0600     0.2585   4.100 4.13e-05 ***\n#> ---\n#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n#> \n#> (Dispersion parameter for binomial family taken to be 1)\n#> \n#>     Null deviance: 1781.2  on 3153  degrees of freedom\n#> Residual deviance: 1736.3  on 3149  degrees of freedom\n#> AIC: 1746.3\n#> \n#> Number of Fisher Scoring iterations: 5\n```\n\n\n:::\n\n```{.r .cell-code}\n# Model plots in 2 by 2 arrangement\npar(mfrow=c(2,2))\nplot(model3)\n```\n\n::: {.cell-output-display}\n![](Categorical_data_analysis2_files/figure-pdf/unnamed-chunk-14-1.pdf){fig-align='center' fig-pos='H' width=85%}\n:::\n\n```{.r .cell-code}\n# Determine odds ratio and its 95% CI (process-1)\nexp(model3$coefficients) # odds ratio only\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> (Intercept)   agec41-45   agec46-50   agec51-55   agec56-60 \n#>  0.06054688  0.87682153  1.70018975  2.31867902  2.88631381\n```\n\n\n:::\n\n```{.r .cell-code}\nexp(confint(model3)) # 95% CI of odds ratio\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>                 2.5 %     97.5 %\n#> (Intercept) 0.0412715 0.08543233\n#> agec41-45   0.5613828 1.39311253\n#> agec46-50   1.1072235 2.66755273\n#> agec51-55   1.4971848 3.66364452\n#> agec56-60   1.7402843 4.81378167\n```\n\n\n:::\n\n```{.r .cell-code}\ncbind(oddsratio=exp(model3$coefficients),CI=exp(confint(model3))) # odds ratio with 95% CI\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>              oddsratio     2.5 %     97.5 %\n#> (Intercept) 0.06054688 0.0412715 0.08543233\n#> agec41-45   0.87682153 0.5613828 1.39311253\n#> agec46-50   1.70018975 1.1072235 2.66755273\n#> agec51-55   2.31867902 1.4971848 3.66364452\n#> agec56-60   2.88631381 1.7402843 4.81378167\n```\n\n\n:::\n\n```{.r .cell-code}\n# Determine odds ratio and its 95% CI (process-2)\nsjPlot::tab_model(model3)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table style=\"border-collapse:collapse; border:none;\">\n<tr>\n<th style=\"border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm;  text-align:left; \">&nbsp;</th>\n<th colspan=\"3\" style=\"border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; \">chd 69</th>\n</tr>\n<tr>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  text-align:left; \">Predictors</td>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  \">Odds Ratios</td>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  \">CI</td>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  \">p</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">(Intercept)</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.06</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.04&nbsp;&ndash;&nbsp;0.09</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \"><strong>&lt;0.001</strong></td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">agec41&#45;45</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.88</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.56&nbsp;&ndash;&nbsp;1.39</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.569</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">agec46&#45;50</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">1.70</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">1.11&nbsp;&ndash;&nbsp;2.67</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \"><strong>0.018</strong></td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">agec51&#45;55</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">2.32</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">1.50&nbsp;&ndash;&nbsp;3.66</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \"><strong>&lt;0.001</strong></td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">agec56&#45;60</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">2.89</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">1.74&nbsp;&ndash;&nbsp;4.81</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \"><strong>&lt;0.001</strong></td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm; border-top:1px solid;\">Observations</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;\" colspan=\"3\">3154</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;\">R<sup>2</sup> Tjur</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;\" colspan=\"3\">0.015</td>\n</tr>\n\n</table>\n\n`````\n:::\n\n```{.r .cell-code}\n# Determine odds ratio and its 95% CI (process-3)\ngtsummary::tbl_regression(model3,exponentiate = T) |>\n  gtsummary::as_hux_xlsx(\"regression_table.xlsx\") # It helps to extract the result to excel\n\n\n\n# Determine the AIC, BIC , RMSE of the model\nperformance::model_performance(model3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> # Indices of model performance\n#> \n#> AIC    |   AICc |    BIC | Tjur's R2 |  RMSE | Sigma | Log_loss | Score_log\n#> ---------------------------------------------------------------------------\n#> 1746.3 | 1746.3 | 1776.6 |     0.015 | 0.272 |     1 |    0.275 |   -21.753\n#> \n#> AIC    | Score_spherical |   PCP\n#> --------------------------------\n#> 1746.3 |           0.006 | 0.853\n```\n\n\n:::\n\n```{.r .cell-code}\n# Prediction of new_data\ndata_new<-data[seq(4,100,4),]\n\n# predict() function helps to predict the results from in the new data\npredict(model3,data_new)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>         1         2         3         4         5         6         7         8 \n#> -1.963340 -2.935789 -1.963340 -1.963340 -2.935789 -1.963340 -1.963340 -2.273598 \n#>         9        10        11        12        13        14        15        16 \n#> -2.935789 -2.935789 -2.935789 -2.935789 -2.804337 -2.273598 -2.935789 -2.935789 \n#>        17        18        19        20        21        22        23        24 \n#> -1.963340 -1.963340 -2.273598 -1.963340 -2.273598 -2.273598 -2.273598 -1.963340 \n#>        25 \n#> -1.963340\n```\n\n\n:::\n\n```{.r .cell-code}\n# Add predicted  value to the new data\ndata_new$predicted<-predict(model3,data_new)\n\n# View head 10 of the data_new\nhead(data_new[,c(1:11,23)], 10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> # A tibble: 10 x 12\n#>      age arcus behpat   bmi chd69  chol   dbp dibpat height    id lnsbp\n#>    <dbl> <dbl> <chr>  <dbl> <fct> <dbl> <dbl> <fct>   <dbl> <dbl> <dbl>\n#>  1    51     1 A1      22.1 No      173    80 Type A     69 22057  4.84\n#>  2    41     0 A1      23.0 No      212    84 Type A     70 11389  4.87\n#>  3    54     0 A1      23.8 No      214    76 Type A     67 21071  4.77\n#>  4    55     1 A1      25.1 No      192    76 Type A     72 13371  4.75\n#>  5    44     0 A1      24.4 No      181    80 Type A     72 11249  4.79\n#>  6    55     0 A1      26.1 No      185    68 Type A     71  3005  4.70\n#>  7    54     0 A1      21.7 No      252    68 Type A     68 12256  4.75\n#>  8    46     0 A1      23.9 No      251    74 Type A     74 11358  4.79\n#>  9    43     0 A1      25.1 No      213    82 Type A     68 21052  4.80\n#> 10    45     0 A1      22.2 No      226    84 Type A     72  3004  4.79\n#> # i 1 more variable: predicted <dbl>\n```\n\n\n:::\n:::\n\n\n### Interpretation\n\nThe `summary(model3)` output reports the log-odds coefficient for `agec`, its standard error, z-value, and p-value. Exponentiating the coefficient (`exp(model3$coefficients)`) converts it to an odds ratio: an OR greater than 1 indicates that CHD (`chd69`) becomes more likely as age category increases, while an OR less than 1 would indicate lower odds. A 95% confidence interval (`exp(confint(model3))`) that excludes 1 supports a statistically significant association at the 0.05 level. The `plot(model3)` diagnostic panels help check for influential observations and deviance residual patterns, and `performance::model_performance(model3)` reports fit statistics (AIC, BIC, and pseudo-R²) that are most useful for comparing this model against alternative specifications rather than for interpreting in isolation.\n\n## **Multivariable Logistic regression**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmodel4<-glm(formula = chd69~sbp+agec+smoke+bmi,family = binomial(link=\"logit\"),data = data)\nsummary(model4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> \n#> Call:\n#> glm(formula = chd69 ~ sbp + agec + smoke + bmi, family = binomial(link = \"logit\"), \n#>     data = data)\n#> \n#> Coefficients:\n#>              Estimate Std. Error z value Pr(>|z|)    \n#> (Intercept) -7.486446   0.739539 -10.123  < 2e-16 ***\n#> sbp          0.021540   0.003965   5.433 5.55e-08 ***\n#> agec41-45   -0.198522   0.233160  -0.851 0.394523    \n#> agec46-50    0.410001   0.226473   1.810 0.070238 .  \n#> agec51-55    0.648548   0.232726   2.787 0.005324 ** \n#> agec56-60    0.916249   0.263741   3.474 0.000513 ***\n#> smokeYes     0.707014   0.137817   5.130 2.90e-07 ***\n#> bmi          0.063477   0.025155   2.523 0.011621 *  \n#> ---\n#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n#> \n#> (Dispersion parameter for binomial family taken to be 1)\n#> \n#>     Null deviance: 1781.2  on 3153  degrees of freedom\n#> Residual deviance: 1669.9  on 3146  degrees of freedom\n#> AIC: 1685.9\n#> \n#> Number of Fisher Scoring iterations: 5\n```\n\n\n:::\n\n```{.r .cell-code}\n# Model plots in 2 by 2 arrangement\npar(mfrow=c(2,2))\nplot(model4)\n```\n\n::: {.cell-output-display}\n![](Categorical_data_analysis2_files/figure-pdf/unnamed-chunk-15-1.pdf){fig-align='center' fig-pos='H' width=85%}\n:::\n\n```{.r .cell-code}\n# Determine odds ratio and its 95% CI (process-1)\nexp(model4$coefficients) # odds ratio only\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>  (Intercept)          sbp    agec41-45    agec46-50    agec51-55    agec56-60 \n#> 0.0005606319 1.0217736501 0.8199414926 1.5068188262 1.9127607823 2.4998947365 \n#>     smokeYes          bmi \n#> 2.0279273793 1.0655352259\n```\n\n\n:::\n\n```{.r .cell-code}\nexp(confint(model4)) # 95% CI of odds ratio\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>                    2.5 %      97.5 %\n#> (Intercept) 0.0001308395 0.002381673\n#> sbp         1.0137779145 1.029679363\n#> agec41-45   0.5226108925 1.307997875\n#> agec46-50   0.9752681039 2.376867146\n#> agec51-55   1.2215696287 3.051031660\n#> agec56-60   1.4915880104 4.210310466\n#> smokeYes    1.5511794080 2.664123783\n#> bmi         1.0140242588 1.119186342\n```\n\n\n:::\n\n```{.r .cell-code}\ncbind(oddsratio=exp(model4$coefficients),CI=exp(confint(model4))) # odds ratio with 95% CI\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>                oddsratio        2.5 %      97.5 %\n#> (Intercept) 0.0005606319 0.0001308395 0.002381673\n#> sbp         1.0217736501 1.0137779145 1.029679363\n#> agec41-45   0.8199414926 0.5226108925 1.307997875\n#> agec46-50   1.5068188262 0.9752681039 2.376867146\n#> agec51-55   1.9127607823 1.2215696287 3.051031660\n#> agec56-60   2.4998947365 1.4915880104 4.210310466\n#> smokeYes    2.0279273793 1.5511794080 2.664123783\n#> bmi         1.0655352259 1.0140242588 1.119186342\n```\n\n\n:::\n\n```{.r .cell-code}\n# Generate sleek tables from the model and export\nsjPlot::tab_model(model4)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table style=\"border-collapse:collapse; border:none;\">\n<tr>\n<th style=\"border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm;  text-align:left; \">&nbsp;</th>\n<th colspan=\"3\" style=\"border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; \">chd 69</th>\n</tr>\n<tr>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  text-align:left; \">Predictors</td>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  \">Odds Ratios</td>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  \">CI</td>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  \">p</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">(Intercept)</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.00</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.00&nbsp;&ndash;&nbsp;0.00</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \"><strong>&lt;0.001</strong></td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">sbp</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">1.02</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">1.01&nbsp;&ndash;&nbsp;1.03</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \"><strong>&lt;0.001</strong></td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">agec41&#45;45</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.82</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.52&nbsp;&ndash;&nbsp;1.31</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.395</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">agec46&#45;50</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">1.51</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.98&nbsp;&ndash;&nbsp;2.38</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.070</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">agec51&#45;55</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">1.91</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">1.22&nbsp;&ndash;&nbsp;3.05</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \"><strong>0.005</strong></td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">agec56&#45;60</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">2.50</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">1.49&nbsp;&ndash;&nbsp;4.21</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \"><strong>0.001</strong></td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">smoke [Yes]</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">2.03</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">1.55&nbsp;&ndash;&nbsp;2.66</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \"><strong>&lt;0.001</strong></td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">bmi</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">1.07</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">1.01&nbsp;&ndash;&nbsp;1.12</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \"><strong>0.012</strong></td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm; border-top:1px solid;\">Observations</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;\" colspan=\"3\">3154</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;\">R<sup>2</sup> Tjur</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;\" colspan=\"3\">0.039</td>\n</tr>\n\n</table>\n\n`````\n:::\n\n```{.r .cell-code}\ngtsummary::tbl_regression(model4,exponentiate = T) |>\n  gtsummary::as_hux_xlsx(\"regression_table.xlsx\")\n\n# Check model diagnostics\nperformance::check_model(model4)\n\n\n# Determine the AIC, BIC, RMSE of the model\nperformance::model_performance(model4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> # Indices of model performance\n#> \n#> AIC    |   AICc |    BIC | Tjur's R2 |  RMSE | Sigma | Log_loss | Score_log\n#> ---------------------------------------------------------------------------\n#> 1685.9 | 1685.9 | 1734.3 |     0.039 | 0.268 |     1 |    0.265 |   -22.089\n#> \n#> AIC    | Score_spherical |   PCP\n#> --------------------------------\n#> 1685.9 |           0.004 | 0.856\n```\n\n\n:::\n\n```{.r .cell-code}\n# Prediction of new_data\ndata_new<-data[seq(4,100,4),]\n\n# predict() function helps to predict the results from in the new data\npredict(model4,data_new)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>         1         2         3         4         5         6         7         8 \n#> -2.717921 -2.720629 -2.785170 -2.746757 -3.550708 -2.106103 -2.959220 -2.975913 \n#>         9        10        11        12        13        14        15        16 \n#> -3.464736 -2.981423 -3.168022 -2.526317 -2.946652 -2.522953 -2.858947 -2.165150 \n#>        17        18        19        20        21        22        23        24 \n#> -2.781031 -2.350442 -2.244942 -1.915825 -3.056847 -1.675013 -2.197552 -2.204070 \n#>        25 \n#> -2.038848\n```\n\n\n:::\n\n```{.r .cell-code}\n# Add predicted  value to the new data\ndata_new$predicted<-predict(model4,data_new)\n```\n:::\n\n\n### Interpretation\n\nIn the multivariable model, each exponentiated coefficient represents the odds ratio for that predictor holding the other predictors (`sbp`, `agec`, `smoke`, `bmi`) constant. This adjustment is what distinguishes the multivariable estimates from the crude (unadjusted) odds ratio produced by the univariate model. `performance::check_model(model4)` produces a fuller diagnostic suite (linearity, homogeneity of variance proxies, influential observations, and collinearity) than the base `plot()` method, and is generally preferred for multivariable models.\n\n## **Interaction in logistic regression**\n\nAn interaction term tests whether the effect of one predictor on the outcome depends on the level of another predictor. In `model5`, the term `sbp*agec` expands to the main effects of `sbp` and `agec` plus their product term (`sbp:agec`), allowing the effect of systolic blood pressure on CHD risk to vary across age categories.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmodel5<-glm(formula = chd69~sbp*agec+smoke+bmi,family = binomial(link=\"logit\"),data = data)\nsummary(model5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> \n#> Call:\n#> glm(formula = chd69 ~ sbp * agec + smoke + bmi, family = binomial(link = \"logit\"), \n#>     data = data)\n#> \n#> Coefficients:\n#>                Estimate Std. Error z value Pr(>|z|)    \n#> (Intercept)   -4.541067   1.924725  -2.359  0.01831 *  \n#> sbp           -0.002297   0.015050  -0.153  0.87868    \n#> agec41-45     -3.283702   2.174693  -1.510  0.13105    \n#> agec46-50     -2.905318   2.149535  -1.352  0.17650    \n#> agec51-55     -2.317372   2.123822  -1.091  0.27521    \n#> agec56-60     -3.212210   2.356622  -1.363  0.17286    \n#> smokeYes       0.719736   0.138355   5.202 1.97e-07 ***\n#> bmi            0.066820   0.025373   2.633  0.00845 ** \n#> sbp:agec41-45  0.024202   0.016989   1.425  0.15428    \n#> sbp:agec46-50  0.025912   0.016763   1.546  0.12214    \n#> sbp:agec51-55  0.023324   0.016507   1.413  0.15766    \n#> sbp:agec56-60  0.031794   0.018064   1.760  0.07838 .  \n#> ---\n#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n#> \n#> (Dispersion parameter for binomial family taken to be 1)\n#> \n#>     Null deviance: 1781.2  on 3153  degrees of freedom\n#> Residual deviance: 1666.4  on 3142  degrees of freedom\n#> AIC: 1690.4\n#> \n#> Number of Fisher Scoring iterations: 6\n```\n\n\n:::\n\n```{.r .cell-code}\n# Odds ratio and 95% CI\nexp(model5$coefficients)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>   (Intercept)           sbp     agec41-45     agec46-50     agec51-55 \n#>    0.01066203    0.99770539    0.03748920    0.05473139    0.09853220 \n#>     agec56-60      smokeYes           bmi sbp:agec41-45 sbp:agec46-50 \n#>    0.04026753    2.05389046    1.06910320    1.02449693    1.02625110 \n#> sbp:agec51-55 sbp:agec56-60 \n#>    1.02359811    1.03230533\n```\n\n\n:::\n\n```{.r .cell-code}\nexp(confint(model5))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>                      2.5 %    97.5 %\n#> (Intercept)   0.0002646532 0.5152048\n#> sbp           0.9673878390 1.0264165\n#> agec41-45     0.0004896772 2.5299152\n#> agec46-50     0.0007409633 3.4623276\n#> agec51-55     0.0013989779 5.9060431\n#> agec56-60     0.0003618415 3.8041663\n#> smokeYes      1.5695268215 2.7012457\n#> bmi           1.0170134637 1.1234531\n#> sbp:agec41-45 0.9916460076 1.0602057\n#> sbp:agec46-50 0.9939356825 1.0616798\n#> sbp:agec51-55 0.9919077874 1.0584460\n#> sbp:agec56-60 0.9971848540 1.0705886\n```\n\n\n:::\n\n```{.r .cell-code}\ncbind(oddsratio=exp(model5$coefficients),CI=exp(confint(model5)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>                oddsratio        2.5 %    97.5 %\n#> (Intercept)   0.01066203 0.0002646532 0.5152048\n#> sbp           0.99770539 0.9673878390 1.0264165\n#> agec41-45     0.03748920 0.0004896772 2.5299152\n#> agec46-50     0.05473139 0.0007409633 3.4623276\n#> agec51-55     0.09853220 0.0013989779 5.9060431\n#> agec56-60     0.04026753 0.0003618415 3.8041663\n#> smokeYes      2.05389046 1.5695268215 2.7012457\n#> bmi           1.06910320 1.0170134637 1.1234531\n#> sbp:agec41-45 1.02449693 0.9916460076 1.0602057\n#> sbp:agec46-50 1.02625110 0.9939356825 1.0616798\n#> sbp:agec51-55 1.02359811 0.9919077874 1.0584460\n#> sbp:agec56-60 1.03230533 0.9971848540 1.0705886\n```\n\n\n:::\n:::\n\n\n::: callout-tip\nWhen an interaction term is included, the main-effect odds ratios for `sbp` and `agec` no longer have a simple standalone interpretation — they represent the effect only when the other interacting variable is held at its reference level (or zero). To interpret the joint effect, compute the combined odds ratio at specific, meaningful combinations of both variables (e.g., using the `emmeans` or `ggeffects` packages), or test whether the interaction coefficient itself is statistically significant.\n:::\n\n**Interpretation:** A significant p-value for the `sbp:agec` interaction term indicates that the relationship between systolic blood pressure and CHD risk differs across age categories, and the model should be interpreted and reported with that interaction in mind rather than through separate main-effect odds ratios.\n\n# Extension of Logistic regression\n\n\n\nThere are multiple extensions of logistic regression. Some of them are as follows:\n\n1.  Exact logistic regression\n2.  Firth Penalization logistic regression\n3.  Generalized estimating equation\n4.  Multinomial logistic regression\n5.  Ordinal logistic regression\n\nThe details of each type of logistic regression are given below:\n\n## Exact logistic regression\n\nExact logistic regression is an extension of logistic regression in which log odds of the binary outcome is modeled as a linear combination of the predictor variables. It is used in the following situations:\n\n1.  When the sample size is too small for a regular logistic regression (which uses the standard maximum-likelihood-based estimator)\n2.  When some of the cells formed by the outcome and categorical predictor variable have zero observations.\n3.  When sample size is adequate but the event is rare (sparse data)\n\nThe estimates given by exact logistic regression do not depend on asymptotic results.\n\nLets take a dataset and work on it\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndat <- read.table(text = \"\nSN Complication Procedure\n1 Yes Old\n2 Yes Old\n3 Yes Old\n4 Yes Old\n5 Yes Old\n6 No New\n7 No New\n8 No New\n9 No New\n10 No New\n11 No New\n12 No New\n13 No New\n14 No New\n15 No New\n16 No New\n17 No New\n18 No New\n19 No New\n20 No New\n21 No New\n22 No New\n23 No New\n24 No New\n25 No New\n26 No New\n27 No New\n28 No New\n29 No New\n31 No New\n32 No New\n33 No New\n34 No New\n35 No New\n36 No New\n37 No Old\n38 No Old\n39 No Old\n40 No Old\n41 No Old\n42 No Old\n43 No Old\n44 No Old\n45 No Old\n46 No Old\n47 No Old\n48 No Old\n49 No Old\n50 No Old\n51 No Old\n52 No Old\n53 No Old\n54 No Old\n55 No Old\n56 No Old\n57 No Old\n58 No Old\n59 No Old\n60 No Old\n61 No Old\n\", header = TRUE, stringsAsFactors = FALSE)\n```\n:::\n\n\nLets generate a table between complication and procedure in the dataset.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntable(dat$Complication, dat$Procedure)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>      \n#>       New Old\n#>   No   30  25\n#>   Yes   0   5\n```\n\n\n:::\n:::\n\n\nCode for exact logistic regression in R\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Prepare data\ndat1 <- data.frame(procedure = c(\"New\", \"Old\"), complication = c(0, 5), ntrials = c(30, 30))\ndat1$procedure <- factor(dat1$procedure, levels =c(\"Old\", \"New\"), labels=c(\"Old\", \"New\") )  # Ensure 'procedure' is a factor\n\n# Fit the empirical logistic regression model\nmodel <- elrm(formula = complication/ntrials ~ procedure, r=2,\n               interest = ~procedure, \n               iter = 22000, \n               dataset = dat1, \n               burnIn = 2000)\n\n# Summarize the results\nsummary(model)\n```\n:::\n\n\nIn exact logistic regression there is complete separation, we have to use firth penalized method.\n\n## Firth Penalized Method\n\nIt is a simple solution that can mitigate the bias caused by rare events in a dataset. It is applicable in the case of complete separation. Complete separation or perfect separation is the condition where one covariate/explanatory variable always or never occurs with the event of interest or outcome variable. It is seen most often when the event is rare, but it can also occur in non-rare events and even in large datasets. The evidence of complete separation includes:\n\n1.  Infinite estimates\n\n2.  Large standard error\n\n3.  Poor fit\n\nFirth logistic regression can be employed to handle complete separation by introducing penalty terms. It is more robust than traditional logistic regression in the presence of rare events or small sample sizes.\n\nIn order to use this in R, we can use logistf package, which includes the `logistf()` function.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(logistf)\n\n# prepare data \ndat$Complication<-as.factor(dat$Complication)\ndat$Procedure<-as.factor(dat$Procedure)\nmodel <- logistf(Complication~Procedure,data = dat)\n\nsummary(model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> logistf(formula = Complication ~ Procedure, data = dat)\n#> \n#> Model fitted by Penalized ML\n#> Coefficients:\n#>                   coef se(coef) lower 0.95 upper 0.95     Chisq            p\n#> (Intercept)  -4.110874 1.425754 -8.9524616  -2.153841 37.856099 7.615991e-10\n#> ProcedureOld  2.576944 1.501269  0.3247434   7.472101  5.322758 2.104867e-02\n#>              method\n#> (Intercept)       2\n#> ProcedureOld      2\n#> \n#> Method: 1-Wald, 2-Profile penalized log-likelihood, 3-None\n#> \n#> Likelihood ratio test=5.322758 on 1 df, p=0.02104867, n=60\n#> Wald test = 18.95857 on 1 df, p = 1.335876e-05\n```\n\n\n:::\n\n```{.r .cell-code}\nsjPlot::tab_model(model)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table style=\"border-collapse:collapse; border:none;\">\n<tr>\n<th style=\"border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm;  text-align:left; \">&nbsp;</th>\n<th colspan=\"3\" style=\"border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; \">Complication</th>\n</tr>\n<tr>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  text-align:left; \">Predictors</td>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  \">Odds Ratios</td>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  \">CI</td>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  \">p</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">(Intercept)</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.02</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.00&nbsp;&ndash;&nbsp;0.27</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \"><strong>&lt;0.001</strong></td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">Procedure [Old]</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">13.16</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.69&nbsp;&ndash;&nbsp;249.48</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \"><strong>0.021</strong></td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm; border-top:1px solid;\">Observations</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;\" colspan=\"3\">60</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;\">R<sup>2</sup></td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;\" colspan=\"3\">0.088</td>\n</tr>\n\n</table>\n\n`````\n:::\n:::\n\n\n## Generalized Estimating Equations (GEE)\n\n### Introduction\n\nGeneralized Estimating Equations (GEE) extend the generalized linear model to correlated or clustered data, such as repeated measurements on the same subject over time, or observations nested within clusters (e.g., patients within clinics). Standard logistic regression assumes independent observations; when that assumption is violated, ignoring the correlation produces standard errors that are too small (or occasionally too large), leading to incorrect inference even though the coefficient estimates themselves may remain roughly unbiased.\n\nGEE addresses this by specifying a **working correlation structure** (e.g., independence, exchangeable, autoregressive AR(1), or unstructured) for the repeated observations within a cluster, and then uses a robust \"sandwich\" variance estimator that gives valid standard errors even if the working correlation structure is misspecified.\n\nUnlike mixed-effects (random-effects) models, which give subject-specific (\"conditional\") interpretations, GEE coefficients have a **population-averaged** interpretation: the odds ratio reflects the average effect of a predictor across the population, marginal over the repeated measurements.\n\n### When to use GEE\n\n1.  The outcome is measured repeatedly on the same subjects (longitudinal data) or subjects are clustered (e.g., by clinic, family, or region).\n2.  The scientific question concerns the population-averaged effect of predictors rather than subject-specific effects.\n3.  The primary interest is in correct standard errors and hypothesis tests rather than in modeling between-subject variability directly.\n\n### Fitting a GEE model in R\n\nWe use the `geepack` package, which provides the `geeglm()` function. We will use the classic `respiratory` dataset included with `geepack`: a multi-center clinical trial in which patients were followed over four visits, with a binary respiratory status outcome recorded at each visit (clustered by patient `id`).\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(geepack)\n\n# load the built-in respiratory dataset (repeated measures per patient)\ndata(respiratory)\nhead(respiratory)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>   center id treat sex age baseline visit outcome\n#> 1      1  1     P   M  46        0     1       0\n#> 2      1  1     P   M  46        0     2       0\n#> 3      1  1     P   M  46        0     3       0\n#> 4      1  1     P   M  46        0     4       0\n#> 5      1  2     P   M  28        0     1       0\n#> 6      1  2     P   M  28        0     2       0\n```\n\n\n:::\n\n```{.r .cell-code}\n# Fit a GEE logistic model with an exchangeable working correlation,\n# since repeated visits within the same patient are correlated\ngee_model <- geeglm(outcome ~ treat + sex + baseline + age,\n                     id = id,\n                     data = respiratory,\n                     family = binomial(link = \"logit\"),\n                     corstr = \"exchangeable\")\n\ngee_model_summary<-summary(gee_model)\n\n# Odds ratio and 95% CI\ncoef_est <- gee_model_summary$coefficients[, \"Estimate\"]\nse <- gee_model_summary$coefficients[, \"Std.err\"]\n\nlower <- coef_est - 1.96 * se\nupper <- coef_est + 1.96 * se\n\nCI <- cbind(Estimate = coef_est,\n            Lower95 = lower,\n            Upper95 = upper)\n\nexp(CI)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>       Estimate   Lower95    Upper95\n#> [1,] 2.1091310 0.5226750  8.5108980\n#> [2,] 0.2772380 0.1393793  0.5514513\n#> [3,] 0.7623601 0.3329734  1.7454632\n#> [4,] 7.3645242 3.8773182 13.9880747\n#> [5,] 0.9863820 0.9609202  1.0125184\n```\n\n\n:::\n:::\n\n\n::: callout-tip\nModel comparison statistics such as AIC/BIC are not defined for GEE models in the usual likelihood-based sense (GEE is estimated via quasi-likelihood, not full likelihood). Use the QIC (Quasi-likelihood under the Independence model Criterion) instead, available via `MuMIn::QIC()` or `geepack::QIC()` depending on package version, to compare working correlation structures or nested predictor sets.\n:::\n\n**Interpretation:** The exponentiated coefficients from `gee_model` are population-averaged odds ratios. For example, the odds ratio for `treat` represents how much more (or less) likely a patient is to have the outcome of interest under the active treatment versus control, averaged across the population and adjusted for `sex`, `baseline` status, and `age`, while accounting for the within-patient correlation across the four visits.\n\n## Multinomial Logistic regression Analysis\n\n### Introduction\n\nIt is the extension of the logistic regression model to accommodate a categorical outcome variable that has more than two categories. The multinomial logistic regression model for an outcome variable with G levels is as follows:\n\n$$ ln(\\frac{P(Y=g|X)} {P(Y=0|X)}) = \\alpha_k + \\beta_1 X_1 +\\beta_2X_2 +\\beta_3X_3 +\\dots +\\beta_gX_g $$\n\nwhere g =1, 2, 3,... G-1\n\nX are the independent variables\n\nIf there are n categories in the outcome variable, then there will be n-1 odds like ratio comparing with one reference group to each of the other categories.\n\nThe exponentiated coefficient obtained from multinomial logistic regression is not a true odds ratio in the classical sense — it is an \"odds-like\" ratio comparing category *g* to the reference category, since it does not meet the strict definition of odds (ratio of success to failure) that applies to a two-category outcome.\n\n### Assumptions\n\n-   It assumes the outcome variable as nominal\n\n-   It doesn't account ordering in the outcome variables\n\nFor the demonstration of multinomial logistic regression analysis, we will be using data from NDHS 2021. The sample data used can be downloaded from the [link here](https://drive.google.com/file/d/10ZTS_xTzaG432oBly6OFp2PvHBOgOpfO). The list of variables are as follows:\n\n-   `Combined2_1`: It is the outcome variable with four levels: Normal/Anemia only/Undernutrition Only/Coexistence\n\n-   `Wealth_quintile`: Wealth quintile\n\n-   `motheredu` : Mother's education\n\n-   `housedecision`: Mother's participation in household decision making\n\n-   `health_program`: Exposure of mother to health related program in TV/radio\n\n-   `age2`: Age of child\n\n-   `Sex`: Sex of child\n\n-   `Place_of_residence`: Place of residence of child\n\n-   `fatheredu`: Father's education level\n\n-   `Ecological_region`: Ecological belt\n\n-   `parity`: Parity\n\n-   `maternal_nut`: Mother's nutritional status\n\n-   `nt_wm_any_anem`: Mother's anemia status\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# load dataset\ndt<-readRDS(\"D:/Epi Biostat with R/Biostat_with_R/Section2/Categorical data analysis/Datasets/dt.RDS\")\n\n# load libraries\nlibrary(nnet) # \"multinom()\" function is from nnet\nlibrary(sjPlot) # to make ready-made tables and charts\nlibrary(ggeffects) # to plot models\nlibrary(performance) # to check assumptions\n```\n:::\n\n\nThe code to use multinomial logistic regression is as follows:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmdel1<-multinom(formula = Combined2_1~Wealth_quintile+motheredu+housedecision+health_program+age2+Sex+Place_of_residence+fatheredu+Ecological_region+parity+maternal_nut+nt_wm_any_anem, data=dt)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> # weights:  92 (66 variable)\n#> initial  value 2617.323754 \n#> iter  10 value 2356.751620\n#> iter  20 value 2310.420979\n#> iter  30 value 2290.536865\n#> iter  40 value 2289.133329\n#> iter  50 value 2289.050213\n#> final  value 2289.046139 \n#> converged\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(mdel1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> Call:\n#> multinom(formula = Combined2_1 ~ Wealth_quintile + motheredu + \n#>     housedecision + health_program + age2 + Sex + Place_of_residence + \n#>     fatheredu + Ecological_region + parity + maternal_nut + nt_wm_any_anem, \n#>     data = dt)\n#> \n#> Coefficients:\n#>                     (Intercept) Wealth_quintilepoorer Wealth_quintilemiddle\n#> Anemia only           0.9854172          -0.010407023            0.04834015\n#> Undernutrition only  -0.6477979          -0.003986444           -0.09799603\n#> Coexistence           0.5766046          -0.184151862           -0.44344604\n#>                     Wealth_quintilericher Wealth_quintilerichest\n#> Anemia only                   -0.04228353             -0.6770043\n#> Undernutrition only           -0.74235271             -0.8526707\n#> Coexistence                   -0.67105714             -0.8768949\n#>                     motheredubasic  mothereduSecondary and Higher\n#> Anemia only              0.01146830                     0.1501191\n#> Undernutrition only      0.04965992                    -0.1225593\n#> Coexistence             -0.33018654                    -0.6422108\n#>                     housedecisionParticipation health_programYes\n#> Anemia only                         -0.3730769       -0.06091002\n#> Undernutrition only                 -0.3526384       -0.13557889\n#> Coexistence                         -0.3383432       -0.04715707\n#>                     age213-36 months age237-59 months   Sexfemale\n#> Anemia only               -1.0851727        -2.003195 -0.08409981\n#> Undernutrition only        1.2476138         1.258172 -0.03024442\n#> Coexistence               -0.4089829        -1.507620 -0.09316537\n#>                     Place_of_residencerural fatheredubasic \n#> Anemia only                     -0.15613950      -0.1946993\n#> Undernutrition only              0.02617873      -0.1095205\n#> Coexistence                      0.17811935      -0.1783381\n#>                     fathereduSecondary and Higher Ecological_regionhill\n#> Anemia only                           -0.46807421            -0.3138077\n#> Undernutrition only                   -0.17365568            -0.5792796\n#> Coexistence                           -0.04204977            -0.7531653\n#>                     Ecological_regionterai parityPrimipara parityMultipara\n#> Anemia only                     0.26819046      0.42232303      0.56309415\n#> Undernutrition only            -0.41830902     -0.58313145     -0.06466644\n#> Coexistence                    -0.08372189      0.02709827      0.54950630\n#>                     maternal_nutOverwt obese maternal_nutthin nt_wm_any_anemYes\n#> Anemia only                       0.26594352       0.05020825         0.4621247\n#> Undernutrition only              -0.02098865       0.38562048         0.2059181\n#> Coexistence                      -0.04115914       0.42109672         0.7761082\n#> \n#> Std. Errors:\n#>                     (Intercept) Wealth_quintilepoorer Wealth_quintilemiddle\n#> Anemia only           0.2738739             0.1919641             0.2066312\n#> Undernutrition only   0.3659968             0.1960567             0.2182094\n#> Coexistence           0.3018701             0.2168357             0.2463465\n#>                     Wealth_quintilericher Wealth_quintilerichest\n#> Anemia only                     0.2241009              0.2650318\n#> Undernutrition only             0.2682186              0.3096395\n#> Coexistence                     0.2798183              0.3337100\n#>                     motheredubasic  mothereduSecondary and Higher\n#> Anemia only               0.1920722                     0.2144264\n#> Undernutrition only       0.1932469                     0.2245962\n#> Coexistence               0.2024112                     0.2389557\n#>                     housedecisionParticipation health_programYes\n#> Anemia only                          0.1543438         0.1500803\n#> Undernutrition only                  0.1691325         0.1616194\n#> Coexistence                          0.1769248         0.1825790\n#>                     age213-36 months age237-59 months Sexfemale\n#> Anemia only                0.1925852        0.2021013 0.1234745\n#> Undernutrition only        0.4180860        0.4161420 0.1337545\n#> Coexistence                0.2395562        0.2545531 0.1457525\n#>                     Place_of_residencerural fatheredubasic \n#> Anemia only                       0.1327872       0.2443898\n#> Undernutrition only               0.1433533       0.2504912\n#> Coexistence                       0.1561835       0.2601701\n#>                     fathereduSecondary and Higher Ecological_regionhill\n#> Anemia only                             0.2631055             0.2567353\n#> Undernutrition only                     0.2718673             0.2344684\n#> Coexistence                             0.2836707             0.2598943\n#>                     Ecological_regionterai parityPrimipara parityMultipara\n#> Anemia only                      0.2812538       0.1620888       0.1447750\n#> Undernutrition only              0.2706417       0.2100337       0.1914079\n#> Coexistence                      0.2953945       0.1865385       0.1633622\n#>                     maternal_nutOverwt obese maternal_nutthin nt_wm_any_anemYes\n#> Anemia only                        0.1581779        0.1923029         0.1369080\n#> Undernutrition only                0.1815454        0.1968095         0.1520609\n#> Coexistence                        0.2090812        0.2022801         0.1574196\n#> \n#> Residual Deviance: 4578.092 \n#> AIC: 4704.092\n```\n\n\n:::\n:::\n\n\nIn order to check assumptions of the model we can use performance package.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# check for multi-collinearity\nperformance::check_collinearity(mdel1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> # Check for Multicollinearity\n#> \n#> Low Correlation\n#> \n#>               Term     VIF VIF 95% CI adj. VIF Tolerance Tolerance 95% CI\n#>      housedecision  -14.21                         -0.07                 \n#>     health_program   -1.70                         -0.59                 \n#>               age2  -11.44                         -0.09                 \n#>                Sex   -5.11                         -0.20                 \n#>          fatheredu -124.78                     -8.01e-03                 \n#>  Ecological_region  -57.09                         -0.02                 \n#>             parity -205.04                     -4.88e-03                 \n#>       maternal_nut   -1.22                         -0.82                 \n#>     nt_wm_any_anem  -16.32                         -0.06                 \n#> \n#> Moderate Correlation\n#> \n#>                Term  VIF     VIF 95% CI adj. VIF Tolerance Tolerance 95% CI\n#>           motheredu 5.10 [ 4.71,  5.52]     2.26      0.20     [0.18, 0.21]\n#>  Place_of_residence 7.91 [ 7.30,  8.59]     2.81      0.13     [0.12, 0.14]\n#> \n#> High Correlation\n#> \n#>             Term   VIF     VIF 95% CI adj. VIF Tolerance Tolerance 95% CI\n#>  Wealth_quintile 38.58 [35.41, 42.04]     6.21      0.03     [0.02, 0.03]\n```\n\n\n:::\n:::\n\n\nWe can use `tab_model()` from the sjPlot package to make a ready-made table and `plot_model()` from sjPlot to create a sleek chart.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# readymade table\ntab_model(mdel1)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table style=\"border-collapse:collapse; border:none;\">\n<tr>\n<th style=\"border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm;  text-align:left; \">&nbsp;</th>\n<th colspan=\"4\" style=\"border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; \">Combined 2 1</th>\n</tr>\n<tr>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  text-align:left; \">Predictors</td>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  \">Odds Ratios</td>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  \">CI</td>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  \">p</td>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  \">Response</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">(Intercept)</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">2.68</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">1.57&nbsp;&ndash;&nbsp;4.58</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \"><strong>&lt;0.001</strong></td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">Anemia only</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">wealth index combined:<br>poorer</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.99</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.68&nbsp;&ndash;&nbsp;1.44</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.957</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">Anemia only</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">wealth index combined:<br>middle</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">1.05</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.70&nbsp;&ndash;&nbsp;1.57</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.815</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">Anemia only</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">wealth index combined:<br>richer</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.96</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.62&nbsp;&ndash;&nbsp;1.49</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.850</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">Anemia only</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">wealth index combined:<br>richest</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.51</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.30&nbsp;&ndash;&nbsp;0.85</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \"><strong>0.011</strong></td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">Anemia only</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">motheredu: basic</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">1.01</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.69&nbsp;&ndash;&nbsp;1.47</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.952</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">Anemia only</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">motheredu: Secondary and<br>Higher</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">1.16</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.76&nbsp;&ndash;&nbsp;1.77</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.484</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">Anemia only</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">housedecision:<br>Participation</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.69</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.51&nbsp;&ndash;&nbsp;0.93</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \"><strong>0.016</strong></td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">Anemia only</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">health program: Yes</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.94</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.70&nbsp;&ndash;&nbsp;1.26</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.685</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">Anemia only</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">age213&#45;36 months</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.34</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.23&nbsp;&ndash;&nbsp;0.49</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \"><strong>&lt;0.001</strong></td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">Anemia only</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">age237&#45;59 months</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.13</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.09&nbsp;&ndash;&nbsp;0.20</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \"><strong>&lt;0.001</strong></td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">Anemia only</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">sex: female</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.92</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.72&nbsp;&ndash;&nbsp;1.17</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.496</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">Anemia only</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">type of place of<br>residence: rural</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.86</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.66&nbsp;&ndash;&nbsp;1.11</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.240</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">Anemia only</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">fatheredu: basic</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.82</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.51&nbsp;&ndash;&nbsp;1.33</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.426</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">Anemia only</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">fatheredu: Secondary and<br>Higher</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.63</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.37&nbsp;&ndash;&nbsp;1.05</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.075</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">Anemia only</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">ecological region: hill</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.73</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.44&nbsp;&ndash;&nbsp;1.21</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.222</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">Anemia only</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">ecological region: terai</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">1.31</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.75&nbsp;&ndash;&nbsp;2.27</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.340</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">Anemia only</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">parity: Primipara</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">1.53</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">1.11&nbsp;&ndash;&nbsp;2.10</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \"><strong>0.009</strong></td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">Anemia only</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">parity: Multipara</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">1.76</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">1.32&nbsp;&ndash;&nbsp;2.33</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \"><strong>&lt;0.001</strong></td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">Anemia only</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">maternal nut: Overwt<br>obese</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">1.30</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.96&nbsp;&ndash;&nbsp;1.78</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.093</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">Anemia only</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">maternal nut: thin</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">1.05</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.72&nbsp;&ndash;&nbsp;1.53</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.794</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">Anemia only</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">Any anemia-women: Yes</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">1.59</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">1.21&nbsp;&ndash;&nbsp;2.08</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \"><strong>0.001</strong></td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">Anemia only</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">(Intercept)</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.52</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.26&nbsp;&ndash;&nbsp;1.07</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.077</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">Undernutrition only</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">wealth index combined:<br>poorer</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">1.00</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.68&nbsp;&ndash;&nbsp;1.46</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.984</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">Undernutrition only</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">wealth index combined:<br>middle</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.91</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.59&nbsp;&ndash;&nbsp;1.39</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.653</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">Undernutrition only</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">wealth index combined:<br>richer</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.48</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.28&nbsp;&ndash;&nbsp;0.81</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \"><strong>0.006</strong></td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">Undernutrition only</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">wealth index combined:<br>richest</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.43</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.23&nbsp;&ndash;&nbsp;0.78</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \"><strong>0.006</strong></td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">Undernutrition only</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">motheredu: basic</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">1.05</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.72&nbsp;&ndash;&nbsp;1.54</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.797</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">Undernutrition only</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">motheredu: Secondary and<br>Higher</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.88</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.57&nbsp;&ndash;&nbsp;1.37</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.585</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">Undernutrition only</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">housedecision:<br>Participation</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.70</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.50&nbsp;&ndash;&nbsp;0.98</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \"><strong>0.037</strong></td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">Undernutrition only</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">health program: Yes</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.87</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.64&nbsp;&ndash;&nbsp;1.20</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.402</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">Undernutrition only</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">age213&#45;36 months</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">3.48</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">1.53&nbsp;&ndash;&nbsp;7.91</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \"><strong>0.003</strong></td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">Undernutrition only</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">age237&#45;59 months</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">3.52</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">1.56&nbsp;&ndash;&nbsp;7.96</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \"><strong>0.003</strong></td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">Undernutrition only</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">sex: female</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.97</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.75&nbsp;&ndash;&nbsp;1.26</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.821</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">Undernutrition only</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">type of place of<br>residence: rural</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">1.03</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.77&nbsp;&ndash;&nbsp;1.36</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.855</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">Undernutrition only</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">fatheredu: basic</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.90</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.55&nbsp;&ndash;&nbsp;1.46</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.662</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">Undernutrition only</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">fatheredu: Secondary and<br>Higher</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.84</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.49&nbsp;&ndash;&nbsp;1.43</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.523</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">Undernutrition only</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">ecological region: hill</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.56</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.35&nbsp;&ndash;&nbsp;0.89</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \"><strong>0.014</strong></td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">Undernutrition only</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">ecological region: terai</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.66</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.39&nbsp;&ndash;&nbsp;1.12</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.122</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">Undernutrition only</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">parity: Primipara</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.56</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.37&nbsp;&ndash;&nbsp;0.84</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \"><strong>0.006</strong></td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">Undernutrition only</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">parity: Multipara</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.94</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.64&nbsp;&ndash;&nbsp;1.36</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.736</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">Undernutrition only</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">maternal nut: Overwt<br>obese</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.98</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.69&nbsp;&ndash;&nbsp;1.40</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.908</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">Undernutrition only</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">maternal nut: thin</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">1.47</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">1.00&nbsp;&ndash;&nbsp;2.16</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.050</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">Undernutrition only</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">Any anemia-women: Yes</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">1.23</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.91&nbsp;&ndash;&nbsp;1.66</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.176</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">Undernutrition only</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">(Intercept)</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">1.78</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.98&nbsp;&ndash;&nbsp;3.22</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.056</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">Coexistence</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">wealth index combined:<br>poorer</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.83</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.54&nbsp;&ndash;&nbsp;1.27</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.396</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">Coexistence</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">wealth index combined:<br>middle</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.64</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.40&nbsp;&ndash;&nbsp;1.04</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.072</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">Coexistence</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">wealth index combined:<br>richer</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.51</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.30&nbsp;&ndash;&nbsp;0.88</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \"><strong>0.017</strong></td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">Coexistence</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">wealth index combined:<br>richest</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.42</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.22&nbsp;&ndash;&nbsp;0.80</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \"><strong>0.009</strong></td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">Coexistence</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">motheredu: basic</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.72</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.48&nbsp;&ndash;&nbsp;1.07</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.103</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">Coexistence</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">motheredu: Secondary and<br>Higher</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.53</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.33&nbsp;&ndash;&nbsp;0.84</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \"><strong>0.007</strong></td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">Coexistence</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">housedecision:<br>Participation</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.71</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.50&nbsp;&ndash;&nbsp;1.01</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.056</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">Coexistence</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">health program: Yes</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.95</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.67&nbsp;&ndash;&nbsp;1.36</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.796</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">Coexistence</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">age213&#45;36 months</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.66</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.42&nbsp;&ndash;&nbsp;1.06</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.088</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">Coexistence</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">age237&#45;59 months</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.22</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.13&nbsp;&ndash;&nbsp;0.36</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \"><strong>&lt;0.001</strong></td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">Coexistence</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">sex: female</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.91</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.68&nbsp;&ndash;&nbsp;1.21</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.523</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">Coexistence</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">type of place of<br>residence: rural</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">1.19</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.88&nbsp;&ndash;&nbsp;1.62</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.254</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">Coexistence</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">fatheredu: basic</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.84</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.50&nbsp;&ndash;&nbsp;1.39</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.493</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">Coexistence</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">fatheredu: Secondary and<br>Higher</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.96</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.55&nbsp;&ndash;&nbsp;1.67</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.882</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">Coexistence</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">ecological region: hill</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.47</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.28&nbsp;&ndash;&nbsp;0.78</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \"><strong>0.004</strong></td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">Coexistence</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">ecological region: terai</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.92</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.52&nbsp;&ndash;&nbsp;1.64</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.777</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">Coexistence</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">parity: Primipara</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">1.03</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.71&nbsp;&ndash;&nbsp;1.48</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.885</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">Coexistence</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">parity: Multipara</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">1.73</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">1.26&nbsp;&ndash;&nbsp;2.39</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \"><strong>0.001</strong></td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">Coexistence</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">maternal nut: Overwt<br>obese</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.96</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.64&nbsp;&ndash;&nbsp;1.45</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.844</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">Coexistence</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">maternal nut: thin</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">1.52</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">1.02&nbsp;&ndash;&nbsp;2.27</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \"><strong>0.038</strong></td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">Coexistence</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">Any anemia-women: Yes</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">2.17</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">1.60&nbsp;&ndash;&nbsp;2.96</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \"><strong>&lt;0.001</strong></td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">Coexistence</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm; border-top:1px solid;\">Observations</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;\" colspan=\"4\">1888</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;\">R<sup>2</sup> / R<sup>2</sup> adjusted</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;\" colspan=\"4\">0.090 / 0.090</td>\n</tr>\n\n</table>\n\n`````\n:::\n\n```{.r .cell-code}\n# chart\nsjPlot::plot_model(mdel1,show.intercept = T, vline.color = \"black\", show.values = TRUE, terms = c(\"Wealth_quintilepoorer\",\"Wealth_quintilemiddle\", \"Wealth_quintilericher\",\"Wealth_quintilerichest\", \"motheredubasic\",\"mothereduSecondary and Higher\",  \"housedecisionParticipation\", \"health_programYes\" ),title = \"Factors associated with co-existence of undernutrition and anemia\", wrap.title = 1000)+\n  ggplot2::theme_bw()\n```\n\n::: {.cell-output-display}\n![](Categorical_data_analysis2_files/figure-pdf/unnamed-chunk-26-1.pdf){fig-align='center' fig-pos='H' width=85%}\n:::\n:::\n\n\n## Ordinal Logistic regression Analysis\n\n### Introduction\n\nOrdinal logistic regression, extension of logistic regression, is a statistical method used to analyze the relationship between an ordinal dependent variable and one or more independent variables. An ordinal variable is a categorical variable for which there is a clear ordering of the category levels (a variable with ordered categories, such as “low,” “medium,” and “high”). The explanatory variables may be either continuous or categorical.\n\nEstimating ordinal logistic regression models with statistical software is not difficult, but the interpretation of the model output can be cumbersome.It can be used to model outcomes such as satisfaction levels or grades. The goal is to predict the probability of an observation belonging to a certain category or a higher category, based on the values of the independent variables\n\n### Assumptions\n\nThere are five assumptions that when violated may result in invalid output. The five assumptions are:\n\n1.  The dependent variable is measured on an ordinal level.\n2.  One or more of the independent variables are either continuous, categorical or ordinal.\n3.  Independence of observations and the dependent variable should be mutually exclusive.\n4.  No multi-collinearity\n5.  Proportional Odds : a major assumption of ordinal logistic regression is the assumption of proportional odds: the effect of an independent variable is constant for each increase in the level of the response. Hence the output of an ordinal logistic regression will contain an intercept for each level of the response except one, and a single slope for each explanatory variable.\n\n### Advantages and Disadvantages of Ordinal logistic regression\n\n#### Advantages\n\n-   It handles ordered outcomes and retains the information of ordered outcome variable\n\n-   It results in fewer parameters compared to multinomial logistic regression\n\n-   It produces interpretable coefficients.\n\n#### Disadvantages\n\n-   It can only be used if it meets the proportional odds assumption\n\n-   Not available in common libraries\n\nLet's explore data to apply ordinal logistic regression analysis.\n\n### Dataset, variables, libraries\n\n**Dataset:** We have a subset of mental health data from NDHS 2022.\n\n**Outcome variable:** `PHQ9_Score` is the outcome variable. We will convert it to a categorical variable named `depression`. The categories of depression are Normal, Mild, Moderate, and Moderately severe to severe. We will convert it to an ordinal variable.\n\n**Independent variables:** In the following example we will take four variables: `Age, Religion, Wealth, and Location.`\n\n**Libraries:** We will use `tidyverse` (for data manipulation), `gsheet` (to import the dataset), `MASS` (to fit the ordinal logistic regression model), and `brant` (to test the proportional odds assumption) packages.\n\n#### Load libraries and import dataset\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# load library\nlibrary(tidyverse) # for data manipulation\nlibrary(gsheet) # to pull data from google sheet\nlibrary(MASS) # to use functions for ordinal regression\nlibrary(brant) # to test proportional odds assumption\n\n# import dataset\ndata<-gsheet::gsheet2tbl('https://docs.google.com/spreadsheets/d/1Sdp2kz0BD5x3nXTk8KlK6LtVy1MWnb_hcWuo67mrWgs')\n\nglimpse(data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> Rows: 12,353\n#> Columns: 25\n#> $ mcaseid              <chr> \"1   1  1\", \"1   8  3\", \"1   8  6\", \"1   8  7\", \"~\n#> $ Cluster              <dbl> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2~\n#> $ Household            <dbl> 1, 8, 8, 8, 11, 11, 14, 14, 33, 39, 45, 7, 7, 9, ~\n#> $ Line_number          <dbl> 1, 3, 6, 7, 3, 6, 1, 3, 1, 5, 1, 1, 3, 1, 1, 3, 1~\n#> $ Sampling_weight      <dbl> 0.871652, 0.871652, 0.871652, 0.871652, 0.871652,~\n#> $ Age                  <dbl> 31, 30, 21, 16, 29, 28, 49, 20, 34, 18, 35, 46, 1~\n#> $ Sex                  <chr> \"Male\", \"Male\", \"Male\", \"Male\", \"Male\", \"Male\", \"~\n#> $ Ethnicity            <chr> \"Janajati\", \"Brahmin_chhetri\", \"Brahmin_chhetri\",~\n#> $ Religion             <chr> \"Hindu\", \"Hindu\", \"Hindu\", \"Hindu\", \"Hindu\", \"Hin~\n#> $ marital_status       <dbl> 2, 2, 1, 1, 2, 2, 2, 1, 2, 1, 2, 2, 1, 2, 2, 1, 1~\n#> $ Education            <dbl> 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 2, 3, 2, 1, 1~\n#> $ occupation           <chr> \"Agriculture\", \"Agriculture\", \"Agriculture\", \"Agr~\n#> $ Location             <dbl> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1~\n#> $ Ecologicalbelt       <chr> \"mountain\", \"mountain\", \"mountain\", \"mountain\", \"~\n#> $ Province             <chr> \"koshi\", \"koshi\", \"koshi\", \"koshi\", \"koshi\", \"kos~\n#> $ District             <chr> \"taplejung\", \"taplejung\", \"taplejung\", \"taplejung~\n#> $ Wealth               <chr> \"poorest\", \"poorest\", \"poorest\", \"poorest\", \"poor~\n#> $ Health_insurance     <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0~\n#> $ current_alcohol      <chr> \"some drink in past month\", \"some drink in past m~\n#> $ current_smoke        <chr> \"Do not smoke\", \"every day\", \"Do not smoke\", \"eve~\n#> $ Self_reported_health <chr> \"moderate\", \"good\", \"good\", \"good\", \"moderate\", \"~\n#> $ disability           <dbl> 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0~\n#> $ Food_insecurity      <chr> \"no\", \"yes\", \"yes\", \"yes\", \"no\", \"no\", \"no\", \"no\"~\n#> $ PHQ9_Score           <dbl> 0, 3, 0, 1, 1, 4, 0, 3, 0, 1, 0, 1, 0, 0, 3, 7, 0~\n#> $ GAD_Score            <dbl> 0, 10, 0, 3, 3, 12, 4, 2, 1, 4, 1, 1, 1, 0, 1, 12~\n```\n\n\n:::\n:::\n\n\n#### Dataset preparation\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Create categorical outcome variable depression\ndata<-data |>\n  mutate(depression=case_when(PHQ9_Score<=4~0,\n                          PHQ9_Score>4 & PHQ9_Score<10~1,\n                        PHQ9_Score>=10 & PHQ9_Score<15~2,\n                        PHQ9_Score>=15 & PHQ9_Score<28~3))\n\n# converting depression variable to ordinal variable\ndata$depression<-factor(data$depression, levels = c(0:3), labels=c(\"Normal\", \"Mild\",\"Moderate\",\"Moderately severe to severe\"), ordered =T)\n```\n:::\n\n\n#### Ordinal logistic regression model\n\nThe proportional odds model (cumulative logit model) is the most widely used ordinal logistic regression model. If the outcome variable M has k categories (M=0, 1, 2, 3, ..., k), there are k-1 ways to dichotomize the outcome variable. The odds of M\\>=k is :\n\n$$ Odds (M \\geq k) = \\frac{P(M \\geq k)}{1-P(M \\geq k)} = \\frac{P(M \\geq k)}{P(M < k)} $$ where k =1, 2, 3,... k-1\n\nUnder the proportional odds assumption, the odds ratio that compares categories \\>=1 to \\<1 is the same as the odds ratio that compares between \\>=2 to \\<2 or \\>=3 to \\<3. This assumption results in only one coefficient for a variable but k-1 intercepts.\n\nThe general regression model for ordinal logistic regression is as follow:\n\n$$ ln(\\frac{P(M \\geq k)} {P(M < k)}) = \\alpha_k + \\beta_1 X_1 +\\beta_2X_2 +\\beta_3X_3 $$ where k =1, 2, 3,... k-1\n\n#### Ordinal logistic regression model preparation\n\nIn a study to determine the association of depression (Normal/ mild/ moderate/ severe) with age (in years), religion (Hindu/ Non-Hindu), wealth quintile (richest/ richer/ middle/ poorer/ poorest), and location (rural/ urban), Lets create a theoretical model\n\n$$ ln(\\frac{P(Depression \\geq k)} {P(Depression < k)}) = \\alpha_k + \\beta_1 Age +\\beta_2Religion +\\beta_3Wealth + \\beta_4Location $$\n\nThe model in R can be created using `polr` function from the `MASS` package as shown below:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Lets fit proportional odds logistic regression model\nmodel1 <- polr(depression ~ Age+Religion+Wealth+Location, data = data, Hess = T)\n\n# See summary of the model\nsummary(model1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> Call:\n#> polr(formula = depression ~ Age + Religion + Wealth + Location, \n#>     data = data, Hess = T)\n#> \n#> Coefficients:\n#>                       Value Std. Error t value\n#> Age                0.007322   0.002354  3.1110\n#> ReligionNon_hindu  0.037160   0.064460  0.5765\n#> Wealthpoorer       0.197368   0.073981  2.6678\n#> Wealthpoorest      0.276796   0.070131  3.9469\n#> Wealthricher      -0.129918   0.078599 -1.6529\n#> Wealthrichest     -0.289871   0.089293 -3.2463\n#> Location           0.075687   0.050717  1.4923\n#> \n#> Intercepts:\n#>                                      Value   Std. Error t value\n#> Normal|Mild                           1.9432  0.1207    16.1061\n#> Mild|Moderate                         3.5078  0.1267    27.6916\n#> Moderate|Moderately severe to severe  4.9024  0.1467    33.4091\n#> \n#> Residual Deviance: 14424.57 \n#> AIC: 14444.57\n```\n\n\n:::\n:::\n\n\n#### Calculate p-value of ordinal logistic regression\n\nIn order to determine p-value for ordinal logistic regression, we can use the following code:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Generate coefficient table\ncoeff_tab<-round(coef(summary(model1)),3)\n# As the p-value is missing, let's calculate the p-value table\np <- pnorm(abs(coeff_tab[, \"t value\"]), lower.tail = F) * 2\n\n# combine tables of coefficient and p-values \ncbind(coeff_tab, \"p value\" = round(p, 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>                                       Value Std. Error t value p value\n#> Age                                   0.007      0.002   3.111   0.002\n#> ReligionNon_hindu                     0.037      0.064   0.576   0.565\n#> Wealthpoorer                          0.197      0.074   2.668   0.008\n#> Wealthpoorest                         0.277      0.070   3.947   0.000\n#> Wealthricher                         -0.130      0.079  -1.653   0.098\n#> Wealthrichest                        -0.290      0.089  -3.246   0.001\n#> Location                              0.076      0.051   1.492   0.136\n#> Normal|Mild                           1.943      0.121  16.106   0.000\n#> Mild|Moderate                         3.508      0.127  27.692   0.000\n#> Moderate|Moderately severe to severe  4.902      0.147  33.409   0.000\n```\n\n\n:::\n:::\n\n\n#### Determine odds ratio and 95%CI\n\nTo calculate the odds ratio and 95% confidence interval around the odds ratio, we can use confint function to generate 95% confidence interval around coefficients. The coefficients can be exponentiated to calculate odds ratio as shown in the code below.\n\n::: callout-tip\nIf the model contains interaction term then you can't directly calculate odds ratio by exponentiation.\n:::\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Calculation of confidence intervals\nconf_int <- round(confint(model1), 2)\n\n# log odds coefficients\nodds_ratio <- round(coef(model1), 2)\n\n# convert coefficients into odds ratio, combine with CIs\ncbind(round(exp(cbind(OR = odds_ratio, conf_int)), 2), \"p-value\"=round(p,3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>                     OR 2.5 % 97.5 % p-value\n#> Age               1.01  1.00   1.01   0.002\n#> ReligionNon_hindu 1.04  0.91   1.17   0.565\n#> Wealthpoorer      1.22  1.05   1.40   0.008\n#> Wealthpoorest     1.32  1.15   1.51   0.000\n#> Wealthricher      0.88  0.76   1.02   0.098\n#> Wealthrichest     0.75  0.63   0.89   0.001\n#> Location          1.08  0.98   1.20   0.136\n```\n\n\n:::\n:::\n\n\n#### Checking proportional odds assumption\n\nThe brant test was defined by Rollin Brant to test the parallel regression assumption. Assessing proportionality in the proportional odds model for ordinal logistic regression.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# testing parallel regression assumption using Brant's test\nbrant(model1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> ---------------------------------------------------- \n#> Test for\t\tX2\tdf\tprobability \n#> ---------------------------------------------------- \n#> Omnibus\t\t\t12.3\t14\t0.58\n#> Age\t\t\t0.84\t2\t0.66\n#> ReligionNon_hindu\t0.22\t2\t0.9\n#> Wealthpoorer\t\t0.9\t2\t0.64\n#> Wealthpoorest\t\t0.62\t2\t0.73\n#> Wealthricher\t\t0.78\t2\t0.68\n#> Wealthrichest\t\t3.29\t2\t0.19\n#> Location\t\t0.36\t2\t0.84\n#> ---------------------------------------------------- \n#> \n#> H0: Parallel Regression Assumption holds\n```\n\n\n:::\n:::\n\n\nAbove is the Brant Test result for this dataset. We conclude that the parallel assumption holds since the probability (p-values) for all variables are greater than alpha=0.05. The output also contains an Omnibus variable, which stands for the whole model, and it is still greater than 0.05. Therefore the proportional odds assumption is not violated and the model is a valid model for this dataset.\n\n#### Checking multi-collinearity\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmodel2<- glm(PHQ9_Score~ Age+Religion+Wealth+Location, data = data, family = gaussian(link=\"identity\"))\n\nperformance::check_collinearity(model2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> # Check for Multicollinearity\n#> \n#> Low Correlation\n#> \n#>      Term  VIF   VIF 95% CI adj. VIF Tolerance Tolerance 95% CI\n#>       Age 1.00 [1.00, 1.91]     1.00      1.00     [0.52, 1.00]\n#>  Religion 1.01 [1.00, 1.17]     1.00      0.99     [0.85, 1.00]\n#>    Wealth 1.16 [1.14, 1.18]     1.08      0.86     [0.85, 0.88]\n#>  Location 1.16 [1.14, 1.18]     1.08      0.86     [0.84, 0.88]\n```\n\n\n:::\n:::\n\n\nMulticollinearity occurs when two or more predictors in the model are correlated and provide redundant information about the response. Multicollinearity was measured by variance inflation factors (VIF) and tolerance. If VIF value exceeding 4.0, or by tol- erance less than 0.2 then there is a problem with multicollinearity (Hair et al., 2010). Here in our model the VIF is lower than 4 so there is no presence of multi-co linearity.\n\n#### Interpretation of odds ratio\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncbind(round(exp(cbind(OR = odds_ratio, conf_int)), 2), \"p-value\"=round(p,3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>                     OR 2.5 % 97.5 % p-value\n#> Age               1.01  1.00   1.01   0.002\n#> ReligionNon_hindu 1.04  0.91   1.17   0.565\n#> Wealthpoorer      1.22  1.05   1.40   0.008\n#> Wealthpoorest     1.32  1.15   1.51   0.000\n#> Wealthricher      0.88  0.76   1.02   0.098\n#> Wealthrichest     0.75  0.63   0.89   0.001\n#> Location          1.08  0.98   1.20   0.136\n```\n\n\n:::\n:::\n\n\nThe odds of having a higher level of depression compared to a lower level is 1.01 (95% CI: 1.00 to 1.01) times higher for each additional year of age, after adjusting for religion, wealth, and place of residence. Compared to the middle wealth quintile, the odds of having a higher level of depression are 25% lower among participants from the richest wealth quintile (OR: 0.75; 95% CI: 0.63 to 0.89) and 32% higher among participants from the poorest wealth quintile (OR: 1.32; 95% CI: 1.15 to 1.51), after adjusting for age, religion, and place of residence.\n\n# Summary\n\nThis chapter covered logistic regression and its major extensions for analyzing categorical outcomes. Standard binary logistic regression (univariate, multivariable, and with interaction terms) is appropriate for a binary outcome with independent observations. When the outcome is binary but the data are sparse or perfectly separated, exact logistic regression or Firth's penalized logistic regression provide more reliable estimates than standard maximum likelihood. When observations are clustered or repeated within subjects, generalized estimating equations (GEE) extend the logistic model to yield valid, population-averaged inference. When the outcome variable has more than two unordered categories, multinomial logistic regression is used, while ordinal logistic regression is preferred when the outcome categories have a natural order, provided the proportional odds assumption holds. Selecting among these methods depends primarily on the structure of the outcome variable (binary, nominal, or ordinal), the independence or clustering of observations, and the sample size and event frequency.\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{},\"value\":[]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}