<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.31">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Measures of Central Tendency – Biostatistics with R</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../Section2/03_measures_of_dispersion.html" rel="next">
<link href="../Section2/01_introduction_descriptive_statistics.html" rel="prev">
<link href="../cover.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-4a990d8dcb58f517c7c86712b8f2ac7c.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark-46f4cc9626f044588a66931b604fc9c8.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-4a990d8dcb58f517c7c86712b8f2ac7c.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-b7a59ac9f7e3a770d9eeb162b88b5d40.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark-f524101b5d1cb1deb615440f12630413.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../site_libs/bootstrap/bootstrap-b7a59ac9f7e3a770d9eeb162b88b5d40.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>
<script src="../site_libs/quarto-diagram/mermaid.min.js"></script>
<script src="../site_libs/quarto-diagram/mermaid-init.js"></script>
<link href="../site_libs/quarto-diagram/mermaid.css" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../Section2/01_introduction_descriptive_statistics.html">Biostatistics</a></li><li class="breadcrumb-item"><a href="../Section2/02_measures_central_tendency.html"><span class="chapter-title">Measures of Central Tendency</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="../index.html" class="sidebar-logo-link">
      <img src="../cover.png" alt="" class="sidebar-logo py-0 d-lg-inline d-none">
      </a>
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Biostatistics with R</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://github.com/Adrisyaone/epidemiologyR.git" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
    <div class="dropdown">
      <a href="" title="Download" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" role="link" aria-label="Download"><i class="bi bi-download"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-0">
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="../Biostatistics-with-R.pdf">
              <i class="bi bi-file-pdf pe-1"></i>
            Download PDF
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="../Biostatistics-with-R.epub">
              <i class="bi bi-journal pe-1"></i>
            Download ePub
            </a>
          </li>
      </ul>
    </div>
    <div class="dropdown">
      <a href="" title="Share" id="quarto-navigation-tool-dropdown-1" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" role="link" aria-label="Share"><i class="bi bi-share"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-1">
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://twitter.com/intent/tweet?url=|url|">
              <i class="bi bi-twitter pe-1"></i>
            Twitter
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://www.linkedin.com/sharing/share-offsite/?url=|url|">
              <i class="bi bi-linkedin pe-1"></i>
            LinkedIn
            </a>
          </li>
      </ul>
    </div>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Introduction to R</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../section1/Chapter1/01_introductions.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Introduction to R</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../section1/Chapter2/02_basics.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Basics in R: Part-1</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../section1/Chapter3/03_basics.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Basics in R: Part-2</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../section1/chapter4/04_data_types.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Data and variables</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../section1/chapter5/04_descriptives.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Descriptive Statistics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../section1/chapter6/04_graphics.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Selection of Graphics for data presentation</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Biostatistics</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Section2/01_introduction_descriptive_statistics.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Introduction to Biostatistics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Section2/02_measures_central_tendency.html" class="sidebar-item-text sidebar-link active"><span class="chapter-title">Measures of Central Tendency</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Section2/03_measures_of_dispersion.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Measures of Dispersion</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Section2/04_probability.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Probability</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Section2/05_discrete_probability_distributions.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Discrete Probability Distributions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Section2/06_continuous_probability_distributions.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Continuous Probability Distributions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Section2/07_intro_hypothesis_testing.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Hypothesis Testing</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Section2/05_bivariate.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Basic statistical tests</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Section2/Numerical data analysis/06_linear_regression.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Linear regression Analysis</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Section2/Categorical data analysis/Categorical_data_analysis2.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Categorical data analysis</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Section2/Count data analysis/Poisson's regression.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Count Data analysis</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Section2/Survival analysis/Survival_analysis.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Survival Analysis</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Section2/Sample size calculation/Sample size calculation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Sample Size estimation</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#the-arithmetic-mean" id="toc-the-arithmetic-mean" class="nav-link" data-scroll-target="#the-arithmetic-mean">The Arithmetic Mean</a>
  <ul class="collapse">
  <li><a href="#definition" id="toc-definition" class="nav-link" data-scroll-target="#definition">Definition</a></li>
  <li><a href="#formula" id="toc-formula" class="nav-link" data-scroll-target="#formula">Formula</a></li>
  <li><a href="#manual-calculation" id="toc-manual-calculation" class="nav-link" data-scroll-target="#manual-calculation">Manual Calculation</a></li>
  <li><a href="#c.-grouped-frequency-distribution" id="toc-c.-grouped-frequency-distribution" class="nav-link" data-scroll-target="#c.-grouped-frequency-distribution">C. Grouped Frequency Distribution</a></li>
  <li><a href="#interpretation" id="toc-interpretation" class="nav-link" data-scroll-target="#interpretation">Interpretation</a></li>
  <li><a href="#advantages" id="toc-advantages" class="nav-link" data-scroll-target="#advantages">Advantages</a></li>
  <li><a href="#disadvantages" id="toc-disadvantages" class="nav-link" data-scroll-target="#disadvantages">Disadvantages</a></li>
  <li><a href="#appropriate-use" id="toc-appropriate-use" class="nav-link" data-scroll-target="#appropriate-use">Appropriate Use</a></li>
  <li><a href="#public-health-example" id="toc-public-health-example" class="nav-link" data-scroll-target="#public-health-example">Public Health Example</a></li>
  </ul></li>
  <li><a href="#weighted-mean" id="toc-weighted-mean" class="nav-link" data-scroll-target="#weighted-mean">Weighted Mean</a>
  <ul class="collapse">
  <li><a href="#definition-1" id="toc-definition-1" class="nav-link" data-scroll-target="#definition-1">Definition</a></li>
  <li><a href="#formula-1" id="toc-formula-1" class="nav-link" data-scroll-target="#formula-1">Formula</a></li>
  <li><a href="#worked-example-public-health" id="toc-worked-example-public-health" class="nav-link" data-scroll-target="#worked-example-public-health">Worked Example (Public Health)</a></li>
  <li><a href="#interpretation-1" id="toc-interpretation-1" class="nav-link" data-scroll-target="#interpretation-1">Interpretation</a></li>
  <li><a href="#advantages-1" id="toc-advantages-1" class="nav-link" data-scroll-target="#advantages-1">Advantages</a></li>
  <li><a href="#disadvantages-1" id="toc-disadvantages-1" class="nav-link" data-scroll-target="#disadvantages-1">Disadvantages</a></li>
  <li><a href="#appropriate-use-1" id="toc-appropriate-use-1" class="nav-link" data-scroll-target="#appropriate-use-1">Appropriate Use</a></li>
  <li><a href="#public-health-example-1" id="toc-public-health-example-1" class="nav-link" data-scroll-target="#public-health-example-1">Public Health Example</a></li>
  </ul></li>
  <li><a href="#geometric-mean" id="toc-geometric-mean" class="nav-link" data-scroll-target="#geometric-mean">Geometric Mean</a>
  <ul class="collapse">
  <li><a href="#definition-2" id="toc-definition-2" class="nav-link" data-scroll-target="#definition-2">Definition</a></li>
  <li><a href="#formula-2" id="toc-formula-2" class="nav-link" data-scroll-target="#formula-2">Formula</a></li>
  <li><a href="#manual-calculation-1" id="toc-manual-calculation-1" class="nav-link" data-scroll-target="#manual-calculation-1">Manual Calculation</a></li>
  <li><a href="#interpretation-2" id="toc-interpretation-2" class="nav-link" data-scroll-target="#interpretation-2">Interpretation</a></li>
  <li><a href="#advantages-2" id="toc-advantages-2" class="nav-link" data-scroll-target="#advantages-2">Advantages</a></li>
  <li><a href="#disadvantages-2" id="toc-disadvantages-2" class="nav-link" data-scroll-target="#disadvantages-2">Disadvantages</a></li>
  <li><a href="#appropriate-use-2" id="toc-appropriate-use-2" class="nav-link" data-scroll-target="#appropriate-use-2">Appropriate Use</a></li>
  <li><a href="#public-health-example-2" id="toc-public-health-example-2" class="nav-link" data-scroll-target="#public-health-example-2">Public Health Example</a></li>
  </ul></li>
  <li><a href="#harmonic-mean" id="toc-harmonic-mean" class="nav-link" data-scroll-target="#harmonic-mean">Harmonic Mean</a>
  <ul class="collapse">
  <li><a href="#definition-3" id="toc-definition-3" class="nav-link" data-scroll-target="#definition-3">Definition</a></li>
  <li><a href="#formula-3" id="toc-formula-3" class="nav-link" data-scroll-target="#formula-3">Formula</a></li>
  <li><a href="#manual-calculation-2" id="toc-manual-calculation-2" class="nav-link" data-scroll-target="#manual-calculation-2">Manual Calculation</a></li>
  <li><a href="#interpretation-3" id="toc-interpretation-3" class="nav-link" data-scroll-target="#interpretation-3">Interpretation</a></li>
  <li><a href="#advantages-3" id="toc-advantages-3" class="nav-link" data-scroll-target="#advantages-3">Advantages</a></li>
  <li><a href="#disadvantages-3" id="toc-disadvantages-3" class="nav-link" data-scroll-target="#disadvantages-3">Disadvantages</a></li>
  <li><a href="#appropriate-use-3" id="toc-appropriate-use-3" class="nav-link" data-scroll-target="#appropriate-use-3">Appropriate Use</a></li>
  <li><a href="#public-health-example-3" id="toc-public-health-example-3" class="nav-link" data-scroll-target="#public-health-example-3">Public Health Example</a></li>
  </ul></li>
  <li><a href="#relationship-among-the-three-means" id="toc-relationship-among-the-three-means" class="nav-link" data-scroll-target="#relationship-among-the-three-means">Relationship Among the Three Means</a></li>
  <li><a href="#the-median" id="toc-the-median" class="nav-link" data-scroll-target="#the-median">The Median</a>
  <ul class="collapse">
  <li><a href="#definition-4" id="toc-definition-4" class="nav-link" data-scroll-target="#definition-4">Definition</a></li>
  <li><a href="#formula-4" id="toc-formula-4" class="nav-link" data-scroll-target="#formula-4">Formula</a></li>
  <li><a href="#manual-calculation-3" id="toc-manual-calculation-3" class="nav-link" data-scroll-target="#manual-calculation-3">Manual Calculation</a></li>
  <li><a href="#a.-raw-data" id="toc-a.-raw-data" class="nav-link" data-scroll-target="#a.-raw-data">A. Raw Data</a></li>
  <li><a href="#b.-frequency-table" id="toc-b.-frequency-table" class="nav-link" data-scroll-target="#b.-frequency-table">B. Frequency Table</a></li>
  <li><a href="#c.-grouped-frequency-distribution-1" id="toc-c.-grouped-frequency-distribution-1" class="nav-link" data-scroll-target="#c.-grouped-frequency-distribution-1">C. Grouped Frequency Distribution</a></li>
  <li><a href="#interpretation-4" id="toc-interpretation-4" class="nav-link" data-scroll-target="#interpretation-4">Interpretation</a></li>
  <li><a href="#advantages-4" id="toc-advantages-4" class="nav-link" data-scroll-target="#advantages-4">Advantages</a></li>
  <li><a href="#disadvantages-4" id="toc-disadvantages-4" class="nav-link" data-scroll-target="#disadvantages-4">Disadvantages</a></li>
  <li><a href="#appropriate-use-4" id="toc-appropriate-use-4" class="nav-link" data-scroll-target="#appropriate-use-4">Appropriate Use</a></li>
  <li><a href="#public-health-example-4" id="toc-public-health-example-4" class="nav-link" data-scroll-target="#public-health-example-4">Public Health Example</a></li>
  </ul></li>
  <li><a href="#the-mode" id="toc-the-mode" class="nav-link" data-scroll-target="#the-mode">The Mode</a>
  <ul class="collapse">
  <li><a href="#definition-5" id="toc-definition-5" class="nav-link" data-scroll-target="#definition-5">Definition</a></li>
  <li><a href="#formula-grouped-data" id="toc-formula-grouped-data" class="nav-link" data-scroll-target="#formula-grouped-data">Formula (Grouped Data)</a></li>
  <li><a href="#manual-calculation-4" id="toc-manual-calculation-4" class="nav-link" data-scroll-target="#manual-calculation-4">Manual Calculation</a></li>
  <li><a href="#a.-raw-data-1" id="toc-a.-raw-data-1" class="nav-link" data-scroll-target="#a.-raw-data-1">A. Raw Data</a></li>
  <li><a href="#b.-frequency-table-1" id="toc-b.-frequency-table-1" class="nav-link" data-scroll-target="#b.-frequency-table-1">B. Frequency Table</a></li>
  <li><a href="#c.-grouped-frequency-distribution-2" id="toc-c.-grouped-frequency-distribution-2" class="nav-link" data-scroll-target="#c.-grouped-frequency-distribution-2">C. Grouped Frequency Distribution</a></li>
  <li><a href="#interpretation-5" id="toc-interpretation-5" class="nav-link" data-scroll-target="#interpretation-5">Interpretation</a></li>
  <li><a href="#advantages-5" id="toc-advantages-5" class="nav-link" data-scroll-target="#advantages-5">Advantages</a></li>
  <li><a href="#disadvantages-5" id="toc-disadvantages-5" class="nav-link" data-scroll-target="#disadvantages-5">Disadvantages</a></li>
  <li><a href="#appropriate-use-5" id="toc-appropriate-use-5" class="nav-link" data-scroll-target="#appropriate-use-5">Appropriate Use</a></li>
  <li><a href="#public-health-example-5" id="toc-public-health-example-5" class="nav-link" data-scroll-target="#public-health-example-5">Public Health Example</a></li>
  </ul></li>
  <li><a href="#quartiles-percentiles-and-deciles" id="toc-quartiles-percentiles-and-deciles" class="nav-link" data-scroll-target="#quartiles-percentiles-and-deciles">Quartiles, Percentiles, and Deciles</a>
  <ul class="collapse">
  <li><a href="#definitions" id="toc-definitions" class="nav-link" data-scroll-target="#definitions">Definitions</a></li>
  <li><a href="#formula-grouped-data-1" id="toc-formula-grouped-data-1" class="nav-link" data-scroll-target="#formula-grouped-data-1">Formula (Grouped Data)</a></li>
  <li><a href="#manual-calculation-a.-raw-data" id="toc-manual-calculation-a.-raw-data" class="nav-link" data-scroll-target="#manual-calculation-a.-raw-data">Manual Calculation — A. Raw Data</a></li>
  <li><a href="#manual-calculation-c.-grouped-frequency-distribution" id="toc-manual-calculation-c.-grouped-frequency-distribution" class="nav-link" data-scroll-target="#manual-calculation-c.-grouped-frequency-distribution">Manual Calculation — C. Grouped Frequency Distribution</a></li>
  <li><a href="#interpretation-6" id="toc-interpretation-6" class="nav-link" data-scroll-target="#interpretation-6">Interpretation</a></li>
  <li><a href="#advantages-6" id="toc-advantages-6" class="nav-link" data-scroll-target="#advantages-6">Advantages</a></li>
  <li><a href="#disadvantages-6" id="toc-disadvantages-6" class="nav-link" data-scroll-target="#disadvantages-6">Disadvantages</a></li>
  <li><a href="#appropriate-use-6" id="toc-appropriate-use-6" class="nav-link" data-scroll-target="#appropriate-use-6">Appropriate Use</a></li>
  <li><a href="#public-health-example-6" id="toc-public-health-example-6" class="nav-link" data-scroll-target="#public-health-example-6">Public Health Example</a></li>
  </ul></li>
  <li><a href="#comparing-all-measures-of-central-tendency" id="toc-comparing-all-measures-of-central-tendency" class="nav-link" data-scroll-target="#comparing-all-measures-of-central-tendency">Comparing All Measures of Central Tendency</a>
  <ul class="collapse">
  <li><a href="#choosing-the-right-measure-effect-of-skewness" id="toc-choosing-the-right-measure-effect-of-skewness" class="nav-link" data-scroll-target="#choosing-the-right-measure-effect-of-skewness">Choosing the Right Measure — Effect of Skewness</a></li>
  </ul></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary">Summary</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/Adrisyaone/epidemiologyR.git/edit/main/Section2/02_measures_central_tendency.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/Adrisyaone/epidemiologyR.git/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../Section2/01_introduction_descriptive_statistics.html">Biostatistics</a></li><li class="breadcrumb-item"><a href="../Section2/02_measures_central_tendency.html"><span class="chapter-title">Measures of Central Tendency</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-title">Measures of Central Tendency</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>A <strong>measure of central tendency</strong> is a single value that attempts to describe a data set by identifying the “center” or “typical” value of the distribution. The three classical measures are the <strong>mean</strong>, <strong>median</strong>, and <strong>mode</strong>; we also cover <strong>quartiles</strong>, <strong>percentiles</strong>, and <strong>deciles</strong>, which are measures of <em>position</em> closely related to the median.</p>
<p>Throughout this section we will use three running data sets so every formula can be demonstrated with a full, step-by-step manual calculation:</p>
<ul>
<li><p><strong>Dataset A (raw/ungrouped data):</strong> Fasting blood glucose (mg/dL) of 11 patients attending a diabetes clinic:</p>
<p><code>88, 92, 95, 98, 101, 104, 108, 112, 118, 125, 250</code></p></li>
<li><p><strong>Dataset B (frequency table / discrete data):</strong> Number of children in 40 households in a village survey.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Number of children (<span class="math inline">\(x\)</span>)</th>
<th>Frequency (<span class="math inline">\(f\)</span>)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0</td>
<td>6</td>
</tr>
<tr class="even">
<td>1</td>
<td>10</td>
</tr>
<tr class="odd">
<td>2</td>
<td>14</td>
</tr>
<tr class="even">
<td>3</td>
<td>7</td>
</tr>
<tr class="odd">
<td>4</td>
<td>3</td>
</tr>
<tr class="even">
<td><strong>Total</strong></td>
<td>40</td>
</tr>
</tbody>
</table></li>
<li><p><strong>Data Set C (grouped frequency distribution):</strong> Age (in years) of 50 patients admitted with hypertension, grouped into class intervals.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Class interval</th>
<th>Frequency (<span class="math inline">\(f\)</span>)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>30–39</td>
<td>4</td>
</tr>
<tr class="even">
<td>40–49</td>
<td>9</td>
</tr>
<tr class="odd">
<td>50–59</td>
<td>15</td>
</tr>
<tr class="even">
<td>60–69</td>
<td>13</td>
</tr>
<tr class="odd">
<td>70–79</td>
<td>7</td>
</tr>
<tr class="even">
<td>80–89</td>
<td>2</td>
</tr>
<tr class="odd">
<td><strong>Total</strong></td>
<td>50</td>
</tr>
</tbody>
</table></li>
</ul>
</section>
<section id="the-arithmetic-mean" class="level2">
<h2 class="anchored" data-anchor-id="the-arithmetic-mean">The Arithmetic Mean</h2>
<section id="definition" class="level3">
<h3 class="anchored" data-anchor-id="definition">Definition</h3>
<p>The <strong>arithmetic mean</strong> (commonly just called “the mean” or “average”) is the sum of all observations divided by the number of observations.</p>
</section>
<section id="formula" class="level3">
<h3 class="anchored" data-anchor-id="formula">Formula</h3>
<p>For a population of size <span class="math inline">\(N\)</span>: <span class="math display">\[\mu = \frac{\sum_{i=1}^{N} X_i}{N}\]</span></p>
<p>For a sample of size <span class="math inline">\(n\)</span>: <span class="math display">\[\bar{x} = \frac{\sum_{i=1}^{n} x_i}{n}\]</span></p>
</section>
<section id="manual-calculation" class="level3">
<h3 class="anchored" data-anchor-id="manual-calculation">Manual Calculation</h3>
<section id="a.-raw-ungrouped-data" class="level4">
<h4 class="anchored" data-anchor-id="a.-raw-ungrouped-data">A. Raw (Ungrouped) Data</h4>
<p>Using Data Set A (fasting glucose, mg/dL): 88, 92, 95, 98, 101, 104, 108, 112, 118, 125, 250 (<span class="math inline">\(n = 11\)</span>)</p>
<p><strong>Step 1.</strong> Sum all observations: <span class="math display">\[\sum x_i = 88+92+95+98+101+104+108+112+118+125+250 = 1291\]</span></p>
<p><strong>Step 2.</strong> Divide by <span class="math inline">\(n\)</span>: <span class="math display">\[\bar{x} = \frac{1291}{11} = 117.4 \text{ mg/dL}\]</span></p>
<p>Notice that the single extreme value (250 mg/dL, representing an undiagnosed diabetic outlier) pulls the mean upward — this illustrates the mean’s <strong>sensitivity to outliers</strong>, discussed further below.</p>
</section>
<section id="b.-frequency-table-ungrouped-discrete-data" class="level4">
<h4 class="anchored" data-anchor-id="b.-frequency-table-ungrouped-discrete-data">B. Frequency Table (Ungrouped, Discrete Data)</h4>
<p>Data Set B — number of children (<span class="math inline">\(x\)</span>) per household, surveyed in 40 households:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Number of children (<span class="math inline">\(x\)</span>)</th>
<th>Frequency (<span class="math inline">\(f\)</span>)</th>
<th><span class="math inline">\(f \times x\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0</td>
<td>6</td>
<td>0</td>
</tr>
<tr class="even">
<td>1</td>
<td>10</td>
<td>10</td>
</tr>
<tr class="odd">
<td>2</td>
<td>14</td>
<td>28</td>
</tr>
<tr class="even">
<td>3</td>
<td>7</td>
<td>21</td>
</tr>
<tr class="odd">
<td>4</td>
<td>3</td>
<td>12</td>
</tr>
<tr class="even">
<td><strong>Total</strong></td>
<td><span class="math inline">\(n = \sum f = 40\)</span></td>
<td><span class="math inline">\(\sum fx = 71\)</span></td>
</tr>
</tbody>
</table>
<p><strong>Formula:</strong> <span class="math inline">\(\bar{x} = \dfrac{\sum f_i x_i}{\sum f_i}\)</span></p>
<p><strong>Step 1.</strong> Compute <span class="math inline">\(f \times x\)</span> for each row (shown above).</p>
<p><strong>Step 2.</strong> Sum the <span class="math inline">\(fx\)</span> column: <span class="math inline">\(\sum fx = 0+10+28+21+12 = 71\)</span>.</p>
<p><strong>Step 3.</strong> Sum the frequency column: <span class="math inline">\(\sum f = 6+10+14+7+3 = 40\)</span>.</p>
<p><strong>Step 4.</strong> Divide: <span class="math display">\[\bar{x} = \frac{71}{40} = 1.775 \approx 1.8 \text{ children per household}\]</span></p>
</section>
</section>
<section id="c.-grouped-frequency-distribution" class="level3">
<h3 class="anchored" data-anchor-id="c.-grouped-frequency-distribution">C. Grouped Frequency Distribution</h3>
<p>Data Set C is a age (in years) of 50 hypertension patients:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 23%">
<col style="width: 23%">
<col style="width: 24%">
<col style="width: 28%">
</colgroup>
<thead>
<tr class="header">
<th>Class interval</th>
<th>Midpoint (<span class="math inline">\(m\)</span>)</th>
<th>Frequency (<span class="math inline">\(f\)</span>)</th>
<th><span class="math inline">\(f \times m\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>30–39</td>
<td>34.5</td>
<td>4</td>
<td>138.0</td>
</tr>
<tr class="even">
<td>40–49</td>
<td>44.5</td>
<td>9</td>
<td>400.5</td>
</tr>
<tr class="odd">
<td>50–59</td>
<td>54.5</td>
<td>15</td>
<td>817.5</td>
</tr>
<tr class="even">
<td>60–69</td>
<td>64.5</td>
<td>13</td>
<td>838.5</td>
</tr>
<tr class="odd">
<td>70–79</td>
<td>74.5</td>
<td>7</td>
<td>521.5</td>
</tr>
<tr class="even">
<td>80–89</td>
<td>84.5</td>
<td>2</td>
<td>169.0</td>
</tr>
<tr class="odd">
<td><strong>Total</strong></td>
<td>-</td>
<td><span class="math inline">\(n = 50\)</span></td>
<td><span class="math inline">\(\sum fm = 2885.0\)</span></td>
</tr>
</tbody>
</table>
<p><strong>Formula:</strong> <span class="math inline">\(\bar{x} = \dfrac{\sum f_i m_i}{\sum f_i}\)</span>, where <span class="math inline">\(m_i\)</span> is the midpoint of each class.</p>
<p><strong>Step 1.</strong> Find the midpoint of each class: <span class="math inline">\(m = \dfrac{\text{lower limit} + \text{upper limit}}{2}\)</span>. For 30–39: <span class="math inline">\(m = (30+39)/2 = 34.5\)</span> (using continuous class boundaries 29.5–39.5 is also acceptable and gives the same midpoint here). <strong>Step 2.</strong> Multiply each midpoint by its frequency (<span class="math inline">\(f \times m\)</span>), shown above. <strong>Step 3.</strong> Sum the <span class="math inline">\(fm\)</span> column: <span class="math inline">\(2885.0\)</span>. <strong>Step 4.</strong> Divide by total frequency: <span class="math display">\[\bar{x} = \frac{2885.0}{50} = 57.7 \text{ years}\]</span></p>
<div class="callout callout-style-simple callout-important">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>The grouped mean is an <strong>approximation</strong> because individual raw values inside each class are unknown; we assume every observation in a class is located at the midpoint. This assumption introduces a small amount of <strong>grouping error</strong>.</p>
</div>
</div>
</div>
</section>
<section id="interpretation" class="level3">
<h3 class="anchored" data-anchor-id="interpretation">Interpretation</h3>
<p>The arithmetic mean represents the “balance point” of the data. If the data were weights on a see-saw, the mean is where it would balance.</p>
</section>
<section id="advantages" class="level3">
<h3 class="anchored" data-anchor-id="advantages">Advantages</h3>
<ul>
<li>Uses every observation in the data set.</li>
<li>Algebraically tractable (has well-defined mathematical properties, e.g., <span class="math inline">\(\sum (x_i - \bar{x}) = 0\)</span>), making it the basis for further statistics (variance, regression, etc.).</li>
<li>Familiar and easy to interpret.</li>
<li>Stable from sample to sample (least sampling variability among the three central tendency measures, under normality).</li>
</ul>
</section>
<section id="disadvantages" class="level3">
<h3 class="anchored" data-anchor-id="disadvantages">Disadvantages</h3>
<ul>
<li>Highly sensitive to <strong>outliers and skewed data</strong> (as shown above, one value of 250 pulled the mean far above where most data points lie).</li>
<li>Cannot be computed for open-ended class intervals or for nominal/ordinal data.</li>
<li>Can produce a value that does not correspond to any actual observation (e.g., “1.8 children”), which may seem unnatural.</li>
</ul>
</section>
<section id="appropriate-use" class="level3">
<h3 class="anchored" data-anchor-id="appropriate-use">Appropriate Use</h3>
<p>The mean is most appropriate when data are <strong>symmetric (approximately normally distributed)</strong> and free of major outliers, and when the variable is measured on an <strong>interval or ratio scale</strong>.</p>
</section>
<section id="public-health-example" class="level3">
<h3 class="anchored" data-anchor-id="public-health-example">Public Health Example</h3>
<p>The mean is used to report the <strong>average birth weight</strong> of newborns in a hospital, the <strong>mean systolic blood pressure</strong> in a screened population, or the <strong>mean length of hospital stay</strong> for a given diagnosis.</p>
</section>
</section>
<section id="weighted-mean" class="level2">
<h2 class="anchored" data-anchor-id="weighted-mean">Weighted Mean</h2>
<section id="definition-1" class="level3">
<h3 class="anchored" data-anchor-id="definition-1">Definition</h3>
<p>The <strong>weighted mean</strong> is a generalization of the arithmetic mean in which each observation is multiplied by a weight reflecting its relative importance, rather than being treated equally.</p>
</section>
<section id="formula-1" class="level3">
<h3 class="anchored" data-anchor-id="formula-1">Formula</h3>
<p><span class="math display">\[\bar{x}_w = \frac{\sum_{i=1}^{k} w_i x_i}{\sum_{i=1}^{k} w_i}\]</span></p>
<p>where <span class="math inline">\(w_i\)</span> is the weight assigned to value <span class="math inline">\(x_i\)</span>.</p>
</section>
<section id="worked-example-public-health" class="level3">
<h3 class="anchored" data-anchor-id="worked-example-public-health">Worked Example (Public Health)</h3>
<p>A district’s overall infant mortality rate (IMR) is calculated by combining IMRs from three sub-districts, weighted by the number of live births in each (not by simply averaging the three rates):</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Sub-district</th>
<th>IMR per 1000 live births (<span class="math inline">\(x\)</span>)</th>
<th>Live births (weight <span class="math inline">\(w\)</span>)</th>
<th><span class="math inline">\(w \times x\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>A</td>
<td>25</td>
<td>2000</td>
<td>50,000</td>
</tr>
<tr class="even">
<td>B</td>
<td>40</td>
<td>500</td>
<td>20,000</td>
</tr>
<tr class="odd">
<td>C</td>
<td>18</td>
<td>3500</td>
<td>63,000</td>
</tr>
<tr class="even">
<td><strong>Total</strong></td>
<td></td>
<td><span class="math inline">\(\sum w = 6000\)</span></td>
<td><span class="math inline">\(\sum wx = 133{,}000\)</span></td>
</tr>
</tbody>
</table>
<p><strong>Step 1.</strong> Multiply each rate by its weight (live births): shown above. <strong>Step 2.</strong> Sum the weighted values: <span class="math inline">\(133{,}000\)</span>. <strong>Step 3.</strong> Sum the weights: <span class="math inline">\(6000\)</span>. <strong>Step 4.</strong> Divide: <span class="math display">\[\bar{x}_w = \frac{133{,}000}{6000} = 22.17 \text{ per } 1000 \text{ live births}\]</span></p>
<p>Notice that the naive (unweighted) average of 25, 40, and 18 would be <span class="math inline">\(27.7\)</span> — quite different, and misleading, because it ignores that sub-district B has far fewer births and should count less toward the district total.</p>
</section>
<section id="interpretation-1" class="level3">
<h3 class="anchored" data-anchor-id="interpretation-1">Interpretation</h3>
<p>The weighted mean reflects the true overall rate/value when subgroups contribute unequally to the total.</p>
</section>
<section id="advantages-1" class="level3">
<h3 class="anchored" data-anchor-id="advantages-1">Advantages</h3>
<ul>
<li>Accounts for differing sample sizes or importance across subgroups.</li>
<li>Prevents small subgroups from distorting the overall estimate.</li>
</ul>
</section>
<section id="disadvantages-1" class="level3">
<h3 class="anchored" data-anchor-id="disadvantages-1">Disadvantages</h3>
<ul>
<li>Requires accurate and appropriate weights; incorrect weights produce a misleading result.</li>
<li>More complex to compute and explain than the simple mean.</li>
</ul>
</section>
<section id="appropriate-use-1" class="level3">
<h3 class="anchored" data-anchor-id="appropriate-use-1">Appropriate Use</h3>
<p>Used whenever combining rates or averages from groups of unequal size. Standardized mortality/morbidity rates, meta-analysis of study results (weighted by sample size or inverse variance), grade point averages (weighted by credit hours).</p>
</section>
<section id="public-health-example-1" class="level3">
<h3 class="anchored" data-anchor-id="public-health-example-1">Public Health Example</h3>
<p><strong>Age-standardized mortality rates</strong>, which combine age-specific death rates using a standard population’s age distribution as weights, so that mortality rates can be fairly compared across populations with different age structures.</p>
</section>
</section>
<section id="geometric-mean" class="level2">
<h2 class="anchored" data-anchor-id="geometric-mean">Geometric Mean</h2>
<section id="definition-2" class="level3">
<h3 class="anchored" data-anchor-id="definition-2">Definition</h3>
<p>The <strong>geometric mean (GM)</strong> is the <span class="math inline">\(n\)</span>-th root of the product of <span class="math inline">\(n\)</span> observations. It is used for data that grow <strong>multiplicatively</strong> (e.g., rates of change, ratios, or log-normally distributed data such as antibody titers).</p>
</section>
<section id="formula-2" class="level3">
<h3 class="anchored" data-anchor-id="formula-2">Formula</h3>
<p><span class="math display">\[GM = \sqrt[n]{x_1 \times x_2 \times \cdots \times x_n} = \left( \prod_{i=1}^n x_i \right)^{1/n}\]</span></p>
<p>Equivalently, using logarithms (easier for manual calculation with many observations): <span class="math display">\[GM = \exp\left( \frac{\sum_{i=1}^{n} \ln(x_i)}{n} \right)\]</span></p>
</section>
<section id="manual-calculation-1" class="level3">
<h3 class="anchored" data-anchor-id="manual-calculation-1">Manual Calculation</h3>
<p>Suppose antibody titers (reciprocal dilution) from 4 patients after vaccination are: 8, 16, 32, 128.</p>
<p><strong>Step 1.</strong> Multiply all values: <span class="math inline">\(8 \times 16 \times 32 \times 128 = 524{,}288\)</span>. <strong>Step 2.</strong> Take the <span class="math inline">\(n\)</span>-th root (<span class="math inline">\(n = 4\)</span>): <span class="math display">\[GM = \sqrt[4]{524{,}288} = 26.9\]</span></p>
<p><strong>Verification using logarithms:</strong> <span class="math inline">\(\ln 8 = 2.079\)</span>, <span class="math inline">\(\ln 16 = 2.773\)</span>, <span class="math inline">\(\ln 32 = 3.466\)</span>, <span class="math inline">\(\ln 128 = 4.852\)</span>. Sum <span class="math inline">\(= 13.17\)</span>. Mean of logs <span class="math inline">\(= 13.17/4 = 3.29\)</span>. <span class="math inline">\(GM = e^{3.29} = 26.9\)</span> ✓.</p>
<p>Compare this to the arithmetic mean of the same data: <span class="math inline">\(\bar{x} = (8+16+32+128)/4 = 46\)</span>. The geometric mean (26.9) is always <span class="math inline">\(\le\)</span> the arithmetic mean (46) for positive data, and is much less influenced by the largest value (128).</p>
</section>
<section id="interpretation-2" class="level3">
<h3 class="anchored" data-anchor-id="interpretation-2">Interpretation</h3>
<p>The geometric mean represents the central tendency of <strong>multiplicative or exponential</strong> processes; it is the appropriate “average” when data are ratios, growth rates, or span several orders of magnitude.</p>
</section>
<section id="advantages-2" class="level3">
<h3 class="anchored" data-anchor-id="advantages-2">Advantages</h3>
<ul>
<li>Less affected by extreme high values than the arithmetic mean (dampens the effect of outliers because it operates on a log scale).</li>
<li>Appropriate for <strong>log-normally distributed</strong> data (very common in laboratory/biological measurements such as titers, viral loads, and PCR cycle thresholds).</li>
<li>Useful for averaging ratios, rates of growth, or index numbers.</li>
</ul>
</section>
<section id="disadvantages-2" class="level3">
<h3 class="anchored" data-anchor-id="disadvantages-2">Disadvantages</h3>
<ul>
<li>Undefined if any observation is zero or negative.</li>
<li>More difficult to compute manually and less intuitive to interpret than the arithmetic mean.</li>
<li>Not appropriate for additive data.</li>
</ul>
</section>
<section id="appropriate-use-2" class="level3">
<h3 class="anchored" data-anchor-id="appropriate-use-2">Appropriate Use</h3>
<p>Used for <strong>serial dilution titers</strong>, <strong>viral load and antibody data</strong>, growth rates of populations or bacterial cultures, and any positively skewed, log-normal biological data.</p>
</section>
<section id="public-health-example-2" class="level3">
<h3 class="anchored" data-anchor-id="public-health-example-2">Public Health Example</h3>
<p>Reporting the <strong>geometric mean antibody titer</strong> post-vaccination in a clinical trial, or the <strong>geometric mean viral load</strong> in an HIV cohort, standard practice in immunology and virology because titers are log-normally distributed.</p>
</section>
</section>
<section id="harmonic-mean" class="level2">
<h2 class="anchored" data-anchor-id="harmonic-mean">Harmonic Mean</h2>
<section id="definition-3" class="level3">
<h3 class="anchored" data-anchor-id="definition-3">Definition</h3>
<p>The <strong>harmonic mean (HM)</strong> is the reciprocal of the arithmetic mean of the reciprocals of the observations. It is most appropriate for averaging <strong>rates</strong> (e.g., speeds, rates per unit time) when the numerator is fixed.</p>
</section>
<section id="formula-3" class="level3">
<h3 class="anchored" data-anchor-id="formula-3">Formula</h3>
<p><span class="math display">\[HM = \frac{n}{\sum_{i=1}^{n} \frac{1}{x_i}}\]</span></p>
</section>
<section id="manual-calculation-2" class="level3">
<h3 class="anchored" data-anchor-id="manual-calculation-2">Manual Calculation</h3>
<p>Suppose three health workers screen patients at rates of 20, 30, and 60 patients per hour, and each worked for the <strong>same total number of patients screened</strong> (not the same amount of time). Find the average screening rate.</p>
<p><strong>Step 1.</strong> Take the reciprocal of each rate: <span class="math inline">\(1/20 = 0.0500\)</span>, <span class="math inline">\(1/30 = 0.0333\)</span>, <span class="math inline">\(1/60 = 0.0167\)</span>.</p>
<p><strong>Step 2.</strong> Sum the reciprocals: <span class="math inline">\(0.0500+0.0333+0.0167 = 0.1000\)</span>.</p>
<p><strong>Step 3.</strong> Divide <span class="math inline">\(n\)</span> by this sum: <span class="math display">\[HM = \frac{3}{0.1000} = 30 \text{ patients/hour}\]</span></p>
<p>Note that the arithmetic mean of the same three rates would be <span class="math inline">\((20+30+60)/3 = 36.7\)</span>, which would <strong>overstate</strong> the true average rate when the underlying quantity (patients screened) is fixed, not the time.</p>
</section>
<section id="interpretation-3" class="level3">
<h3 class="anchored" data-anchor-id="interpretation-3">Interpretation</h3>
<p>The harmonic mean gives the correct “average rate” when combining rates that share a common numerator (e.g., a fixed distance, fixed number of patients, or fixed dose).</p>
</section>
<section id="advantages-3" class="level3">
<h3 class="anchored" data-anchor-id="advantages-3">Advantages</h3>
<ul>
<li>Correct choice for averaging rates and ratios where the denominator varies.</li>
<li>Strongly dampens the influence of large values — most conservative of the three Pythagorean means (<span class="math inline">\(HM \le GM \le AM\)</span>).</li>
</ul>
</section>
<section id="disadvantages-3" class="level3">
<h3 class="anchored" data-anchor-id="disadvantages-3">Disadvantages</h3>
<ul>
<li>Undefined if any value is zero.</li>
<li>Rarely used and often misunderstood; easy to apply incorrectly.</li>
<li>Heavily influenced by small values.</li>
</ul>
</section>
<section id="appropriate-use-3" class="level3">
<h3 class="anchored" data-anchor-id="appropriate-use-3">Appropriate Use</h3>
<p>Used when averaging <strong>rates</strong> such as speed, dose per kilogram, or performance rates, particularly when the events being counted (not the time) are held constant.</p>
</section>
<section id="public-health-example-3" class="level3">
<h3 class="anchored" data-anchor-id="public-health-example-3">Public Health Example</h3>
<p>Calculating the average <strong>turnaround time rate</strong> for laboratory tests processed at different rates by different technicians, or combining rates in <strong>person-time incidence</strong> calculations.</p>
</section>
</section>
<section id="relationship-among-the-three-means" class="level2">
<h2 class="anchored" data-anchor-id="relationship-among-the-three-means">Relationship Among the Three Means</h2>
<p>For any set of positive numbers that are not all identical: <span class="math display">\[HM \le GM \le AM\]</span></p>
<p>The three means are equal only when all observations are identical.</p>
</section>
<section id="the-median" class="level2">
<h2 class="anchored" data-anchor-id="the-median">The Median</h2>
<section id="definition-4" class="level3">
<h3 class="anchored" data-anchor-id="definition-4">Definition</h3>
<p>The <strong>median</strong> is the middle value of a data set when the observations are arranged in ascending (or descending) order. It divides the data into two equal halves: 50% of observations lie at or below the median, and 50% lie at or above it.</p>
</section>
<section id="formula-4" class="level3">
<h3 class="anchored" data-anchor-id="formula-4">Formula</h3>
<p>For raw/ungrouped data with <span class="math inline">\(n\)</span> observations sorted in order:</p>
<ul>
<li>If <span class="math inline">\(n\)</span> is <strong>odd</strong>: Median <span class="math inline">\(= x_{\left(\frac{n+1}{2}\right)}\)</span></li>
<li>If <span class="math inline">\(n\)</span> is <strong>even</strong>: Median <span class="math inline">\(= \dfrac{x_{(n/2)} + x_{(n/2+1)}}{2}\)</span></li>
</ul>
<p>For grouped data: <span class="math display">\[\text{Median} = L + \left( \frac{\frac{n}{2} - CF}{f} \right) \times h\]</span></p>
<p>where <span class="math inline">\(L\)</span> = lower boundary of the median class, <span class="math inline">\(n\)</span> = total frequency, <span class="math inline">\(CF\)</span> = cumulative frequency before the median class, <span class="math inline">\(f\)</span> = frequency of the median class, <span class="math inline">\(h\)</span> = class width.</p>
</section>
<section id="manual-calculation-3" class="level3">
<h3 class="anchored" data-anchor-id="manual-calculation-3">Manual Calculation</h3>
</section>
<section id="a.-raw-data" class="level3">
<h3 class="anchored" data-anchor-id="a.-raw-data">A. Raw Data</h3>
<p>Dataset A sorted: 88, 92, 95, 98, 101, 104, 108, 112, 118, 125, 250 (<span class="math inline">\(n = 11\)</span>, odd)</p>
<p><strong>Step 1.</strong> Confirm data are sorted (already sorted above).</p>
<p><strong>Step 2.</strong> Since <span class="math inline">\(n = 11\)</span> is odd, the median is the <span class="math inline">\(\left(\frac{11+1}{2}\right) = 6^{th}\)</span> value.</p>
<p><strong>Step 3.</strong> Count to the 6th value: 88(1), 92(2), 95(3), 98(4), 101(5), <strong>104(6)</strong>. <span class="math display">\[\text{Median} = 104 \text{ mg/dL}\]</span></p>
<p>Notice the median (104) is much closer to where most of the data lie than the mean (117.4). Here, the median is <strong>not</strong> pulled by the outlier of 250.</p>
</section>
<section id="b.-frequency-table" class="level3">
<h3 class="anchored" data-anchor-id="b.-frequency-table">B. Frequency Table</h3>
<p>Data Set B (number of children per household):</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th><span class="math inline">\(x\)</span></th>
<th><span class="math inline">\(f\)</span></th>
<th>Cumulative frequency (<span class="math inline">\(CF\)</span>)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0</td>
<td>6</td>
<td>6</td>
</tr>
<tr class="even">
<td>1</td>
<td>10</td>
<td>16</td>
</tr>
<tr class="odd">
<td>2</td>
<td>14</td>
<td>30</td>
</tr>
<tr class="even">
<td>3</td>
<td>7</td>
<td>37</td>
</tr>
<tr class="odd">
<td>4</td>
<td>3</td>
<td>40</td>
</tr>
</tbody>
</table>
<p><strong>Step 1.</strong> Build the cumulative frequency column (shown above).</p>
<p><strong>Step 2.</strong> With <span class="math inline">\(n = 40\)</span> (even), the median position is the average of the <span class="math inline">\(20^{th}\)</span> and <span class="math inline">\(21^{st}\)</span> values.</p>
<p><strong>Step 3.</strong> Locate these positions using <span class="math inline">\(CF\)</span>: the <span class="math inline">\(17^{th}\)</span>–<span class="math inline">\(30^{th}\)</span> values all equal 2 (since <span class="math inline">\(CF\)</span> jumps from 16 to 30 at <span class="math inline">\(x=2\)</span>). Both the <span class="math inline">\(20^{th}\)</span> and <span class="math inline">\(21^{st}\)</span> values fall in this range.</p>
<p><strong>Step 4.</strong> Calculation <span class="math display">\[\text{Median} = \frac{2+2}{2} = 2 \text{ children}\]</span></p>
</section>
<section id="c.-grouped-frequency-distribution-1" class="level3">
<h3 class="anchored" data-anchor-id="c.-grouped-frequency-distribution-1">C. Grouped Frequency Distribution</h3>
<p>Data Set C (age of 50 hypertension patients):</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Class</th>
<th><span class="math inline">\(f\)</span></th>
<th><span class="math inline">\(CF\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>30–39</td>
<td>4</td>
<td>4</td>
</tr>
<tr class="even">
<td>40–49</td>
<td>9</td>
<td>13</td>
</tr>
<tr class="odd">
<td>50–59</td>
<td>15</td>
<td>28</td>
</tr>
<tr class="even">
<td>60–69</td>
<td>13</td>
<td>41</td>
</tr>
<tr class="odd">
<td>70–79</td>
<td>7</td>
<td>48</td>
</tr>
<tr class="even">
<td>80–89</td>
<td>2</td>
<td>50</td>
</tr>
</tbody>
</table>
<p><strong>Step 1.</strong> <span class="math inline">\(n/2 = 50/2 = 25\)</span>.</p>
<p><strong>Step 2.</strong> Find the median class: the class where the cumulative frequency first reaches/exceeds 25. That is the <strong>50–59</strong> class (<span class="math inline">\(CF\)</span> jumps from 13 to 28).</p>
<p><strong>Step 3.</strong> Identify: <span class="math inline">\(L = 49.5\)</span> (lower boundary), <span class="math inline">\(CF = 13\)</span> (cumulative frequency <em>before</em> median class), <span class="math inline">\(f = 15\)</span> (frequency of median class), <span class="math inline">\(h = 10\)</span> (class width).</p>
<p><strong>Step 4.</strong> Apply the formula: <span class="math display">\[\text{Median} = 49.5 + \left( \frac{25 - 13}{15} \right) \times 10 = 49.5 + \left(\frac{12}{15}\right)\times 10 = 49.5 + 8.0 = 57.5 \text{ years}\]</span></p>
</section>
<section id="interpretation-4" class="level3">
<h3 class="anchored" data-anchor-id="interpretation-4">Interpretation</h3>
<p>The median is the value at the 50th percentile — half the observations fall below it, half above.</p>
</section>
<section id="advantages-4" class="level3">
<h3 class="anchored" data-anchor-id="advantages-4">Advantages</h3>
<ul>
<li><strong>Robust to outliers and skewed distributions</strong> (unaffected by extreme values, as shown above).</li>
<li>Can be computed for ordinal data (does not require interval/ratio scale).</li>
<li>Not distorted by open-ended class intervals.</li>
</ul>
</section>
<section id="disadvantages-4" class="level3">
<h3 class="anchored" data-anchor-id="disadvantages-4">Disadvantages</h3>
<ul>
<li>Does not use the actual value of every observation (only their rank/position), so it “wastes” information present in the data.</li>
<li>Less amenable to further algebraic/statistical manipulation than the mean.</li>
<li>Can be less stable (more sampling variability) than the mean for perfectly normal data.</li>
</ul>
</section>
<section id="appropriate-use-4" class="level3">
<h3 class="anchored" data-anchor-id="appropriate-use-4">Appropriate Use</h3>
<p>Preferred over the mean for <strong>skewed distributions</strong> (e.g., income, hospital charges, length of stay) or when outliers are present, and for <strong>ordinal data</strong>.</p>
</section>
<section id="public-health-example-4" class="level3">
<h3 class="anchored" data-anchor-id="public-health-example-4">Public Health Example</h3>
<p><strong>Median household income</strong>, <strong>median survival time</strong> in a cancer study (widely reported instead of mean survival because survival time is typically right-skewed and subject to censoring), <strong>median age at diagnosis</strong>.</p>
</section>
</section>
<section id="the-mode" class="level2">
<h2 class="anchored" data-anchor-id="the-mode">The Mode</h2>
<section id="definition-5" class="level3">
<h3 class="anchored" data-anchor-id="definition-5">Definition</h3>
<p>The <strong>mode</strong> is the value (or category) that occurs most frequently in a data set. Unlike the mean and median, the mode can be identified for <strong>nominal data</strong>, and a data set can have zero, one (unimodal), two (bimodal), or more (multimodal) modes.</p>
</section>
<section id="formula-grouped-data" class="level3">
<h3 class="anchored" data-anchor-id="formula-grouped-data">Formula (Grouped Data)</h3>
<p><span class="math display">\[\text{Mode} = L + \left( \frac{f_1 - f_0}{2f_1 - f_0 - f_2} \right) \times h\]</span></p>
<p>where <span class="math inline">\(L\)</span> = lower boundary of the modal class, <span class="math inline">\(f_1\)</span> = frequency of modal class, <span class="math inline">\(f_0\)</span> = frequency of class before modal class, <span class="math inline">\(f_2\)</span> = frequency of class after modal class, <span class="math inline">\(h\)</span> = class width.</p>
</section>
<section id="manual-calculation-4" class="level3">
<h3 class="anchored" data-anchor-id="manual-calculation-4">Manual Calculation</h3>
</section>
<section id="a.-raw-data-1" class="level3">
<h3 class="anchored" data-anchor-id="a.-raw-data-1">A. Raw Data</h3>
<p>Data Set A: 88, 92, 95, 98, 101, 104, 108, 112, 118, 125, 250. Every value occurs exactly once, So, there is <strong>no mode</strong> for this data set.</p>
<p>Consider instead a small illustrative data set of patient temperatures (°F): 98.6, 99.1, 98.6, 100.2, 98.6, 99.1.</p>
<p><strong>Step 1.</strong> Tally the frequency of each distinct value:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Value</th>
<th>Frequency</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>98.6</td>
<td>3</td>
</tr>
<tr class="even">
<td>99.1</td>
<td>2</td>
</tr>
<tr class="odd">
<td>100.2</td>
<td>1</td>
</tr>
</tbody>
</table>
<p><strong>Step 2.</strong> The value with the highest frequency is the mode:</p>
<p><span class="math inline">\(Mode = 98.6°F\)</span></p>
</section>
<section id="b.-frequency-table-1" class="level3">
<h3 class="anchored" data-anchor-id="b.-frequency-table-1">B. Frequency Table</h3>
<p>For dataset B, the highest frequency is <span class="math inline">\(f = 14\)</span>, occurring at <span class="math inline">\(x = 2\)</span>. <span class="math display">\[\text{Mode} = 2 \text{ children}\]</span></p>
<p>This simply corresponds to the category with the largest tally in the frequency table.</p>
</section>
<section id="c.-grouped-frequency-distribution-2" class="level3">
<h3 class="anchored" data-anchor-id="c.-grouped-frequency-distribution-2">C. Grouped Frequency Distribution</h3>
<p>For the dataset C, mode can be estimated using following steps:</p>
<p><strong>Step 1.</strong> Identify the modal class - the class with the highest frequency: <strong>50–59</strong> (<span class="math inline">\(f_1 = 15\)</span>).</p>
<p><strong>Step 2.</strong> Identify neighboring frequencies: <span class="math inline">\(f_0 = 9\)</span> (40–49 class, before), <span class="math inline">\(f_2 = 13\)</span> (60–69 class, after).</p>
<p><strong>Step 3.</strong> <span class="math inline">\(L = 49.5\)</span>, <span class="math inline">\(h = 10\)</span>.</p>
<p><strong>Step 4.</strong> Apply the formula: <span class="math display">\[\text{Mode} = 49.5 + \left( \frac{15-9}{2(15)-9-13} \right)\times 10 = 49.5 + \left(\frac{6}{8}\right)\times 10 = 49.5+7.5 = 57.0 \text{ years}\]</span></p>
</section>
<section id="interpretation-5" class="level3">
<h3 class="anchored" data-anchor-id="interpretation-5">Interpretation</h3>
<p>The mode identifies the most “popular” or common value/category — useful for describing the peak of a distribution or the most frequent category in nominal data.</p>
</section>
<section id="advantages-5" class="level3">
<h3 class="anchored" data-anchor-id="advantages-5">Advantages</h3>
<ul>
<li>Only measure of central tendency valid for <strong>nominal data</strong>.</li>
<li>Not affected by extreme outliers.</li>
<li>Easy to understand intuitively; represents an actual, commonly-occurring value.</li>
<li>Directly identifies the most frequent category, useful for resource planning (e.g., “most common blood type needed”).</li>
</ul>
</section>
<section id="disadvantages-5" class="level3">
<h3 class="anchored" data-anchor-id="disadvantages-5">Disadvantages</h3>
<ul>
<li>May not exist, or may not be unique (bimodal/multimodal data).</li>
<li>Ignores much of the data (based only on the frequency of the most common value(s)).</li>
<li>Can be unstable in small samples — a small change in the data can shift the mode considerably.</li>
</ul>
</section>
<section id="appropriate-use-5" class="level3">
<h3 class="anchored" data-anchor-id="appropriate-use-5">Appropriate Use</h3>
<p>Best used for <strong>categorical (nominal) data</strong>, or to describe the peak/most common value of any distribution alongside other measures.</p>
</section>
<section id="public-health-example-5" class="level3">
<h3 class="anchored" data-anchor-id="public-health-example-5">Public Health Example</h3>
<p>The <strong>modal blood type</strong> in a blood bank’s donor registry (to guide blood product stocking), or the modal age group affected in an outbreak (identifying which age group to target with an intervention).</p>
</section>
</section>
<section id="quartiles-percentiles-and-deciles" class="level2">
<h2 class="anchored" data-anchor-id="quartiles-percentiles-and-deciles">Quartiles, Percentiles, and Deciles</h2>
<p>Quartiles, percentiles, and deciles are collectively called <strong>measures of position</strong> (or <strong>quantiles</strong>) — they divide an ordered data set into equal-sized parts and are closely related to the median (which is both the 2nd quartile, the 50th percentile, and the 5th decile).</p>
<section id="definitions" class="level3">
<h3 class="anchored" data-anchor-id="definitions">Definitions</h3>
<ul>
<li><strong>Quartiles (</strong><span class="math inline">\(Q_1, Q_2, Q_3\)</span>): Divide data into 4 equal parts. <span class="math inline">\(Q_1\)</span> = 25th percentile, <span class="math inline">\(Q_2\)</span> = median (50th percentile), <span class="math inline">\(Q_3\)</span> = 75th percentile.</li>
<li><strong>Deciles (</strong><span class="math inline">\(D_1 \ldots D_9\)</span>): Divide data into 10 equal parts. <span class="math inline">\(D_5\)</span> = median.</li>
<li><strong>Percentiles (</strong><span class="math inline">\(P_1 \ldots P_{99}\)</span>): Divide data into 100 equal parts. <span class="math inline">\(P_{50}\)</span> = median.</li>
</ul>
</section>
<section id="formula-grouped-data-1" class="level3">
<h3 class="anchored" data-anchor-id="formula-grouped-data-1">Formula (Grouped Data)</h3>
<p><span class="math display">\[Q_k = L + \left( \frac{\frac{kn}{4} - CF}{f} \right)\times h \quad (k=1,2,3)\]</span> <span class="math display">\[P_k = L + \left( \frac{\frac{kn}{100} - CF}{f} \right)\times h \quad (k=1,\ldots,99)\]</span> <span class="math display">\[D_k = L + \left( \frac{\frac{kn}{10} - CF}{f} \right)\times h \quad (k=1,\ldots,9)\]</span></p>
<p>These all use the same logic as the median formula, simply replacing <span class="math inline">\(n/2\)</span> with the appropriate fraction of <span class="math inline">\(n\)</span>.</p>
</section>
<section id="manual-calculation-a.-raw-data" class="level3">
<h3 class="anchored" data-anchor-id="manual-calculation-a.-raw-data">Manual Calculation — A. Raw Data</h3>
<p>Using Data Set A (sorted): 88, 92, 95, 98, 101, 104, 108, 112, 118, 125, 250 (<span class="math inline">\(n=11\)</span>)</p>
<p><strong>Finding</strong> <span class="math inline">\(Q_1\)</span> (25th percentile):</p>
<p><strong>Step 1.</strong> Compute the position: <span class="math inline">\(\dfrac{n+1}{4} = \dfrac{12}{4} = 3^{rd}\)</span> position. <strong>Step 2.</strong> The 3rd value in the ordered list is <strong>95</strong>. <span class="math display">\[Q_1 = 95 \text{ mg/dL}\]</span></p>
<p><strong>Finding</strong> <span class="math inline">\(Q_3\)</span> (75th percentile):</p>
<p><strong>Step 1.</strong> Compute the position: <span class="math inline">\(\dfrac{3(n+1)}{4} = \dfrac{3 \times 12}{4} = 9^{th}\)</span> position. <strong>Step 2.</strong> The 9th value is <strong>118</strong>. <span class="math display">\[Q_3 = 118 \text{ mg/dL}\]</span></p>
<p><strong>Interquartile Range (a byproduct, used in Section 3):</strong> <span class="math inline">\(IQR = Q_3 - Q_1 = 118 - 95 = 23\)</span>.</p>
<div class="callout callout-style-simple callout-tip">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>Several valid methods exist for computing quantile positions with raw data (e.g., the method shown above vs.&nbsp;linear interpolation methods used by software like R, Excel, or SPSS). Minor differences between hand calculations and software output are normal and expected; always report which method/software was used.</p>
</div>
</div>
</div>
</section>
<section id="manual-calculation-c.-grouped-frequency-distribution" class="level3">
<h3 class="anchored" data-anchor-id="manual-calculation-c.-grouped-frequency-distribution">Manual Calculation — C. Grouped Frequency Distribution</h3>
<p>Using Data Set C (age of 50 hypertension patients), find <span class="math inline">\(Q_1\)</span> and <span class="math inline">\(P_{90}\)</span>.</p>
<p><strong>Finding</strong> <span class="math inline">\(Q_1\)</span>:</p>
<p><strong>Step 1.</strong> Position: <span class="math inline">\(\dfrac{kn}{4} = \dfrac{1 \times 50}{4} = 12.5\)</span>. <strong>Step 2.</strong> Find the class where cumulative frequency first reaches 12.5: looking at the <span class="math inline">\(CF\)</span> column (4, 13, 28, 41, 48, 50), this occurs in the <strong>40–49</strong> class (<span class="math inline">\(CF\)</span> jumps from 4 to 13). <strong>Step 3.</strong> <span class="math inline">\(L=39.5\)</span>, <span class="math inline">\(CF_{\text{before}}=4\)</span>, <span class="math inline">\(f=9\)</span>, <span class="math inline">\(h=10\)</span>. <strong>Step 4.</strong> <span class="math display">\[Q_1 = 39.5 + \left(\frac{12.5-4}{9}\right)\times 10 = 39.5+9.44 = 48.9 \text{ years}\]</span></p>
<p><strong>Finding</strong> <span class="math inline">\(P_{90}\)</span> (90th percentile):</p>
<p><strong>Step 1.</strong> Position: <span class="math inline">\(\dfrac{kn}{100} = \dfrac{90\times 50}{100}=45\)</span>. <strong>Step 2.</strong> Find the class where <span class="math inline">\(CF\)</span> first reaches 45: the <strong>70–79</strong> class (<span class="math inline">\(CF\)</span> jumps from 41 to 48). <strong>Step 3.</strong> <span class="math inline">\(L=69.5\)</span>, <span class="math inline">\(CF_{\text{before}}=41\)</span>, <span class="math inline">\(f=7\)</span>, <span class="math inline">\(h=10\)</span>. <strong>Step 4.</strong> <span class="math display">\[P_{90} = 69.5 + \left(\frac{45-41}{7}\right)\times 10 = 69.5+5.71 = 75.2 \text{ years}\]</span></p>
</section>
<section id="interpretation-6" class="level3">
<h3 class="anchored" data-anchor-id="interpretation-6">Interpretation</h3>
<p><span class="math inline">\(Q_1 = 48.9\)</span> years means 25% of hypertension patients in this sample are younger than 48.9 years. <span class="math inline">\(P_{90} = 75.2\)</span> years means 90% of patients are younger than 75.2 years (only 10% are older).</p>
</section>
<section id="advantages-6" class="level3">
<h3 class="anchored" data-anchor-id="advantages-6">Advantages</h3>
<ul>
<li>Provide detailed information about the <strong>shape and spread</strong> of a distribution beyond a single center value.</li>
<li>Robust to outliers (like the median).</li>
<li>Useful for constructing <strong>growth charts</strong>, <strong>reference ranges</strong>, and <strong>box plots</strong>.</li>
</ul>
</section>
<section id="disadvantages-6" class="level3">
<h3 class="anchored" data-anchor-id="disadvantages-6">Disadvantages</h3>
<ul>
<li>Do not summarize the data in a single number; require reporting multiple values.</li>
<li>Can be sensitive to the choice of interpolation method, especially in small samples.</li>
</ul>
</section>
<section id="appropriate-use-6" class="level3">
<h3 class="anchored" data-anchor-id="appropriate-use-6">Appropriate Use</h3>
<p>Used whenever the <strong>position</strong> of an individual within a distribution matters — growth charts (a child’s weight at the 15th percentile), setting clinical reference ranges, identifying high-risk groups (e.g., the top decile of BMI).</p>
</section>
<section id="public-health-example-6" class="level3">
<h3 class="anchored" data-anchor-id="public-health-example-6">Public Health Example</h3>
<p><strong>Pediatric growth charts</strong> (WHO/CDC) report a child’s weight-for-age and height-for-age as a <strong>percentile</strong>, e.g., “this infant’s weight is at the 25th percentile,” meaning 25% of same-age, same-sex infants weigh less.</p>
</section>
</section>
<section id="comparing-all-measures-of-central-tendency" class="level2">
<h2 class="anchored" data-anchor-id="comparing-all-measures-of-central-tendency">Comparing All Measures of Central Tendency</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>Measure</th>
<th>Data type</th>
<th>Uses all data?</th>
<th>Affected by outliers?</th>
<th>Unique?</th>
<th>Algebraically tractable?</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Arithmetic mean</td>
<td>Interval/ratio</td>
<td>Yes</td>
<td>Highly</td>
<td>Yes</td>
<td>Yes</td>
</tr>
<tr class="even">
<td>Weighted mean</td>
<td>Interval/ratio</td>
<td>Yes</td>
<td>Highly</td>
<td>Yes</td>
<td>Yes</td>
</tr>
<tr class="odd">
<td>Geometric mean</td>
<td>Ratio (positive only)</td>
<td>Yes</td>
<td>Moderately</td>
<td>Yes</td>
<td>Yes (on log scale)</td>
</tr>
<tr class="even">
<td>Harmonic mean</td>
<td>Ratio (positive only)</td>
<td>Yes</td>
<td>Least (of the 3 means)</td>
<td>Yes</td>
<td>Yes</td>
</tr>
<tr class="odd">
<td>Median</td>
<td>Ordinal, interval, ratio</td>
<td>No (only rank used)</td>
<td>No (robust)</td>
<td>Yes</td>
<td>Limited</td>
</tr>
<tr class="even">
<td>Mode</td>
<td>Nominal, ordinal, interval, ratio</td>
<td>No</td>
<td>No (robust)</td>
<td>Not always</td>
<td>No</td>
</tr>
<tr class="odd">
<td>Quartiles/Percentiles/Deciles</td>
<td>Ordinal, interval, ratio</td>
<td>No (rank-based)</td>
<td>No (robust)</td>
<td>Yes</td>
<td>Limited</td>
</tr>
</tbody>
</table>
<section id="choosing-the-right-measure-effect-of-skewness" class="level3">
<h3 class="anchored" data-anchor-id="choosing-the-right-measure-effect-of-skewness">Choosing the Right Measure — Effect of Skewness</h3>
<div class="cell" data-layout-align="default">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode default code-with-copy"><code class="sourceCode default"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>flowchart TD</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>    A[Is the variable numeric?] --&gt;|No, categorical| B[Use Mode]</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>    A --&gt;|Yes| C{Is the distribution roughly symmetric, no major outliers?}</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>    C --&gt;|Yes| D[Use Mean]</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>    C --&gt;|No: skewed or has outliers| E[Use Median]</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>    D --&gt; F{Is the data multiplicative / ratios / log-normal, e.g. titers?}</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>    F --&gt;|Yes| G[Consider Geometric Mean]</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>    F --&gt;|No| D</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD
    A[Is the variable numeric?] --&gt;|No, categorical| B[Use Mode]
    A --&gt;|Yes| C{Is the distribution roughly symmetric, no major outliers?}
    C --&gt;|Yes| D[Use Mean]
    C --&gt;|No: skewed or has outliers| E[Use Median]
    D --&gt; F{Is the data multiplicative / ratios / log-normal, e.g. titers?}
    F --&gt;|Yes| G[Consider Geometric Mean]
    F --&gt;|No| D
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p><strong>Relationship between mean, median, and skewness:</strong></p>
<ul>
<li><strong>Symmetric distribution:</strong> Mean ≈ Median ≈ Mode.</li>
<li><strong>Right-skewed (positively skewed) distribution</strong> (e.g., income, hospital charges, our Data Set A with the outlier of 250): Mean &gt; Median &gt; Mode.</li>
<li><strong>Left-skewed (negatively skewed) distribution</strong> (e.g., age at death from a disease mostly affecting the elderly): Mean &lt; Median &lt; Mode.</li>
</ul>
<p>In Data Set A: Mean = 117.4, Median = 104 — the mean exceeds the median, correctly signaling a right-skewed distribution due to the outlier.</p>
</section>
</section>
<section id="summary" class="level2">
<h2 class="anchored" data-anchor-id="summary">Summary</h2>
<ul>
<li>The <strong>mean</strong> is the most commonly used and mathematically useful measure, but it is sensitive to outliers and skewness.</li>
<li>The <strong>weighted mean</strong> correctly combines subgroup values with different levels of importance/sample size.</li>
<li>The <strong>geometric mean</strong> and <strong>harmonic mean</strong> are specialized means for multiplicative data and rates, respectively; <span class="math inline">\(HM \le GM \le AM\)</span>.</li>
<li>The <strong>median</strong> is robust to outliers and skewness and is preferred for skewed public health data such as income or survival time.</li>
<li>The <strong>mode</strong> is the only central tendency measure usable with nominal data.</li>
<li><strong>Quartiles, percentiles, and deciles</strong> describe an individual’s position within a distribution and underlie growth charts and reference ranges.</li>
</ul>
<p>Section 3 builds directly on these concepts by covering <strong>measures of dispersion</strong>, which quantify how spread out the data are around these central values.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../Section2/01_introduction_descriptive_statistics.html" class="pagination-link" aria-label="Introduction to Biostatistics">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-title">Introduction to Biostatistics</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../Section2/03_measures_of_dispersion.html" class="pagination-link" aria-label="Measures of Dispersion">
        <span class="nav-page-text"><span class="chapter-title">Measures of Dispersion</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/Adrisyaone/epidemiologyR.git/edit/main/Section2/02_measures_central_tendency.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/Adrisyaone/epidemiologyR.git/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div></div></footer><script src="../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>